### ISSUE TITLE
[kiwix-builder] Handle cross-compilation on Windows of kiwix-lib et kiwix-tools.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-tools#1]
kiwix-builder should handle compilation of kiwix for windows of kiwix-tools and kiwix-serve

**Comment by kelson42** [comment]
@mgautierfr I guess this depends on https://github.com/kiwix/kiwix-build/issues/2 ? Let me know as soon as I can go ahead on this.

**Comment by kelson42** [comment]
This is done CI works.
