### ISSUE TITLE
Build deb (for Debian repos)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#10]
To do, one time the kiwix-lib is packaged.

**Comment by kelson42** [comment]
Here is the RFP https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856595

**Comment by JoaoPir** [comment]
Any progress on this? kiwix-lib is already packaged (but at version 0.2). Would be great if kiwix-tools was in Debian before the buster freeze (between summer and the end of the year?). Thanks!

**Comment by kelson42** [comment]
@legoktm is currently having a look, but we first need to introduce libaria2(-dev) packages as this is a new dependency of libkiwix.

**Comment by legoktm** [comment]
As an update, libzim is nearly ready to be upgraded to v4, which will allow us to upgrade libkiwix to v2 (also nearly done), which will allow us to get to kiwix-tools :)

The aria2 dependency issue was solved a few days ago thanks to Kartik, another Wikimedian DD :) (https://tracker.debian.org/news/972752/accepted-aria2-1340-2-source-amd64-into-unstable-unstable/)

**Comment by kelson42** [comment]
@legoktm is currently working on it.

**Comment by legoktm** [comment]
My current packaging work is at https://salsa.debian.org/legoktm/kiwix-tools

I've gone through most of kiwix-serve and kiwix-manage, the only issues I've identified are #249 and #250 (the latter of which I've worked around).

**Comment by kelson42** [comment]
@legoktm Any update available?

**Comment by legoktm** [comment]
kiwix-tools is currently waiting in Debian's NEW queue: https://ftp-master.debian.org/new/kiwix-tools_3.1.2-1.html
