### ISSUE TITLE
Kiwix-Serve doesn't serve all images

### ISSUE THREAD

**Issue by darkenvy** [kiwix/kiwix-tools#101]
`ERR_CONNECTION_REFUSED` is returned on some images. I don't know how it picks the images to not serve. Extracting the entire zim with `zimdump input.zim -D outputFolder/` shows that the image is still in the zim.

I have a list of 234 images in this zim that could not be served. I attached the zim as well:

https://drive.google.com/open?id=1HmofbQexJCY1diW36wJeuMTw80iCqxIT
https://drive.google.com/open?id=1zD62xhdFs7AU-ilXactduMANLYB9XdaN

**Comment by kelson42** [comment]
@darkenvy Which exact version of kiwix-serve do you use?

**Comment by kelson42** [comment]
@darkenvy As far as I can see all the image are displayed correctly with last kiwix-serve nightly. Please reopen the bug if you still have the problem with this version of kiwix-serve and be extremly specific (at least one example) about what goes wrong.

**Comment by darkenvy** [comment]
Turns out this was a duplicate ticket from last week. It was a busy week for me at work :\. Forgot Matthieu fixed it.

However, the kiwix nightly latest folder is empty or has dates in the filename. So my docker never gets the latest kiwix-tools. Should I make a ticket for that? (example: http://download.kiwix.org/nightly/latest/kiwix-tools_linux64_2017-11-10.tar.gz <- name always changes. No static filename)

Appologies for the ticket.

**Comment by kelson42** [comment]
@darkenvy, yes please in the kiwix-build repo.
