### ISSUE TITLE
~30% of images missing & FT search not working in wikipedia_ht_all_novid_2017-08.zim & kiwix-serve often fails to launch properly

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#102]
(1) Any idea why 5-of-12 photos are missing @ new-ZIM http:// iiab . me : 3000 /wikipedia_ht_all_novid_2017-08/A%2fVeintiseis%5fde%5fJulio%2c%5fVilla%5fClara%2ehtml downloaded from http://download.kiwix.org/zim/wikipedia/wikipedia_ht_all_novid_2017-08.zim ?

In Comparison: only 1-of-12 photos were missing @ year-old http:// iiab . me : 3000 /wikipedia_ht_all_2016-11/A%2fVeintiseis_de_Julio%2c_Villa_Clara.html downloaded from http://download.kiwix.org/portable/wikipedia/kiwix-0.9+wikipedia_ht_all_2016-11.zip

(2) Any idea why Full Text Search is not available?  http:// iiab . me : 3000 /search?content=wikipedia_ht_all_novid_2017-08&pattern=suisse shows "Not Found...There is no article with the title "suisse" and the fulltext search engine is not available for this content."

(3) Is there a better way to install this ZIM and others than https://github.com/iiab/iiab/blob/master/roles/kiwix/templates/iiab-make-kiwix-lib ?  Something like 75% of the almost-150 ZIM's **disappear** from server http:// iiab . me : 3000 when iiab-make-kiwix-lib (pasted in below) is on run newly installed ZIM's like this one:

> systemctl_program stop kiwix-serve
/usr/bin/[iiab-make-kiwix-lib.py](https://github.com/iiab/iiab/blob/master/roles/kiwix/templates/iiab-make-kiwix-lib.py)
/usr/bin/[iiab-make-apache-config.py](https://github.com/iiab/iiab/blob/master/roles/kiwix/templates/iiab-make-apache-config.py)
systemctl_program start kiwix-serve

As a workaround, running `systemctl restart kiwix-serve` a few minutes later solves the problem of ~75% of our ZIM files not displaying at http:// iiab . me : 3000

**Comment by mgautierfr** [comment]
Please open a different issue per problem.

> Any idea why 5-of-12 photos are missing

I have all the 12 photos with last nightly of kiwix-serve 2017-11-12

> Any idea why Full Text Search is not available?

The zim file doesn't contain a full text index. You can check this in http://mirror.download.kiwix.org/library/library_zim.xml. There is no tag `_ftindex` for the `wikipedia_ht_all_novid_2017-08.zim`.
If you want it, you should open a issue on https://github.com/openzim/mwoffliner side who is generating the zim file.

>  Is there a better way to install this ZIM and others than ...

I don't know where your problem come from. The fact that a `systemctl restart kiwix-serve` works make me think that the library.xml is correttly written. 
And I'm not sure to well understand your problem. You say it is on newly installed ZIM and in the same time, zim files disappear.

**Comment by holta** [comment]
> I have all the 12 photos with last nightly of kiwix-serve 2017-11-12

Amazing!  Worked or me too, Thx!

> open a issue on https://github.com/openzim/mwoffliner

Done: https://github.com/openzim/mwoffliner/issues/160 "Haiti's wikipedia_ht_all_novid_2017-08.zim is missing its internal index"

> I don't know where your problem come from. The fact that a systemctl restart kiwix-serve works make me think that the library.xml is correttly written.

I'll ask @tim-moody to monitor this on his server.  The fact that `systemctl start kiwix-serve` fails to launch kiwix-serve 0.3.0 properly (and often, upon installing new ZIM's) BUT `systemctl restart kiwix-serve` works a few minutes later...suggests a possible timing issue?

**Comment by holta** [comment]
Apologies if these 3 issues are in fact unrelated &mdash; I was not sure.

**Comment by mgautierfr** [comment]
> suggests a possible timing issue?

Possibly yes. It would be surprising as `systemctl start kiwix-serve` should be launch after `iiab-make-kiwix-lib.py` has finished. But the behaviour is a classical symptom of timing issue.

> Apologies if these 3 issues are in fact unrelated — I was not sure.

No problem. It is easier (and better) to mark two issues a duplicate than splitting one issues in two.

**Comment by kelson42** [comment]
@holta @mgautierfr Unfortunatly (1) seems to be quite a valid bug :( I have open a dedicated ticket at #108. The other topics seem to have been answered or do not consider directly kiwix-serve. So I will close this ticket.
