### ISSUE TITLE
Nighly kiwix-serve seems to be unable to open a simple library XML file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#103]
```
$ kiwix-serve --library --port=8081 test.xml
Unable to open the XML library file 'test.xml'.
```
The XML file can be found here:
http://tmp.kiwix.org/test.xml

**Comment by kelson42** [comment]
@mgautierfr Please have a look to that probleme. This sounds like a stupid problem... but this is still a blocker for one of the milestone :(

**Comment by mgautierfr** [comment]
Duplicate of https://github.com/kiwix/kiwix-tools/issues/70
