### ISSUE TITLE
Avoid one IP to take all the connections of the pool

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#106]
libmicrohttps proposes To avoid one MHD_OPTION_PER_IP_CONNECTION_LIMIT which seems to be adapted to that.

**Comment by kelson42** [comment]
I believe it should be 6. See https://docs.pushtechnology.com/cloud/latest/manual/html/designguide/solution/support/connection_limitations.html

**Comment by kelson42** [comment]
@juuz0 Do you think you could implement this please? `6` should be the default value, but it would be good to implement an option to allow to change it: `--maxConnectionsPerIP`

**Comment by juuz0** [comment]
@kelson42 Thanks, I'll look into it. You can assign me :)

**Comment by kelson42** [comment]
See my email to the microhttpd mailinglist at https://lists.gnu.org/archive/html/libmicrohttpd/2022-02/index.html
