### ISSUE TITLE
kiwix-serve forces you to do a MULTI-ZIM search, instead of the "25 per page" search results at bottom

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#109]
`http:// iiab . me : 3000 /search?content=20171105_Eihwaz_frwiki_4.7gb_75p&pattern=haiti` quickly/properly shows 1,206 results, within this single ZIM.

The problem is the "< 1 2 3 4 5 6 7 8 9 10 >" links at the bottom of the above page.  For example click on "1" (which is supposed to give you the 1st 25 search results) _but in fact you will get an entirely different search_, across all ZIM files on this server, painfully (!) taking many minutes: 

`http:// iiab . me : 3000 /search?pattern=haiti&start=0&end=25` (eventually shows 21,222 results, across almost 150 ZIM files on this server)

Context: this server (iiab . me) is running kiwix-serve from http://download.kiwix.org/nightly/2017-11-12/kiwix-tools_linux64_2017-11-12.tar.gz on Debian 9.1

Somewhat Related: #97

Thanks to @deldesir in Haiti who uncovered this bug!

**Comment by holta** [comment]
Just to confirm this bug occurs on all versions of kiwix-tools that I've tested from 2017-08-28 up to very latest nightly e.g. http://download.kiwix.org/nightly/2017-11-23/kiwix-tools_linux64_2017-11-23.tar.gz

I am hopeful this serious usability problem might be fixable in 2017!

**Comment by mgautierfr** [comment]
This will be fixed with kiwix/kiwix-lib#99 and #115.
