### ISSUE TITLE
Publish kiwix-tools for i686 archictecture

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#112]
Currently on OLPC's 32-bit XO laptops in the developing world we are using:
http://download.kiwix.org/bin/0.9/kiwix-0.9-linux-i686.tar.bz2 (30-Oct-2014)

As this is more than 3 years old and failing with new content, we're also experimenting with:
http://download.kiwix.org/bin/0.10/kiwix-0.10-linux-i686.tar.bz2 (26-Oct-2016)

With essentially all new ZIM content coming online at the end of 2017 having an internal index in the ZIM file, the above strategies are no longer working :-(

Can compiler flags hopefully be set to publish kiwix-tools (kiwix-serve, kiwix-manage) for the i686 architecture as well?  Ideally publishing to http://download.kiwix.org/nightly/ and also upholding the i686 tradition @ http://download.kiwix.org/bin/ ?

_Context: 3 million of OLPC's XO laptops were manufactured, and several 100,000 are today in active use, where Wikipedia on Kiwix is often the most adored of all apps/content when it is installed!  A special thank you to @georgejhunt & @darkenvy whose field community/integration has made this work a centerpiece in Haiti, Ghana, Mexico etc, where we distribute different versions of WikipediaFR, WikipediaHT, WikipediaEN and WikipediaES._

**Comment by kelson42** [comment]
@holta Do you have the exact models of CPUs? I remember having difficulties to make kiwix-serve working with Intel Atom devices (not supporting MMX2 instructions)?

**Comment by kelson42** [comment]
@mgautierfr I suspect this should be quite easy to get nightlies compiling for i686 too?

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-build#94
