### ISSUE TITLE
kiwix-serve displays ZIM but it's not on main page http://box:3000

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#114]
The Haitian Wikipedia ZIM publicly viewable at `http:// iiab . me : 3000 /wikipedia_ht_all_2016-12/` (obtained from source ZIPFILE `http:// iiab . me /local_content/kiwix-0.9+wikipedia_ht_all_2016-12.zip`) works[*] with the very latest kiwix-tools from http://download.kiwix.org/nightly/2017-11-23/kiwix-tools_linux64_2017-11-23.tar.gz on Debian 9.1

However the server's main/index page at `http:// iiab . me : 3000` does not display this particular ZIM &mdash; despite running "systemctl restart kiwix-serve" several times &mdash; is this a known issue?  HTML View Source confirms the link to this ZIM is missing.

[*] ASIDE: a few images/graphics are missing on the ZIM's main page `http:// iiab . me : 3000 /wikipedia_ht_all_2016-12/` (on the right side, halfway down).  However I do not consider this very serious, as all other images within the ZIM itself seem to appear properly, e.g. `http:// iiab . me : 3000 /wikipedia_ht_all_2016-12/A%2fVeintiseis%5fde%5fJulio%2c%5fVilla%5fClara%2ehtml`

**Comment by kelson42** [comment]
@holta You reported a few weeks/days ago this file (wikipedia_ht_all_2016-12.zim) as problematic and it has been therefore removed from our offer and is neither available anymore on download nor supported by us. Better use the most recent or wikipedia_ht_all_2016-11.zim

**Comment by holta** [comment]
> You reported a few weeks/days ago this file (wikipedia_ht_all_2016-12.zim) as problematic

Interestingly you and I were wrong 2 weeks ago (!) as the latest kiwix-tools has now fixed 99+% of the problems that you and I both thought were part of the ZIM itself &mdash; but were in fact problems with kiwix-tools.

This is extremely good news that the new kiwix-tools displays many legacy ZIM's properly that it failed to display as recently as 2 weeks ago, amazing!

I do remain concerned however, that kiwix-serve accidentally fails to link to legacy ZIM's that remain in circulation in various communities' hands, even if this is not the highest-priority bug understandably~

**Comment by mgautierfr** [comment]
> I do remain concerned however, that kiwix-serve accidentally fails to link to legacy ZIM's that remain in circulation in various communities' hands, even if this is not the highest-priority bug understandably~

This is not related to legacy ZIM's. It was simply a bug in kiwix-tools and the bug were present for all ZIM's.

**Comment by holta** [comment]
> This is not related to legacy ZIM's. It was simply a bug in kiwix-tools and the bug were present for all ZIM's.

I've confirmed that this is now fixed in http://download.kiwix.org/nightly/2017-11-26/kiwix-tools_linux64_2017-11-26.tar.gz, Thank you!
