### ISSUE TITLE
missing zims in library_zim.xml

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#118]
my understanding is that library_zim.xml is a catalog of http://download.kiwix.org/zim/

I do not see the medical wikis with video for either EN or ES (probably others)

http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2017-10.zim
http://download.kiwix.org/zim/wikipedia/wikipedia_es_medicine_2017-10.zim

**Comment by tim-moody** [comment]
Think the same is true for https://ftp.nluug.nl/pub/kiwix/library/library.xml

**Comment by kelson42** [comment]
@tim-moody Problem should be fixed, wikipedia_en_medicine_2017-10.zim is not in the libraries... might takes a few hours to get the file mirrored everywhere.
