### ISSUE TITLE
CI kiwix-tools basic integration with Travis

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#12]
For each new commit to master, CI should run and:
* Build statically on Fedora and Ubuntu
* Build Dynamically on Fedora and Ubuntu

**Comment by kelson42** [comment]
@mgautierfr The problem for that ticket is that travis does only provide ubuntu vms, do I'm right?

**Comment by mgautierfr** [comment]
Yes. Travis provides only ubuntu and macos vms.

**Comment by kelson42** [comment]
The Travis CI works fine with "old" Ubuntu OSes. See #41 for the Fedora stuff.
