### ISSUE TITLE
New function to get details about location of an article

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#121]
We need a method, for each content to know:
* In which file (path) an article is located (so it might be in a ZIM chunk)
* The offset in bytes from the start of that file
* If the content is not found or if the content is compressed in a cluster return empty string and 0

This is need because on Android, Kiwix needs to build a filedescriptor based on these information to play properly videos. See https://github.com/kiwix/kiwix-android/issues/277#issuecomment-348783383

**Comment by mgautierfr** [comment]
Fixed in kiwix/kiwix-lib#102
