### ISSUE TITLE
Pneumonia article missing in search results

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#124]
to reproduce view http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2017-11.zim in
http://download.kiwix.org/nightly/2017-12-01/kiwix-tools_armhf_2017-12-01.tar.gz

search for pneumonia

there is an article Pneumonia but it does not appear in the list of articles, but it does appear in the list of articles 'containing ...'

Can this be because there is an article Pneumonia Alba that appears in the search results, of which Pneumonia is a substring?

Note that this problem does not exist in http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2017-10.zim, which has only the Pneumonia article and not the Pneumonia Alba article.

**Comment by kelson42** [comment]
@tim-moody I confirm the bug
@mgautierfr Might that be that for any reason it matches but not in the list of 10 first results (so not displayed as a suggestion?)

**Comment by tim-moody** [comment]
![image](https://user-images.githubusercontent.com/5678731/33571303-99ac54aa-d8fd-11e7-94ff-fa1cab1dbdee.png)

I think a direct match should be in the top results

**Comment by kelson42** [comment]
@tim-moody Yes, but it might be a quite more complex problem than it looks like :)

**Comment by tim-moody** [comment]
@kelson42 no doubt; it usually is :), but I'm sure you and @mgautierfr can solve it.

**Comment by kelson42** [comment]
With today nightly I can not reproduct the problem:
http://library.kiwix.org/wikipedia_en_medicine_2018-01/

Looks like the problem has been fixed.
