### ISSUE TITLE
formatting tags in search results

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#125]
to reproduce view http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2017-11.zim in
http://download.kiwix.org/nightly/2017-12-01/kiwix-tools_armhf_2017-12-01.tar.gz

search for pneumonia

results include <i>Pneumocystis</i> pneumonia where <i> are the italics.

**Comment by kelson42** [comment]
Duplicate of https://github.com/openzim/mwoffliner/issues/159.
