### ISSUE TITLE
Difference between bare "LANG_all" zim and "LANG_all_novid"

### ISSUE THREAD

**Issue by yassinei** [kiwix/kiwix-tools#126]
I don't know the correct place to ask this, but what is the difference between for example "en_all" and "en_all_novid"? The latter file as of today seems to be a lot newer.

**Comment by kelson42** [comment]
@yassinei  no problem.

* en_all means with all pictures and videos and sounds (except before summer 2017 where videos/sounds where not included)
* en_all_novid mean without the videos/sounds (so basically like en_all before summer 2017).
