### ISSUE TITLE
ZIM embeded index doesn't seem to be taken into consideration

### ISSUE THREAD

**Issue by yassinei** [kiwix/kiwix-tools#128]
I'm using kiwix-serve with the file `wikipedia_en_all_novid_2017-08.zim`, using this simple command: `kiwix-serve --port=8090 /mnt/toshiba/wikipedia_en_all_novid_2017-08.zim`, and I think that full text search isn't working. This is the verbatim error: `There is no article with the title "thing to look for" and the fulltext search engine is not available for this content.`

**Comment by kelson42** [comment]
@yassinei Yes, the fulltext index are not included in this ZIM file. This is one of the last of this kind, all future ZIM files we produce should have it. Two solutions:
* Wait one month or two to get the new version with the ft index
* Download the corresponding portable file in http://download.kiwix.org/portable/ and use the separated index packaged in that ZIP file.
