### ISSUE TITLE
Improve the 'usage' information for kiwix-manage

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-tools#129]
The current 'usage' information for several of the kiwix tools isn't sufficiently clear to enable a novice to use them. The two tools I tried are `kiwix-install` and `kiwix-manage`, the others may also benefit from improvements to the usage statements they emit when run.

After a working session with @kelson42 I now have a better idea of what usage would be valuable so I'm happy to try improving the information emitted by these utilities. It'd also be healthy to revise the documentation on the Kiwix wiki, again I'm happy to do so.

**Comment by kelson42** [comment]
kiwix-install will be removed, see #189, so this is only necessary for kiwix-manage

**Comment by kelson42** [comment]
See also #275
