### ISSUE TITLE
kiwix-serve - other ebook reader support possible?

### ISSUE THREAD

**Issue by Uwe-B** [kiwix/kiwix-tools#13]
I saw on sourceforge that you provided some changes in 2015 to the code of kiwix-serve, helping to run it on Bookeen Cybook ebook readers (mainly in the css section).
I got version 0.9 from 2014 of kiwix-serve (without the Bookeen additions) running on a Pocketbook 626 but wonder, if the Bookeen version could be changed to recognize Pocketbook headers too:
Mozilla/5.0 (Linux like Android; de-DE) AppleWebKit/534.34 PocketBook/630 (screen 758x1024; FW U630.5.321) Mobile
or
Mozilla/5.0 (Linux like Android; de-DE) AppleWebKit/534.34 PocketBook/626 (screen 758x1024; FW W626.5.14.964) Mobile
or
Mozilla/5.0 (Linux like Android; de-DE) AppleWebKit/534.34 PocketBook/631 (screen 1072x1448; FW U631.5.321) Mobile
or
Mozilla/5.0 (Linux like Android; en-US) AppleWebKit/534.34 PocketBook/623 (screen 758x1024; FW M623.4.3.267) Mobile

Do You see a way to include Pocketbook devices too into kiwix-serve and get a newer ARM compiled binary? I'm sure a lot of users would like to use offline wikidumps via kiwix on their device.
Regards, Uwe

**Comment by kelson42** [comment]
As far as I know, the Bookeen ebook reader just use a specific CSS class: "cybook" if I correctly understand the source code. @rgaudin You confirm? So, to apply this kind of customization to your model, you probably would need to know which kind of CSS class is used.

**Comment by Uwe-B** [comment]
The CSS class "cybook" ist preselected in "include.html.part":
  /* cybook hack */
21	  if (navigator.userAgent.indexOf("bookeen/cybook") != -1) {
22	  	jk("html").addClass("cybook");

**Comment by kelson42** [comment]
@Uwe-B indeed... Do you know the user-agent of the tablet browser?

**Comment by Uwe-B** [comment]
Yes I gave some examples in the first Post. Mine is Pocketbook 626 so the useragent header lokes like this:

Mozilla/5.0 (Linux like Android; de-DE) AppleWebKit/534.34 PocketBook/626 (screen 758x1024; FW W626.5.14.964) Mobile

**Comment by kelson42** [comment]
OK, so beside the patch, the point is to recompile for ARM. This tickets seems to depends on https://github.com/kiwix/kiwix-build/issues/6

**Comment by Uwe-B** [comment]
It is not that urgent, I still have other ways to access wikis on other devices. 2 month is better than nothing. Thanks!

**Comment by kelson42** [comment]
@Uwe-B We have finally nightly builds for ARM. Could you try http://download.kiwix.org/nightly/2017-04-29/kiwix-tools_armhf_2017-04-29.tar.gz for example?

**Comment by Uwe-B** [comment]
Thanks for the effort and the notification.
I downloaded it and will try it out the next week.

Datum:	Sat, 29 Apr 2017 08:30:28 -0700
Von:	Kelson <notifications@github.com>
Antwort an:	kiwix/kiwix-tools <reply@reply.github.com>
An:	kiwix/kiwix-tools <kiwix-tools@noreply.github.com>
Kopie an:	Uwe-B <nannys.hedgehog@googlemail.com>, 
	Mention <mention@noreply.github.com>
Betreff:	Re: [kiwix/kiwix-tools] kiwix-serve - other ebook reader support
	possible? (#13)

> 
> @Uwe-B We have finally nightly builds for ARM. Could you try 
> http://download.kiwix.org/nightly/2017-04-29/kiwix-tools_armhf_2017-04-29.tar.gz for example?
> -
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by kelson42** [comment]
I close the ticket. @Uwe-B Please open a new one if you have a bug report or an other question.

**Comment by Uwe-B** [comment]
In the meantime I changed the reader so it took me some time to answer to your efforts.
Today I installed kiwix-serve on a Kobo Glo HD and it is working well. Thank you!
I made a video to show it:
https://youtu.be/ILvGf4OlA2U
