### ISSUE TITLE
Warrington *does* exist even if search doesn't always want to recognise it :)

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-tools#131]
Here's a specific instance of what appears to be a bug. Warrington exists in our tests file and is returned for search queries such as `a` and `Wa` but not for `War`

```
kiwix-search wikipedia_fr_test_2017-11.zim a
Warrington
Orbite héliosynchrone
Sven-Åke Johansson

kiwix-search wikipedia_fr_test_2017-11.zim wa
Warrington
[cleanroom@kafka-vm-0 ~]$ kiwix-search wikipedia_fr_test_2017-11.zim Wa
Warrington
```
I then get no results until the last which also returns 'Summary'  - presumably that mentions the fine location by name?
```
[cleanroom@kafka-vm-0 ~]$ kiwix-search wikipedia_fr_test_2017-11.zim War
[cleanroom@kafka-vm-0 ~]$ kiwix-search wikipedia_fr_test_2017-11.zim Warr
[cleanroom@kafka-vm-0 ~]$ kiwix-search wikipedia_fr_test_2017-11.zim Warri
[cleanroom@kafka-vm-0 ~]$ kiwix-search wikipedia_fr_test_2017-11.zim Warring
[cleanroom@kafka-vm-0 ~]$ kiwix-search wikipedia_fr_test_2017-11.zim Warringt
[cleanroom@kafka-vm-0 ~]$ kiwix-search wikipedia_fr_test_2017-11.zim Warringto
[cleanroom@kafka-vm-0 ~]$ kiwix-search wikipedia_fr_test_2017-11.zim Warrington
Warrington
Summary
```
The behaviour is similar for `kiwix-serve` and `kiwix-search`. No results from `War` to `Warringto`, etc.

BTW: The search for `a` returns 3 results. When I checked the contents by serving this file using `kiwix-serve` I can see `Orbite héliosynchrone`'s snippet contains **`A`**`-B-C`[i] and `Sven-Åke Johansson` because of `Il `**`a`**` joué notamment avec`. I'd have expected at least this last instance to be rejected as `a` would be a stop word (one that's ignored). 

[i] Sorry about the extra space that appears when A-B-C is formatted, it's not really there in the search result.

**Comment by holta** [comment]
Likely related to https://github.com/kiwix/kiwix-tools/issues/124 "Pneumonia article missing in search results"

**Comment by kelson42** [comment]
Everything works as intent here AFAIK. You are just mixing concepts like "suggestions" and "fulltext search". The kiwix-search does only provide the second. No answer means no work matching your pattern, which so far I can see is the case.
