### ISSUE TITLE
kiwix-search should report about missing ft index

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#138]
If a ZIM file is missing the ft index then kiwix-search should:
* return `1` (or any not null error code)
* print an error on STDERR reporting the missing of the index (and therefore the impossibility to run the search properly).

This should work with and without the `--suggestion` option. In case of `--suggestion`, as we have a fallback solution (based on native ZIM title list), the returned value should be 0, the error message should be printed on `STDERR` as a warning.

Requirement comes from #130 discussion

**Comment by julianharty** [comment]
Yay, thank you.

**Comment by arjun-369** [comment]
I'd like to resolve this issue. The code can be traced from kiwix-search.cpp to reader.cpp, that provides a method to check if a fulltext index exists within a .zim file.
The ZIM files from #130 aren't available.
Can you provide me with some ZIM files which can be used to test the code.

**Comment by kelson42** [comment]
I don't think we have one but You can build one pretty easily with mwoffliner

**Comment by arjun-369** [comment]
![Screenshot from 2021-04-07 15-05-47](https://user-images.githubusercontent.com/68965236/113845500-363f7280-97b3-11eb-9d90-fe478680cca4.png)
In the above image, the ZIM file "wikipedia_en_sociology_nopic_2021-03.zim" contains a fulltext index while the ZIM file "wikiquote_en_all_2021-04.zim" does not contain a fulltext index.

**Comment by kelson42** [comment]
@arjun-369 Seems you are on the right path, check that all the requirements of the ticket are fullfilled and open  a PR please

**Comment by mgautierfr** [comment]
> This should work with and without the --suggestion option. In case of --suggestion, as we have a fallback solution (based on native ZIM title list), the returned value should be 0, the error message should be printed on STDERR as a warning.

In kiwix-search tool, we always the kiwix-lib's `Searcher` to do the search (suggestion or not).
The `Searcher` always use the xapian database, the fallback is made by the `Reader`.

I've tried to change this https://github.com/kiwix/kiwix-tools/pull/136 but you disagree about that (we probably had a discussion elsewhere to agree to drop it).

**Comment by mgautierfr** [comment]
I've missed read the @kelson42 comment. It was about the return code, not making the suggestion using the fallback.
So I agree.
