### ISSUE TITLE
kiwix-serve index page computation is too expensive

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#143]
This is in particulary true if many ZIM files are loaded. IMO it is acceptable to read the ZIM files metadata one time to build that index page one time, but then there is not reason anymore. This page, and everything needed to build it should be cached in memory.

This ticket is strongly linked to https://github.com/kiwix/kiwix-tools/issues/142 and https://github.com/kiwix/kiwix-tools/issues/139

**Comment by mgautierfr** [comment]
As said in #140, the index page is already generate only once at the launch of kiwix-serve process. kiwix-serve only serve a static content when a browser request for the index page.

**Comment by kelson42** [comment]
@mgautierfr Thank you for this clarification. I thought I was able to generate a CPU pick each time I ask for the welcome page... but now I can't. Probably this caching system needs at some point to be extended a bit to sotre also favicon images as soon as they won't be in base64 encoding anymore.
