### ISSUE TITLE
New kiwix-serve crash scenario with 'Xapian::DatabaseError'

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#146]
With most recent kiwix-serve nightly (from yesterday)
```
kiwix-serve --port=8080 --verbose stackoverflow.com_en_all_2017-10.zim
======================
Requesting : 
full_url  : /search
method    : GET (0)
version   : HTTP/1.1
headers   :
 - Accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
 - Accept-Encoding : 'gzip, deflate'
 - Accept-Language : 'fr,en-US;q=0.8,en;q=0.5,de;q=0.3'
 - Connection : 'keep-alive'
 - Cookie : '_ga=GA1.1.1481809055.1496164515'
 - DNT : '1'
 - Host : 'localhost:8080'
 - Upgrade-Insecure-Requests : '1'
 - User-Agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
arguments :
 - content : 'stackoverflow.com_en_all_2017-10'
 - pattern : 'emmanuel '
Parsed : 
url   : /search
acceptEncodingDeflate : 1
has_range : 0
.............
** running handle_search
Performing query `emmanuel '
terminate called after throwing an instance of 'Xapian::DatabaseError'
Aborted (core dumped)
```

See also core in attachment
  
[core.zip](https://github.com/kiwix/kiwix-tools/files/1600800/core.zip)

**Comment by mgautierfr** [comment]
I can reproduce the bug.

It seems that the embedded xapian database is not a valid database, `xapian` tries to read data after EOF.
At first glance, it seems that it is NOT a bug in `kiwix-lib`/`libzim` (reading) nor `xapian`.

It may be a bug in `zimwriterfs`/`libzim`(creating). I'm still investigating but it will be pretty difficult to reproduce without the input (stackoverflow) data (and even with the data, there is a LOT of data with a zim of 57Go)

**Comment by mgautierfr** [comment]
I've probably found the bug.
It "simply" seems that libzim cannot handle content bigger than 4Go. ALL variables used in libzim to store article size (in the public API or internally) are 32 bits size. So every (individual) content bigger than 4Go leads to a integer overflow and undefined behavior.

In our case, it seems that the xapian database of `stackoverflow.com_en_all_2017-10` is bigger than 4Go. Zimwriterfs "simply" do not write entirely the database in the zim file.

This can (and should) be fixed, but it is not a easy fix and needs a bit of time to be sure that we forgot nothing while changing the variables type.

For older content wrongly generated (as `stackoverflow.com_en_all_2017-10.zim`), there is nothing we can do except regenerate them once `libzim` is fixed. I recommend you to simply remove  `stackoverflow.com_en_all_2017-10.zim` for now.

**Comment by kelson42** [comment]
@mgautierfr Thank you very much for the analysis. I have moved the file to http://tmp.kiwix.org/stackoverflow.com_en_all_2017-10.zim. I close that ticket as there is nothing more here we can do.

**Comment by mgautierfr** [comment]
Please also remove it from `library*.xml`
