### ISSUE TITLE
Problem with byte range access in kiwix-serve

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#148]
By playing around with last nightly kiwix-serve, I have achieved to get this situation:
```
======================
Requesting : 
full_url  : /ted_en_business_2016-06/I/2515/video.webm
method    : GET (0)
version   : HTTP/1.1
headers   :
 - Accept-Encoding : 'gzip'
 - Connection : 'Keep-Alive'
 - Host : 'download.kiwix.org:8081'
 - Range : 'bytes=424391-'
 - User-Agent : 'Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-T700 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Safari/537.36'
 - allow-cross-domain-redirect : 'false'
arguments :
Parsed : 
url   : /ted_en_business_2016-06/I/2515/video.webm
acceptEncodingDeflate : 0
has_range : 0
.............
** running handle_content
Found /I/2515/video.webm
mimeType: video/webm
Response :
httpResponseCode : 200
headers :
 - Cache-Control: 'max-age=2723040, public'
 - Access-Control-Allow-Origin: '*'
 - Content-Type: 'video/webm'
 - Content-Length: '31219027'
 - Content-Range: 'bytes 0-31219026/31219027'
 - Accept-Ranges: 'bytes'
----------------------
```

The problem is that the client (was tested with my Android device) asks for bytes starting at offset `424391` but kiwix-serve returns (accordingly to the `Content-Length` HTTP header) `31219027` bytes, which happens to be also the overall size (according to the `Content-Range` HTTP header), ie. `31219027` bytes. The `Content-Length` should be 31219027 - 424391 bytes.

Here is the definition of the HTTP header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by kelson42** [comment]
We don't have achieve to come forward on this and I think we should reuse a parser which has already been done. See for example https://github.com/yhirose/cpp-httplib

**Comment by kelson42** [comment]
About the integration with libmicrohttpd https://lists.gnu.org/archive/html/libmicrohttpd/2020-03/msg00011.html

**Comment by rgaudin** [comment]
FYI, videos on apple browsers using kiwix-serve are not able to be played due to this.

It's not affecting most of our recent ZIMs because we use webm with is handled differently.
