### ISSUE TITLE
chrome 56 breaks js in kiwix-serve

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-tools#15]
This issue has been opened on the wrong https://github.com/kiwix/tools repository. (https://github.com/kiwix/tools/issues/1)
I report it here because this is where it should have be opened.
Please see already posted comments on the original issue.

> on access to even an old zim like ted_en_science_2015-02/ jquery fails to initialize with
jquery.js:9790 Uncaught SyntaxError: Invalid or unexpected token
this is the end of the file and there are two junk characters.
problem does not occur in latest FF or chrome 55 and earlier.
breaks search, and on ted science videos do not appear.

**Comment by needlestack** [comment]
Thanks - glad to see this fix! Is there an upcoming release that will include this, or are we best off trying to build from source?

**Comment by kelson42** [comment]
@needlestack try a nightly http://download.kiwix.org/nightly/2017-03-31/

**Comment by sqfield** [comment]
I have kiwix-serve installed on a Raspberry Pi as part of the Internet in a Box project.
The executable built for the Pi does not have the latest fix for the Chrome problem,
so I am trying to build it from sources.
I am encountering several problems:
1. It requires libzim, so I did
    apt-get install libzim-dev
   But that did not produce or provide a .pc file for pkg-config, so meson can't find the dependency.
   This is also true for another dependency, pugixml-dev.
2. I worked around this problem by first creating a .pc file, and when that didn't work, I simply changed
    the meson.build file to make the dependencies not required, so that a ninja.build file would be created.
3. When I do ninja install, I get dozens of compile errors:
(build)root@box.lan(AK.120):~/kiwix-lib/build # ninja install
[3/6] Compiling C++ object 'src/kiwix@sha/reader.cpp.o'.
FAILED: src/kiwix@sha/reader.cpp.o 
c++  -Isrc/kiwix@sha -Isrc -I../src -Iinclude -I../include -Istatic -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -fPIC -pthread -MMD -MQ 'src/kiwix@sha/reader.cpp.o' -MF 'src/kiwix@sha/reader.cpp.o.d' -o 'src/kiwix@sha/reader.cpp.o' -c ../src/reader.cpp
../src/reader.cpp: In member function ‘std::map<const std::basic_string<char>, unsigned int> kiwix::Reader::parseCounterMetadata() const’:
../src/reader.cpp:119:45: error: no matching function for call to ‘std::basic_stringstream<char>::basic_stringstream(zim::Blob)’
     stringstream ssContent(article.getData());
                                             ^
../src/reader.cpp:119:45: note: candidates are:
In file included from ../include/reader.h:30:0,
                 from ../src/reader.cpp:20:
/usr/include/c++/4.9/sstream:553:7: note: std::basic_stringstream<_CharT, _Traits, _Alloc>::basic_stringstream(const __string_type&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_stringstream<_CharT, _Traits, _Alloc>::__string_type = std::basic_string<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_stringstream(const __string_type& __str,
       ^
/usr/include/c++/4.9/sstream:553:7: note:   no known conversion for argument 1 from ‘zim::Blob’ to ‘const __string_type& {aka const std::basic_string<char>&}’
/usr/include/c++/4.9/sstream:537:7: note: std::basic_stringstream<_CharT, _Traits, _Alloc>::basic_stringstream(std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_stringstream(ios_base::openmode __m = ios_base::out | ios_base::in)
       ^
/usr/include/c++/4.9/sstream:537:7: note:   no known conversion for argument 1 from ‘zim::Blob’ to ‘std::ios_base::openmode {aka std::_Ios_Openmode}’
../src/reader.cpp: In member function ‘bool kiwix::Reader::hasFulltextIndex() const’:
../src/reader.cpp:593:29: error: ‘class zim::File’ has no member named ‘is_multiPart’
         && !zimFileHandler->is_multiPart() );
                             ^
../src/reader.cpp: In member function ‘bool kiwix::Reader::searchSuggestionsSmart(const string&, unsigned int)’:
../src/reader.cpp:696:36: error: ‘class zim::File’ has no member named ‘suggestions’
       = this->getZimFileHandler()->suggestions(prefix, 0, suggestionsCount);
                                    ^
../src/reader.cpp:698:25: error: ‘const class zim::Search’ has no member named ‘get_matches_estimated’
   if (suggestionSearch->get_matches_estimated()) {
                         ^
../src/reader.cpp:699:43: error: ‘const class zim::Search’ has no member named ‘begin’
     for (auto current = suggestionSearch->begin();
                                           ^
../src/reader.cpp:700:39: error: ‘const class zim::Search’ has no member named ‘end’
          current != suggestionSearch->end();
                                       ^
../src/reader.cpp: In member function ‘bool kiwix::Reader::hasFulltextIndex() const’:
../src/reader.cpp:594:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[4/6] Compiling C++ object 'src/kiwix@sha/searcher.cpp.o'.
FAILED: src/kiwix@sha/searcher.cpp.o 
c++  -Isrc/kiwix@sha -Isrc -I../src -Iinclude -I../include -Istatic -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -fPIC -pthread -MMD -MQ 'src/kiwix@sha/searcher.cpp.o' -MF 'src/kiwix@sha/searcher.cpp.o.d' -o 'src/kiwix@sha/searcher.cpp.o' -c ../src/searcher.cpp
../src/searcher.cpp:41:44: error: ‘zim::Search::iterator’ has not been declared
   _Result(Searcher* searcher, zim::Search::iterator& iterator);
                                            ^
../src/searcher.cpp:55:16: error: ‘iterator’ in ‘class zim::Search’ does not name a type
   zim::Search::iterator iterator;
                ^
../src/searcher.cpp:61:16: error: ‘iterator’ in ‘class zim::Search’ does not name a type
   zim::Search::iterator current_iterator;
                ^
../src/searcher.cpp: In member function ‘void kiwix::Searcher::search(std::string&, unsigned int, unsigned int, bool)’:
../src/searcher.cpp:165:49: error: no matching function for call to ‘zim::Search::Search(std::vector<const zim::File*>&)’
       zim::Search* search = new zim::Search(zims);
                                                 ^
../src/searcher.cpp:165:49: note: candidates are:
In file included from ../src/searcher.cpp:25:0:
/usr/local/include/zim/search.h:93:7: note: zim::Search::Search(const zim::File&, const zim::File&)
       Search(const File& articlefile_, const File& indexfile_)
       ^
/usr/local/include/zim/search.h:93:7: note:   candidate expects 2 arguments, 1 provided
/usr/local/include/zim/search.h:89:16: note: zim::Search::Search(const zim::File&)
       explicit Search(const File& zimfile)
                ^
/usr/local/include/zim/search.h:89:16: note:   no known conversion for argument 1 from ‘std::vector<const zim::File*>’ to ‘const zim::File&’
/usr/local/include/zim/search.h:86:7: note: zim::Search::Search()
       Search()
       ^
/usr/local/include/zim/search.h:86:7: note:   candidate expects 0 arguments, 1 provided
/usr/local/include/zim/search.h:58:9: note: zim::Search::Search(const zim::Search&)
   class Search
         ^
/usr/local/include/zim/search.h:58:9: note:   no known conversion for argument 1 from ‘std::vector<const zim::File*>’ to ‘const zim::Search&’
/usr/local/include/zim/search.h:58:9: note: zim::Search::Search(zim::Search&&)
/usr/local/include/zim/search.h:58:9: note:   no known conversion for argument 1 from ‘std::vector<const zim::File*>’ to ‘zim::Search&&’
../src/searcher.cpp:166:15: error: ‘class zim::Search’ has no member named ‘set_query’
       search->set_query(unaccentedSearch);
               ^
../src/searcher.cpp:167:15: error: ‘class zim::Search’ has no member named ‘set_range’
       search->set_range(resultStart, resultEnd);
               ^
../src/searcher.cpp:169:17: error: ‘struct kiwix::SearcherInternal’ has no member named ‘current_iterator’
       internal->current_iterator = internal->_search->begin();
                 ^
../src/searcher.cpp:169:55: error: ‘const class zim::Search’ has no member named ‘begin’
       internal->current_iterator = internal->_search->begin();
                                                       ^
../src/searcher.cpp:170:55: error: ‘const class zim::Search’ has no member named ‘get_matches_estimated’
       this->estimatedResultCount = internal->_search->get_matches_estimated();
                                                       ^
../src/searcher.cpp: In member function ‘void kiwix::Searcher::restart_search()’:
../src/searcher.cpp:182:15: error: ‘struct kiwix::SearcherInternal’ has no member named ‘current_iterator’
     internal->current_iterator = internal->_search->begin();
               ^
../src/searcher.cpp:182:53: error: ‘const class zim::Search’ has no member named ‘begin’
     internal->current_iterator = internal->_search->begin();
                                                     ^
../src/searcher.cpp: In member function ‘kiwix::Result* kiwix::Searcher::getNextResult()’:
../src/searcher.cpp:190:24: error: ‘struct kiwix::SearcherInternal’ has no member named ‘current_iterator’
   } else if (internal->current_iterator != internal->_search->end()) {
                        ^
../src/searcher.cpp:190:63: error: ‘const class zim::Search’ has no member named ‘end’
   } else if (internal->current_iterator != internal->_search->end()) {
                                                               ^
../src/searcher.cpp:191:50: error: ‘struct kiwix::SearcherInternal’ has no member named ‘current_iterator’
     Result* result = new _Result(this, internal->current_iterator);
                                                  ^
../src/searcher.cpp:192:15: error: ‘struct kiwix::SearcherInternal’ has no member named ‘current_iterator’
     internal->current_iterator++;
               ^
../src/searcher.cpp: In member function ‘void kiwix::Searcher::suggestions(std::string&, bool)’:
../src/searcher.cpp:229:47: error: no matching function for call to ‘zim::Search::Search(std::vector<const zim::File*>&)’
     zim::Search* search = new zim::Search(zims);
                                               ^
../src/searcher.cpp:229:47: note: candidates are:
In file included from ../src/searcher.cpp:25:0:
/usr/local/include/zim/search.h:93:7: note: zim::Search::Search(const zim::File&, const zim::File&)
       Search(const File& articlefile_, const File& indexfile_)
       ^
/usr/local/include/zim/search.h:93:7: note:   candidate expects 2 arguments, 1 provided
/usr/local/include/zim/search.h:89:16: note: zim::Search::Search(const zim::File&)
       explicit Search(const File& zimfile)
                ^
/usr/local/include/zim/search.h:89:16: note:   no known conversion for argument 1 from ‘std::vector<const zim::File*>’ to ‘const zim::File&’
/usr/local/include/zim/search.h:86:7: note: zim::Search::Search()
       Search()
       ^
/usr/local/include/zim/search.h:86:7: note:   candidate expects 0 arguments, 1 provided
/usr/local/include/zim/search.h:58:9: note: zim::Search::Search(const zim::Search&)
   class Search
         ^
/usr/local/include/zim/search.h:58:9: note:   no known conversion for argument 1 from ‘std::vector<const zim::File*>’ to ‘const zim::Search&’
/usr/local/include/zim/search.h:58:9: note: zim::Search::Search(zim::Search&&)
/usr/local/include/zim/search.h:58:9: note:   no known conversion for argument 1 from ‘std::vector<const zim::File*>’ to ‘zim::Search&&’
../src/searcher.cpp:230:13: error: ‘class zim::Search’ has no member named ‘set_query’
     search->set_query(unaccentedSearch);
             ^
../src/searcher.cpp:231:13: error: ‘class zim::Search’ has no member named ‘set_range’
     search->set_range(resultStart, resultEnd);
             ^
../src/searcher.cpp:232:13: error: ‘class zim::Search’ has no member named ‘set_suggestion_mode’
     search->set_suggestion_mode(true);
             ^
../src/searcher.cpp:234:15: error: ‘struct kiwix::SearcherInternal’ has no member named ‘current_iterator’
     internal->current_iterator = internal->_search->begin();
               ^
../src/searcher.cpp:234:53: error: ‘const class zim::Search’ has no member named ‘begin’
     internal->current_iterator = internal->_search->begin();
                                                     ^
../src/searcher.cpp:235:53: error: ‘const class zim::Search’ has no member named ‘get_matches_estimated’
     this->estimatedResultCount = internal->_search->get_matches_estimated();
                                                     ^
../src/searcher.cpp: At global scope:
../src/searcher.cpp:257:51: error: ‘zim::Search::iterator’ has not been declared
 _Result::_Result(Searcher* searcher, zim::Search::iterator& iterator)
                                                   ^
../src/searcher.cpp: In constructor ‘kiwix::_Result::_Result(kiwix::Searcher*, int&)’:
../src/searcher.cpp:258:27: error: class ‘kiwix::_Result’ does not have any field named ‘iterator’
     : searcher(searcher), iterator(iterator)
                           ^
../src/searcher.cpp: In member function ‘virtual std::string kiwix::_Result::get_url()’:
../src/searcher.cpp:264:18: error: missing template arguments before ‘.’ token
   return iterator.get_url();
                  ^
../src/searcher.cpp: In member function ‘virtual std::string kiwix::_Result::get_title()’:
../src/searcher.cpp:268:18: error: missing template arguments before ‘.’ token
   return iterator.get_title();
                  ^
../src/searcher.cpp: In member function ‘virtual int kiwix::_Result::get_score()’:
../src/searcher.cpp:272:18: error: missing template arguments before ‘.’ token
   return iterator.get_score();
                  ^
../src/searcher.cpp: In member function ‘virtual std::string kiwix::_Result::get_snippet()’:
../src/searcher.cpp:276:18: error: missing template arguments before ‘.’ token
   return iterator.get_snippet();
                  ^
../src/searcher.cpp: In member function ‘virtual std::string kiwix::_Result::get_content()’:
../src/searcher.cpp:280:15: error: missing template arguments before ‘->’ token
   if (iterator->good()) {
               ^
../src/searcher.cpp:281:20: error: missing template arguments before ‘->’ token
     return iterator->getData();
                    ^
../src/searcher.cpp: In member function ‘virtual int kiwix::_Result::get_size()’:
../src/searcher.cpp:287:18: error: missing template arguments before ‘.’ token
   return iterator.get_size();
                  ^
../src/searcher.cpp: In member function ‘virtual int kiwix::_Result::get_wordCount()’:
../src/searcher.cpp:291:18: error: missing template arguments before ‘.’ token
   return iterator.get_wordCount();
                  ^
../src/searcher.cpp: In member function ‘virtual int kiwix::_Result::get_readerIndex()’:
../src/searcher.cpp:295:18: error: missing template arguments before ‘.’ token
   return iterator.get_fileIndex();
                  ^
../src/searcher.cpp: In member function ‘std::string kiwix::Searcher::getHtml()’:
../src/searcher.cpp:376:30: error: ‘results_ct2’ is not a member of ‘RESOURCE’
   std::string template_ct2 = RESOURCE::results_ct2;
                              ^
../src/searcher.cpp: In member function ‘virtual std::string kiwix::_Result::get_url()’:
../src/searcher.cpp:265:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/searcher.cpp: In member function ‘virtual std::string kiwix::_Result::get_title()’:
../src/searcher.cpp:269:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/searcher.cpp: In member function ‘virtual int kiwix::_Result::get_score()’:
../src/searcher.cpp:273:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/searcher.cpp: In member function ‘virtual std::string kiwix::_Result::get_snippet()’:
../src/searcher.cpp:277:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/searcher.cpp: In member function ‘virtual int kiwix::_Result::get_size()’:
../src/searcher.cpp:288:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/searcher.cpp: In member function ‘virtual int kiwix::_Result::get_wordCount()’:
../src/searcher.cpp:292:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/searcher.cpp: In member function ‘virtual int kiwix::_Result::get_readerIndex()’:
../src/searcher.cpp:296:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ninja: build stopped: subcommand failed.


Has someone built a kiwix-serve program for the Raspberry Pi that works with Chrome?

**Comment by kelson42** [comment]
@sqfield Could you please open a new ticket for this new problem? So far I can see, you should use a git version of the libzim to get kiwix-serve work properly? We recommend to just download a pre compile nightly from http://download.kiwix.org/. A new release of kiwix-serve should be done soon now.
