### ISSUE TITLE
library.xml

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#154]
I don't see either the en or ar full medical wikis in the catalog

https://mirrors.dotsrc.org/kiwix/library/library_zim.xml

vs

http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2018-01.zim
http://download.kiwix.org/zim/wikipedia/wikipedia_ar_medicine_2018-01.zim

**Comment by kelson42** [comment]
@tim-moody Thx for the bug report, it should be fixed https://github.com/kiwix/tools/commit/b874bcb8946ca6ec5614b86726ed67bdee3b55ae
