### ISSUE TITLE
Search doesn't find all articles with hyphen

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#156]
_From @Klimmbimmel on February 19, 2018 20:57_

But kiwix doesn't behave predictable.

* FM-Synthese doesn't show up, even if you type "FM" (or more)
* La Ville-aux-Dames does show up as long as you didn't type the first letter or more after the first hyphen
*Jean-Michel <whatever last name> is found in all cases of search string. (Even 2 last names separated each by white space.) 

So maybe it has to do with the order of the white space and the hyphen?

I'm using LineageOS with kiwix, newest release on F-Droid, 2.2 build 47

_Copied from original issue: kiwix/kiwix-xulrunner#506_

**Comment by kelson42** [comment]
@Klimmbimmel Which ZIM/Content includes the arrticles you are talking about?

**Comment by Klimmbimmel** [comment]
I'm using Wikipedia in German,

wikipedia_de_all_nopic_2017-08.zim

I got this over the common way (don't ask me to be more specific :) :)

**Comment by kelson42** [comment]
@Klimmbimmel This is a known limitation with ZIM files without fulltext search indexes. Your file does not have one. The problem is fixed with file with full text indexes. You can for example test it with the Wikimed file in German here http://library.kiwix.org/wikipedia_de_medicine_2018-01/. Try for example to search "PHQ-D".
