### ISSUE TITLE
Improvement of the kiwix-serve toolbar labelling

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#160]
The navigation system within the display is unclear to the user. At the top of the screen, there is a navigation bar that displays

Library -- Home -- Random.

Library actually brings us back to the home page of the entire bundle. Home brings us back to the home of the offline resource (eg, Wikipedia offline). It would be way clearer to rename those buttons, with labels becoming

Home -- Wikipedia -- Random
or
Home -- WIktionary -- Random
or
Home -- Wikiquote -- Random

**Comment by kelson42** [comment]
@mgautierfr @Popolechien @rgaudin This is an idea for the WikiFundi project. What do you think about that move? We could put the ZIM title instead of "Home"?

**Comment by rgaudin** [comment]
👍 This bar always gets me confused.

What you propose makes sense. Which attribute of the ZIM would the _Wikipedia_ part be? The title? So it's the localized version usually, right?

**Comment by Popolechien** [comment]
I think "home" is more expected (also: size constraints / can be replaced by icon). The added value of "random" is doubtful imho.

**Comment by kelson42** [comment]
@rgaudin Yes, this would the ZIM title, so localised.

**Comment by kelson42** [comment]
@mgautierfr OK, we should have "Home" - [ZIM_TITLE] - "Random". Could you implement this please.
