### ISSUE TITLE
Haiti trip - looking for help getting Kiwix working on OLPC XO-1.5

### ISSUE THREAD

**Issue by avni** [kiwix/kiwix-tools#170]
I'm trying to get Kiwix working on OLPC XO-1.5 (fedora 18). Please see prior messages from thread below.

Per Matthieu's instructions, I git cloned the kiwix-lib repo and ran "meson kiwix-lib build". See attached screenshot. It made it further now, but complains with  "Native dependency 'libzim' not found"

This seems very similar to the issue here: https://github.com/kiwix/kiwix-lib/issues/49 though I can't figure out how this was resolved. 

I've also attached the terminal history from the last 2 days. 

Any pointers greatly appreciated. Thank you!

![skype_picture](https://user-images.githubusercontent.com/47825/37954186-f64fa644-3172-11e8-91b4-65f2510445b6.jpeg)

[20180326.txt](https://github.com/kiwix/kiwix-tools/files/1850995/20180326.txt)

---------

### Pasting prior messages from thread here:  ###

Date: Mon, 26 Mar 2018 10:01:50 +0200
From: Matthieu Gautier <mgautier@kymeria.fr>
To: offline-l@lists.wikimedia.org
Subject: Re: [Offline-l] Haiti trip - looking for help getting Kiwix
        working on OLPC XO-1.5
Message-ID: <123d91e3-c12f-883c-466e-94f995d1c107@kymeria.fr>
Content-Type: text/plain; charset=utf-8; format=flowed

Hi Avni,

Do you know https://github.com/kiwix/kiwix-build ?
It is the tool we used to compile all kiwix projects (and so kiwix-tools).
It download all sources, and compile everything from dependencies to
kiwix-tools.

Anyway, you can compile kiwix-tools without kiwix-build :

Meson need the sources of kiwix-tools to compile them. You will need to
clone them with `git clone https://github.com/kiwix/kiwix-lib`
Once they are cloned, you can use them. The command is `meson
<path_to_source_directory> <path_to_build_directory>`.
So if you already are in the source directory and want to build in the
subdirectory build, the command is `meson . build`

Once the build is configured (meson is the equivalent of ./configure),
you can compile it with `ninja` (being in the build_directory)

Cheers,
Matthieu Gautier.

---------
Hi - 

I am working on compiling kiwix-tools, and therefore kiwix-lib for the XO-1.5 (fedora 18), in preparation for the trip to Haiti in April. 

I am following the instructions here: https://github.com/kiwix/kiwix-tools and here: https://github.com/kiwix/kiwix-lib

With Jerry, Nathan, and Adam's help, I was able to install all dependencies for kiwix-lib (icu, zim, pugixml, ctpp2 [had to compile from source], xapian) and 
the environment compilation tools (automake, libtool, pkg-config). 

But I am having trouble with meson. Meson requires python 3.5+ so we installed python 3.6 from source (via https://danieleriksson.net/2017/02/08/how-to-install-latest-python-on-centos/). 

Meson (finally) was successfully installed that way, but now am running into the following error when running "meson . build" as instructed to do so here: https://github.com/kiwix/kiwix-lib. 

Error during basic setup: Neither directory contains a build file meson.build

Based on searching the web, it seems like this command requires the source existing thought it seems per here: https://github.com/kiwix/kiwix-tools/issues/158
that it may not be the preferred route anymore. The solution in that issue was to run this command: 

sudo -u kiwix /bin/bash -c "cd /opt/kiwix; /usr/lib/kiwix/bin/kiwix-manage /opt/kiwix/data/library/library.xml add /media/esata/MEDIA/System/Kiwix/data/content/wikipedia_en_for-schools_2013-01.zim"

Would appreciate any guidance on how to proceed. Many thanks.

**Comment by kelson42** [comment]
@avni Like the script says: "libzim" is not installed. kiwix-serve relies on many dependencies, and each of them should be installed. See https://github.com/kiwix/kiwix-lib/blob/master/README.md#dependencies

**Comment by holta** [comment]
@kelson42: is the GCC option `-mno-sse` recommended when building all kiwix & openzim tools here, as you outlined Nov 27th @ https://github.com/kiwix/kiwix-build/issues/94#issuecomment-347178452, but within the Meson/Ninja build system somehow?

Thanks much @kelson42 & @mgautierfr for all your help.

Next step appears to be libzim install instructions: https://github.com/openzim/libzim/blob/master/README.md

**Comment by avni** [comment]
I tried installing the zim packages that are available for fedora (zimlib-devel, Zim, etc) and that didn't install libzim. Thanks for finding this link, @holta: https://github.com/openzim/libzim/blob/master/README.md - Will try compiling from src.

**Comment by avni** [comment]
I tried compiling libzim from source.Please see image 1 for the output when building libzim. I believe it looks successful. 
IMAGE 1: ![img_5937](https://user-images.githubusercontent.com/47825/38160154-76f4acac-3486-11e8-9ad4-e663e203b379.jpg)

I then ran ninja to compile libzim.  I get 2 errors for which I cannot find solutions. Please see image 2. 
The errors are "'emplace' was not declared in this scope" and "error: 'runtime_error' is not a member of 'std'". Any help that can be provided would be greatly appreciated.

IMAGE 2: ![img_5936](https://user-images.githubusercontent.com/47825/38160161-a1ad3946-3486-11e8-8afa-9dc7c5e6a402.jpg)

**Comment by avni** [comment]
An FYI that xapian-core-devel is installed. I tried installing xapian-core from source (into /opt) per instructions here: https://xapian.org/docs/install.html and continue to encounter the same errors when running ninja. We leave for Haiti next Saturday so any guidance someone can provide to get this working would be greatly appreciated.

**Comment by mgautierfr** [comment]
@avni which version of fedora are you using ?
What is the output of `g++ -v` ?

**Comment by avni** [comment]
Hi @mgautierfr - 

Confirming the same OS and software as @holta  posted above: 

> @avni which version of fedora are you using ?

[olpc@xo-4a-a8-d7 ~]$ cat /etc/fedora-release
OLPC release 13 (based on Fedora 18)

[olpc@xo-4a-a8-d7 ~]$ uname -a
Linux xo-4a-a8-d7.localdomain 3.3.8_xo1.5-20140611.1154.olpc.355c89e
#1 PREEMPT Wed Jun 11 11:58:31 EST 2014 i686 i686 i386 GNU/Linux

> What is the output of g++ -v ?

[olpc@xo-4a-a8-d7 ~]$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/i686-redhat-linux/4.7.2/lto-wrapper
Target: i686-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man
--infodir=/usr/share/info
--with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap
--enable-shared --enable-threads=posix --enable-checking=release
--disable-build-with-cxx --disable-build-poststage1-with-cxx
--with-system-zlib --enable-__cxa_atexit
--disable-libunwind-exceptions --enable-gnu-unique-object
--enable-linker-build-id --with-linker-hash-style=gnu
--enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto
--enable-plugin --enable-initfini-array --enable-java-awt=gtk
--disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre
--enable-libgcj-multifile --enable-java-maintainer-mode
--with-ecj-jar=/usr/share/java/eclipse-ecj.jar
--disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic
--with-arch=i686 --build=i686-redhat-linux
Thread model: posix
gcc version 4.7.2 20121109 (Red Hat 4.7.2-8) (GCC)

**Comment by holta** [comment]
@jvonau suspects the errors in [IMAGE 2 screenshot above](https://github.com/kiwix/kiwix-tools/issues/170#issuecomment-377668843) are arising from:

> think there is a missing include for stdexcept for 'runtime_error is not a member of std'  and the emplace error I think is related to which arch version of unistd.h gets imported

**Comment by avni** [comment]
FYI for those following this issue, @mgautierfr has provided a new i586 build that we are testing. You can see results of the testing and a link to the build here: https://github.com/kiwix/kiwix-build/issues/94

**Comment by kelson42** [comment]
We got confirmation from @holta that i586 static binaries we distribute since yesterday work fine on the OLPC. So I close that ticket.

**Comment by holta** [comment]
Thanks again to all who helped!  Followup continues here:

https://github.com/kiwix/kiwix-build/issues/94#issuecomment-379979248
