### ISSUE TITLE
In French, the search can not treat properly the "d'"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#173]
What I do:
```
$ ./kiwix-search -s wikipedia_fr_all_novid_2018-03.zim "actium bataille"
$ 
```
So, no result. But IMO I should get the same result as with the following command:
```
./kiwix-search -s wikipedia_fr_all_novid_2018-03.zim "d'actium bataille"
Bataille d'Actium
```

**Comment by kelson42** [comment]
@mgautierfr The bug is still valid with the most recent libzim/libkiwix/kiwix-search

**Comment by mgautierfr** [comment]
In verbose mode we can see that :
- "actium bataille" will lead to a query `Sactium@1 AND (WILDCARD SYNONYM Sbataille OR Sbataill@2)`
- "d'actium bataille" will lead to `Sd'actium@1 AND (WILDCARD SYNONYM Sbataille OR Sbataill@2)`

It is probable that the title as been indexed the same way. So it is "normal" that the search without `d'` return nothing (there is no term `actium` in the title namespace).

The question is why xapian doesn't remove the `d'` and if we can do something about this.

**Comment by maneeshpm** [comment]
You are right @mgautierfr within the title index, the stored terms for "battaille d'actium" are as follows
```
0posanchor
Zbattaill // stemmed
Zd'actium // stemmed
battaille
d'actium
```
so even after stemming with `fr` language, the `d'` is not removed. 

This is actually an open ticket at Xapian tracked [here](https://trac.xapian.org/ticket/609). We can on libzim side introduce language-specific preprocessing in the indexer(and queryparser) for cases not handled by Xapian but I can see this getting complicated and tedious real sool. But if such cases are few or we can find some tool which does this, we can consider implementing this. Thoughts @kelson42?

**Comment by kelson42** [comment]
@maneeshpm OK, IMO the best thing to do is either to wait Xapian to fix the problem upstream... or to fix it ourself... in Xapian :)
