### ISSUE TITLE
kiwix-serve: Massive kernel-mode CPU usage when serving images when accessed via hostname with subdomain

### ISSUE THREAD

**Issue by OmegaPhil** [kiwix/kiwix-tools#179]
Hosting the extracted 'kiwix-0.9+wikipedia_en_all_novid_2017-08.zip' with the following URL locally, as an example:

http://lib.omeganet:8080/wikipedia_en_all_novid_2017-08/A/Dumont_d%27Urville_Station.html

[causes all 4 cores of the server to be maxed out with mostly kernel-mode CPU usage](https://imgur.com/a/oAj1YzW) - the browser waits for some time, loading images, and when they have all been fetched, the CPU usage dies.

No such problem when kiwix is accessed via:

http://lib:8080/wikipedia_en_all_novid_2017-08/A/Dumont_d%27Urville_Station.html

Both names resolve to the same host fine - but it looks like adding the domain on the end upsets kiwix-serve somehow.

Have seen the same behaviour from single file ZIMs, e.g. 'anime.stackexchange.com_en_all_2018-03.zim'.

Devuan Ascii
Browser used: Pale Moon 27.9, Firefox ESR 52.7.3
libzim: 3.2.0, bf82eae6518dda7c9d1b6b7d3810e1a41c7fb5ca, Mon Apr 9 11:01:42 2018 +0200
kiwix-lib: 1.1.0, 3849f0ae8b1287eec9f5ad90a2867d44bf739717, Thu Mar 29 17:49:10 2018 +0200
kiwix-tools: 0.4.0, c6ace1eafc06bbe52d596f0905e50dac47000a7a, Tue Mar 27 12:03:21 2018 +0200

All freshly built for this overall kiwix investigation (am now starting to use it for real).

**Comment by kelson42** [comment]
I will try to reproduce the problem.

**Comment by kelson42** [comment]
@OmegaPhil I can not reproduce the problem with a recent version, even if I do not have exactly the same version than you. What I recommend is to activate the --verbose mode on kiwix-serve to see if the requests are the same. But on my side, everything seems to work fine.

**Comment by OmegaPhil** [comment]
As requested on the channel, I have recreated the problem with the Wikipedia front page again, and have looked at the images listed as remaining to load in the browser. Fetching their URLs individually with curl results in no delay.

For reference I have attached a screenshot of the developer tools Network tab showing the very slow overall page loading. Interestingly some JavaScript files and one CSS file are either part of the problem or are affected by the lockup too.

![loading wikipedia front page with fully-qualified domain name developer tools network tab - 22 04 18](https://user-images.githubusercontent.com/395928/39095322-19dee3de-462e-11e8-9df0-c48c5d44e56c.png)

**Comment by OmegaPhil** [comment]
When fetching http://lib.omeganet:8080/wikipedia_en_all_novid_2017-08/I/m/Wikivoyage-Logo-v3-en.svg.png in Pale Moon after clearing cache etc, it takes 3ms.

**Comment by OmegaPhil** [comment]
On the channel I've been requested to redo the test with the original Wikipedia page:

![loading specific wikipedia page with fully-qualified domain name developer tools network tab - 22 04 18](https://user-images.githubusercontent.com/395928/39095647-6536d13e-4633-11e8-951d-760bd6268575.png)

Picking one image, Cntrl+F5 fetch of http://lib.omeganet:8080/wikipedia_en_all_novid_2017-08/I/m/Base_Dumont_d'Urville_-_Dumont_d'Urville_station.jpg on its own is 5ms

**Comment by kelson42** [comment]
@mgautierfr Would you have a theory to explain last chart?

**Comment by OmegaPhil** [comment]
Talk in the channel mentioned possibility of bad interaction with dependencies, so testing with statically-compiled kiwix-serve had no issues whatsoever - so this is some strange 'works but too old' dependency interaction, Devuan Ascii is based on Debian Stable so is very old.
