### ISSUE TITLE
kiwix-serve: Option to bind listening port to IP address

### ISSUE THREAD

**Issue by OmegaPhil** [kiwix/kiwix-tools#180]
Please can kiwix-serve have an option to bind the listening port to a specific IP address - this would help for machines with multiple interfaces (and is a last line of defence in the case of incomplete or broken firewall rules etc).

**Comment by kelson42** [comment]
@OmegaPhil Maybe not an IP, but a network interface, probably.

**Comment by kelson42** [comment]
@OmegaPhil I see that this option (to bind only to an interface) is already implemented. Is that not what you need?

**Comment by OmegaPhil** [comment]
Interface is also good, but an interface can have more than one IP address - but this isn't the case for me anyway. --interface is fine, thanks.

OK, looks like I should stop reading these manpages and just go off --help :)
