### ISSUE TITLE
kiwix-serve superuser search: 'xfce4 scrollback' returns hits, 'xfce4-terminal scrollback' doesnt

### ISSUE THREAD

**Issue by OmegaPhil** [kiwix/kiwix-tools#181]
'superuser.com_en_all_2018-01.zim' used, 'xfce4 scrollback' returns hits which include http://lib:8080/superuser.com//A/question/455927.html - this should also appear when searching on 'xfce4-terminal scrollback', but no hits at all are returned there.

Possible continuation of https://github.com/kiwix/kiwix-tools/issues/156

Devuan Ascii
Browser used: Pale Moon 27.9
libzim: 3.2.0, bf82eae6518dda7c9d1b6b7d3810e1a41c7fb5ca, Mon Apr 9 11:01:42 2018 +0200
kiwix-lib: 1.1.0, 3849f0ae8b1287eec9f5ad90a2867d44bf739717, Thu Mar 29 17:49:10 2018 +0200
kiwix-tools: 0.4.0, c6ace1e, Tue Mar 27 12:03:21 2018 +0200

**Comment by kelson42** [comment]
@mgautierfr I confirm the problem with http://library.kiwix.org/superuser.com_en_all_2018-01/

**Comment by kelson42** [comment]
I think this should be fixed in last libzim and kiwix-serve release. Needs to be confirmed.

**Comment by mgautierfr** [comment]
`xfce4` is a different word than `xfce-terminal`. It is "normal" that the results are different.

It is possible to add a synonyms dictionary (https://getting-started-with-xapian.readthedocs.io/en/latest/howtos/synonyms.html), but it would be difficult to generate it automatically. At best, the dictionnary should come from the wrapper with a content specific to the zim created.

**Comment by kelson42** [comment]
We need to make a new ZIM and check again, see https://farm.openzim.org/recipes/superuser.com_en

**Comment by kelson42** [comment]
Seems to work now http://library.kiwix.org/search?content=superuser.com_en_all_2020-04&pattern=xfce4-terminal+scrollback+
