### ISSUE TITLE
Kiwix-serve : problem with search when "&" char in zim name

### ISSUE THREAD

**Issue by dattaz** [kiwix/kiwix-tools#19]
When there is a "&" in the name of the zim, search will request to kiwix-serve with a url like this : http://127.0.0.1:8080/suggest?content=unix_&_linux_stack_exchange_en_all_2017-03&term=how 

the & of the name is interpret as a & for new argument of the request

Also in this case, kiwix-serve will answer to this request with the html of the page to choose which zim to load

**Comment by mgautierfr** [comment]
This probably have to been fixed in the `introduceTaskbar` function of kiwix-serve.cpp.
