### ISSUE TITLE
Implement ODPS download links

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#204]
A first version should be implemented based on the link given in the library.xml.

**Comment by mgautierfr** [comment]
This is already the case in http://library.kiwix.org/catalog/root.xml
There is a `<link rel="http://opds-spec.org/acquisition/open-access" type="application/x-zim" href="http://download.kiwix.org/[...].meta4" />` for each entry (the same than in http://mirror.download.kiwix.org/library/library_zim.xml)

**Comment by kelson42** [comment]
@mgautierfr super, merci.
