### ISSUE TITLE
kiwix-serve suggestions should use URLs instead of titles

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#205]
Currently, kiwix-serve suggestions is based on a json returned by kiwix-serve. In this JSON, each suggestions is couple label/title (which is the same!). Which means, that if someone click on a suggestion, the article is retrieved based on its title (in the ZIM title list) which is not really secure (you can have duplicates). kiwix-serve should return label/url to be sure we open then the right article.

**Comment by cm8** [comment]
confirmed.  Considered a somewhat major issue here, the suggest feature shows article page results, that when clicked trigger a xapian ft search (on embedded hardware this is noticeably slow).  Tested with [wikipedia_en_wp1-0.8_nopic_2018-05.zim](https://download.kiwix.org/zim/wikipedia/wikipedia_en_wp1-0.8_nopic_2018-05.zim) which seems to embed a ft index in the zim.  For scenarios in which xapian full text search is much too slow it would be nice if kiwix-serve had a command line option, as to explicitly turn off fulltext search capabilites all together.

In other words:  Having full-text search enabled on embedded hardware is an attack vector for denial of service (unintentional or not)  -   it may make sense to limit the maximum number of concurrent searches, use a timeout or schedule priority of the full text search threads..

Handling suggest search results that are an article could be handled client side, could it not?  It does not seem to be too bright to resend what is a search result to the server and start a full-text search using that.

I've tested kiwix-serve a couple of years ago - it may have used a different search engines, but spared such weiredness and worked as expected (tm) at that time.

I did not test with a dedicated index living in a directory, but assume similar results.

**Comment by kelson42** [comment]
@cm8 I do not think your comment really belong to that ticket. That said, you clearly report something wrong, but it is still unclear to me what. Can you please confirm you still have the problem with last kiwix-serve release and https://download.kiwix.org/zim/wikipedia/wikipedia_en_wp1-0.8_novid_2018-06.zim ? If "yes" please open a separate ticket.

**Comment by cm8** [comment]
@kelson42 In that case, can you please elaborate on what this ticket is about?  I'll give a description and a pic of the bug described above:

* on the box `./kiwix-serve --port 82 --verbose /var/media/ftp/uStor01/openzim/wikipedia_en_wp1-0.8
_nopic_2018-05.zim` is run
* in the client browser, the searchbar is used when visiting:
![screenshot_20180624_081746](https://user-images.githubusercontent.com/10984760/41817192-2c0f8592-7796-11e8-9f6e-88ca93356ebd.png)
* clicking on the link is expected to open the article directly, i.e.
  `http://fritz.box:82/wikipedia_en_wp1-0.8_nopic_2018-05/A/Kalahari_Desert.html`
  instead `http://fritz.box:82/search?content=wikipedia_en_wp1-0.8_nopic_2018-05&pattern=Kalahari+Desert` is requested
* tail of kiwix-serve log prints
```
[...]
** running handle_suggest
Searching suggestions for: "Kalaha"
Response :
httpResponseCode : 200
headers :
 - Cache-Control: 'max-age=2723040, public'
 - Access-Control-Allow-Origin: '*'
 - Content-Type: 'application/json; charset=utf-8'
 - Accept-Ranges: 'bytes'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
----------------------
======================
Requesting : 
full_url  : /search
method    : GET (0)
version   : HTTP/1.1
headers   :
 - Accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
 - Accept-Encoding : 'gzip, deflate'
 - Accept-Language : 'en-US,en;q=0.5'
 - Connection : 'keep-alive'
 - DNT : '1'
 - Host : 'fritz.box:82'
 - Referer : 'http://fritz.box:82/wikipedia_en_wp1-0.8_nopic_2018-05/A/Wikipedia%3A0.8_Index.html'
 - Upgrade-Insecure-Requests : '1'
 - User-Agent : 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0'
arguments :
 - content : 'wikipedia_en_wp1-0.8_nopic_2018-05'
 - pattern : 'Kalahari Desert'
Parsed : 
url   : /search
acceptEncodingDeflate : 1
has_range : 0
.............
** running handle_search
Performing query `Kalahari Desert'
}}}
```

As to not interfere with your issue title, please suggest good titles for both issues if you find that they indeed differ and I'll move the comment to a new issue.

**Comment by kelson42** [comment]
@cm8 I can not reproduce this pb with library.kiwix.org/wikipedia_en_wp1-0.8_nopic_2018-06/. I think this file has been impacted by https://github.com/openzim/zimwriterfs/issues/55. Sorry for the burden.

**Comment by cm8** [comment]
Ok, lets reference that as a duplicate of #197 then, no problem.  It'd be still nice to know what time range of zim files is affected, or if it can be detected by tools, compile a list, to help people decide what to download (some of the files are huge and knowing what files are broken beforehand may save lots of bandwidth..)

As for this issue - what where you originally intending?  It's tagged `enhancement`, I think the issue title is not too clear about what is to be enhanced and how.

**Comment by kelson42** [comment]
@cm8 yes, this is a bit of a mess currently, just trying within a few weeks to get ride of "broken" files. Most of them have already been superseed. I'll explain a bit the ticket to make it more clear.

**Comment by stardiviner** [comment]
My Emacs extension `kiwix.el` currently using this returned JSON to get available results. I hope to keep the title. So that available candidates is still can be retrived.
Here is my code:
https://github.com/stardiviner/kiwix.el/blob/master/kiwix.el#L254

**Comment by kelson42** [comment]
@stardiviner Sorry but we really have to fix that bug in next release. I guess you will have to adapt a bit your code after next kiwix-serve release.

**Comment by stardiviner** [comment]
Ok, I see, I will follow upstream changes. Thanks for notify me. @kelson42

**Comment by kelson42** [comment]
@MananJethwani is working on it
