### ISSUE TITLE
kiwix-serve flag --urlRootLocation=/URL_ROOT fails since 2018-06-10 (blocks http://box:3000)

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#208]
Running kiwix-serve with flag `--urlRootLocation=/kiwix/` did NOT cause the http://iiab.me:3000 error with every "nightly" build up-to-and-including Saturday June 9th.

Running kiwix-serve with flag `--urlRootLocation=/kiwix/` DOES cause the http://iiab.me:3000 error on every "nightly" build on-and-after Sunday June 10th.

Instead of showing the ZIM files, here is the error shown in the browser when visiting the non-proxied site http://iiab.me:3000 &mdash; that many still use for privacy, and also during server implementation and deployment:
```
Not Found

The requested URL "/" was not found on this server.
```

CONTEXT: --urlRootLocation=/kiwix/ (which worked up to and including June 9th) prepends string "/kiwix/" to URL's for proxy servers &mdash; e.g. for analytics when users visit http://iiab.me/kiwix/ which points to http://iiab.me:3000/kiwix/

CLARIF: here are 2 example versions of kiwix-serve (like all versions starting with June 10th) that cause the failure:
- Version 0.6.0 from 2018-08-20: http://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64-0.6.0.tar.gz
- Today's 2018-06-25 nightly build: http://download.kiwix.org/nightly/2018-06-25/kiwix-tools_linux-armhf-2018-06-25.tar.gz

**Comment by holta** [comment]
Clarif as requested by @kelson42 &mdash; the following kiwix-serve command will trigger the failure since June 10th:
```
kiwix-serve --port=3000 --urlRootLocation=/kiwix/ filename.zim
```
Aside: within Internet-in-a-Box (https://github.com/iiab) we currently use this longer call:
```
/opt/iiab/kiwix/bin/kiwix-serve --daemon --port 3000 --nolibrarybutton
 --library /library/zims/library.xml --urlRootLocation=/kiwix/
```

**Comment by kelson42** [comment]
@mgautierfr 

With:

```
kiwix-serve --urlRootLocation=/kiwix/ ...
``` 

With 0.5.0, "/" was displaying the kiwix-serve welcome page like "/kiwix/".
With 0.6.0, "/" displays a 404 but kiwix-serve welcome page "/kiwix/" works fine.

I'm not really sure what is the right behaviour... but this represents a regression for IIAB, which relies on "/"

**Comment by holta** [comment]
Clarif: this functionality worked from Nov 26, 2017 until Jun 9, 2018 (see https://github.com/kiwix/kiwix-tools/issues/96) including kiwix-tools 0.3.0, 0.4.0 and 0.5.0.

Thanks again to @mgautierfr.

**Comment by kelson42** [comment]
This behaviour has been introduced by https://github.com/kiwix/kiwix-tools/commit/efd4a1434eb498506a392902b682ab546834f586

**Comment by kelson42** [comment]
To me, all of this does not look like a bug but like a feature. `/` is not a valid request path if `--urlRootLocation=/kiwix/`. In the past we delivered the default homepage instead of a proper `404` page. We have discussed to fix that wrong behaviour within #144. I doubt this would be a good idea to re-introduce the previous behaviour.

**Comment by kelson42** [comment]
@holta provide a reversed proxy solution which does not log access.

**Comment by holta** [comment]
> @holta provide a reversed proxy solution which does not log access.

To secure legacy support for unlogged access to http://box:3000 does this mean we should use another port for kiwix-serve itself, e.g. `--port=3001 --urlRootLocation=/kiwix/` ?  (Any alternate port/s you recommend if so?)

**Comment by kelson42** [comment]
@holta no, kiwix-serve can only hear on the loopback interface and then you could create a reverse proxy on 3000 with nginx.

**Comment by mgautierfr** [comment]
> What would be the recommended/elegant way to support both:
>
>    unproxied access (http://iiab.me:3000 for those who want privacy, as they've always had on that clean/short URL)
>    proxied access (http://iiab.me/kiwix/ for schools/clinics that ask for analytics)

Having `kiwix-serve` being unaware of the proxy and having the proxy taking care of everything about proxyification (Rewrite request `http://iiab.me/kiwix/url` by removing `kiwix/` and rewrite http/css page to add `kiwix/` in the urls).
