### ISSUE TITLE
Feature Request - Home Button

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#209]
Add optional parameter to kiwix-serve with the relative URL of the web server home page to permit kiwix-serve to return the user to a top level menu.

**Comment by mgautierfr** [comment]
It is related to #17.

This is already possible to change the topbar without modifying kiwix-serve by provide your own html template and point to it with env var (Follow the links in #17). But this is really messy, an option should be better.

**Comment by kelson42** [comment]
@tim-moody I support #17 but I have mixed feelings regarding this particular feature request. Would not that be simplier to just have a rewrite rule - in the reverse proxy - to make the kiwix-serve "ḧome" points wherever you want?

**Comment by tim-moody** [comment]
maybe. are you saying I remove --nolibrarybutton from the startup and then trap the 'home' url in the proxy? what is the 'home' url? I'm proxying /kiwix/ to localhost:3000/kiwix/. Won't your suggestion mean also proxying /kiwix/ to /home/?

**Comment by kelson42** [comment]
@tim-moody yes, per default the home button points to "/". So if url == "/" then redirects to somewhere else.

**Comment by tim-moody** [comment]
but I have  --urlRootLocation=/kiwix/ so I'm guessing you will return /kiwix/ not /, which is already redirected to /home

**Comment by kelson42** [comment]
@tim-moody yes. Would that make it for you?

**Comment by kelson42** [comment]
@tim-moody The home button AFAIK return the value of --urlRootLocation if defined, / otherwise.

**Comment by tim-moody** [comment]
then it doesn't work. I need /kiwix/ to go to localhost:3000/kiwix/ and a home button to go to /

**Comment by kelson42** [comment]
@tim-moody If you really want an additional button, then  #17 is definitly THE ticket.

**Comment by kelson42** [comment]
I close this ticket because this is a use case for #17
