### ISSUE TITLE
Searching EN WP on RPi Zero W does not always return results

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#221]
[James Heilman](https://meta.wikimedia.org/wiki/User:Doc_James) reports via @tim-moody that Kiwix searches against the full EN WP[*] on a Raspberry Pi Zero W do not always return results, but return an error service unavailable.

[*] i.e. English Wikipedia ZIM files like 77GB http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_novid_2018-06.zim

I don't have more details, but this is an important observation/flaw on an extremely popular platform &mdash; no doubt exacerbated by the 512MB RAM memory limitation of the Raspberry Pi Zero W hardware?

**Comment by holta** [comment]
Question from the IIAB chat channel: "Given kiwix is using a precompiled binary this might come down to the difference between arm6 as used on raspbian and arm7 that I suspect was used to compile the binary"

**Comment by kelson42** [comment]
@mgautierfr has many an idea... but on my side, without a more detailed bug report, I fear that it will be complicated to deal with that probelm.

It would be helpful to know:
* Which search pattern exactly?
* After how many time you get the answer?
* Measurement of memory/cpu on the device during the request?
* If the behaviour is erratic or systematic for the same requests?

**Comment by WikiDocJames** [comment]
I am going to test to see if the problem is present on the raspberry pi 3 when I get home. Also going to try a version in which the SD card is less full. Will let you know.

**Comment by WikiDocJames** [comment]
Okay tried the 128 Gb microSD card on a Raspberry Pi 3 and it still has trouble searching. Often returns nothing. But than works we reloading a bunch of times.

**Comment by WikiDocJames** [comment]
By the way I occasionally get the search issue with the 32 Gb beta IIAB when looking at the 5.2 Gb full medical ZIM but it is much much less frequent.

**Comment by kelson42** [comment]
@WikiDocJames We need the details like asked earlier in my comment.

**Comment by WikiDocJames** [comment]
Sure so:

Which search pattern exactly?

   Occurs with basically all searches. 

After how many time you get the answer?

   May need to reload a dozen times before the page appears.

Measurement of memory/cpu on the device during the request?

   Happens on both the zero and the 3. Not sure how to measure the memory/cpu usage but will ask Tim.

If the behaviour is erratic or systematic for the same requests?

  It happens most of the time in the 77 Gb all en module.

**Comment by WikiDocJames** [comment]
Okay Tim and I have done some more testing. We looked at CPU and memory usage and neither one went over 20%. When we use ":3000" it worked better. Basically an error page occurred for a few seconds to up to half a minute and than the page in question loaded. When we do a search for something that does not exist we get nothing at all. On the smaller ZIM files we get "No results were found for XXXXXX"

**Comment by WikiDocJames** [comment]
We are wondering if something has timed out and is sending an error message to Apache.

**Comment by WikiDocJames** [comment]
The search terms I tried were "gout", "pneumonia", "HIV/AIDS", "Columbia Basin Trust", "urinary tract infection".

**Comment by tim-moody** [comment]
the longer the search term the more likely it failed

**Comment by tim-moody** [comment]
even without the apache proxy (directly on port 3000) the browser initially got a failure to connect error message, but then sometimes the results were displayed. is there a redirect done to the search results page that might have the wrong result code?

**Comment by tim-moody** [comment]
discovered that all of these tests are on an earlier version of kiwix-serve. we are retesting with 0.6 on rpi 3

**Comment by tim-moody** [comment]
upgrading to 0.6 seems to have solved these problems.

**Comment by holta** [comment]
Tangentially Related: a new kiwix-tools 0.6.1 or 0.7.0 appears to be imminent, after the version numbering snafu is resolved @ https://github.com/kiwix/kiwix-tools/issues/222
