### ISSUE TITLE
Kiwix-serve does not (always) print title properly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#223]
With https://download.kiwix.org/zim/stack_exchange/stackoverflow.com_eng_all_2018-08.zim, the title in the search bar print escaped `%26` characters.

**Comment by Bhavnaharitsa** [comment]
I want to work on this issue

**Comment by kelson42** [comment]
@Bhavnaharitsa OK, you probably need here to secure the HTML proper encoding before printing.

**Comment by Bhavnaharitsa** [comment]
Where can I find the file for the html page ?

**Comment by mgautierfr** [comment]
The content of the taskbar (I suppose it is what @kelson42 call search bar) is generated depending of the actual page displayed.

The template is here : https://github.com/kiwix/kiwix-tools/blob/master/static/server/taskbar.html.part
The template is used in the `introduceTaskbar` function here : https://github.com/kiwix/kiwix-tools/blob/master/src/server/kiwix-serve.cpp#L161

However, @kelson42 may speak about the titles displayed in the search suggestions (when you start to type a search term). If this is the case, you will have to look elsewhere : 
- The suggestion result is generated by the function `handle_suggest` (https://github.com/kiwix/kiwix-tools/blob/master/src/server/kiwix-serve.cpp#L449).
- Then it is the jquery autocomplete method (http://api.jqueryui.com/autocomplete/) that is used handle the completion of the field. The autocomplete is setup here by https://github.com/kiwix/kiwix-tools/blob/master/static/server/include.html.part.

This is also related to #205. You may want to also fix it while your working of the title displaying. (But please try to separate your submissions with separated PRs or, at least, separated commits)

**Comment by rgaudin** [comment]
Also affected by this. @kelson42's link not much useful and hardly visible on [online library](http://library.kiwix.org/stackoverflow.com_en_all_2019-02/A/index.html). Use inspector to reveal.

Character `&` is escaped to `%26`.

It seems to be a known issue given [this line](https://github.com/kiwix/kiwix-tools/blob/ef0fc514adb802252f4a779f3d4a825ee8c55e87/src/server/kiwix-serve.cpp#L188) but it didn't fix it. At least with **`2.1.0`**.

``` C
  content = replaceRegex(content, replaceRegex(zimTitle, "%26", "&"), "__ZIM_TITLE__");
```

**Comment by kelson42** [comment]
@rgaudin Yes, its an old problem which already have been tried to be fixed... I think this is in fact a bit more complex than what it looks like... but I don't remember why.
