### ISSUE TITLE
100% on rpi3 when url is not loading

### ISSUE THREAD

**Issue by godane** [kiwix/kiwix-tools#225]
I noticed a bug in my build of kiwix-tools where kiwix-serve will go 100% when it tries to load page when images are not loading. Even after exiting the tab the rpi3 will still be at 100%. I noticed that with kiwix-server in 2018-08-30 nightly build this doesn't happen. When a url fails to load (with nightly build) it will stop trying after after a few seconds. 

I'm doing this on a raspbian image that i updated. Here are some pastebin of libzim and kiwix-lib that some errors in the builds but still build the files:
libzim: https://pastebin.com/HsFCbsaT
kiwix-lib: https://pastebin.com/vR2m5Z6v

I think the errors are warnings more then errors but i figure i would at least post those. Kiwix-tools didn't have any errors like those so there is nothing to post.

PS:
I would like to know how the static nightly builds are made so i can see if i can build it the way you guys do to see if that fixes the problem also.  All i see with kiwix-build is android arm builds options in the readme.

**Comment by kelson42** [comment]
@godane Please try with most recent rele1sed static build from http://download.kiwix.org/release/kiwix-tools/. If it still fails, please share the filename and url of problematic article.

**Comment by godane** [comment]
i tried the kiwix-tools_linux-armhf-0.6.1-1.tar.gz static builds and still no problem. I think this is do to how i build my kiwix-tools so i need to know how you guys build it manual without a kiwix-build cause thats how i'm building. 

I also retried my old builds from 2018-08-30 and it would cause 50% cpu usage on just trying to load the home page of kiwix-serve. So i don't think this cause by a missing image not loading cause there is no missing images on that page that i know of.

**Comment by godane** [comment]
I recompiled my kiwix-tools with xapian-core 1.4.7 and i still get a core going 100%. So i think the static builds are build different then the way i do it or maybe with a different gcc set maybe.

**Comment by mgautierfr** [comment]
@godane, `kiwix-build` is here especially to avoid this kind of problem.
It is the reference and we are making our releases using it. I never compile `kiwix-*` projects directly, I always use `kiwix-build`, even when I'm developing.

You may try to compile yourself `kiwix-tools` using `kiwix-build` it would help to know if it is a problem in the way you're compiling `kiwix-tools` (configure options,...) or in your environment (gcc version, ...)

**Comment by kelson42** [comment]
@godane I'll close that ticket assuming it works properly using kiwix-build. If it does not then we probably have a real bug and please reopen the ticket. Otherwise we can assume that something went wrong somewhere specifically during your compilation on your computer or maybe you use an outdated dependence, etc...
