### ISSUE TITLE
kiwix-manage - "Unable to build or save library file '"

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#226]
on latest raspbian on rpi3 with kiwix-tools from Aug 30 I get

root@box:~# /opt/iiab/kiwix/bin/kiwix-manage /library/working/library.xml add /media/usb0/library/zims/content/wikipedia_en_all_2016-05.zim -i /media/usb0/library/zims/index/wikipedia_en_all_2016-05.zim.idx

Unable to build or save library file '/library/working/library.xml'

But others do not give this error, e.g.

/opt/iiab/kiwix/bin/kiwix-manage /library/working/library.xml add /media/usb0/library/zims/content/wikipedia_en_medicine_2016-07.zim -i /media/usb0/library/zims/index/wikipedia_en_medicine_2016-07.zim.idx

**Comment by tim-moody** [comment]
The ones that failed are:

skipping bouquineux_07_2013
skipping cest-pas-sorcier_fr_all_2015-07
skipping crashcourse_en_all_2015-09
skipping e-penser_fr_all_2016-06
skipping gutenberg_en_all_10_2014
skipping gutenberg_fr_all_10_2014
skipping la_chaine_de_maths_et_tiques_fr_all_2015-07
skipping oer4schools_en_all_2015-03
skipping oer4schools_en_all_2015-11
skipping ted_en_business_2016-06
skipping ted_en_design_2016-06
skipping ted_en_entertainment_2016-06
skipping ted_en_global_issues_2016-06
skipping ted_en_science_2016-06
skipping ted_en_technology_2016-06
skipping tedmed_en_all_2015-07
skipping tedmed_en_all_2016-07
skipping universcience-tv_fr_all_2015-03
skipping wikipedia_ar_all_2015-07
skipping wikipedia_ar_all_2016-08
skipping wikipedia_ar_all_novid_2017-07
skipping wikipedia_en_all_2015-05
skipping wikipedia_en_all_2016-05
skipping wikipedia_en_all_2016-12
skipping wikipedia_en_all_nopic_2015-05
skipping wikipedia_en_for_schools_opt_2013
skipping wikipedia_en_wp1-0.8_2016-08
skipping wikipedia_es_all_2017-01
skipping wikipedia_es_all_nopic_2015-09
skipping wikipedia_fr_all_2015-03
skipping wikipedia_fr_all_2016-12
skipping wikipedia_fr_all_nopic_2015-09
skipping wikipedia_pt_all_novid_2017-06
skipping wikipedia_zh_all_2017-01
skipping wikisource_en_all_2015-10
skipping wikisource_fr_all_2015-10
skipping wikistage_fr_all_2015-07

mostly old

**Comment by mgautierfr** [comment]
Seems related to the fact that zim file is split or not.
I cannot add split zim file to the library.
