### ISSUE TITLE
kiwix-manage remove fails because can not open zim to be removed

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#227]
if test.zim is item 1 in library.xml and test.zim is removed from the file system

kiwix-manage library.xml remove 1 issues the following

error 2 opening file "/library/zims/content/test.zim

is this expected and can it be ignored?

**Comment by mgautierfr** [comment]
I can confirm the issue.
There is no easy fix. `kiwix-manage` doesn't handle the library directly. It use `kiwix-lib` :
- Open the library.
- Manipulate the library (add, show, remove)
- Save back the library.

The main problem is that "Open the library" is the same code path than when we want to open the library to use it and serve the content. So we skip there invalid entry.
We should always add the book to the library and flag it as invalid. But in this case, other tools (`kiwix-serve` at least) should check the book is valid before using it.

I'm currently rewriting this part while working on `kiwix-desktop`'s content manager.
It will be fix there but not before mid October (#holiday :smile: )

**Comment by tim-moody** [comment]
After playing with this, I believe that the item will in fact be removed by kiwix-manage even if it issues this error message, so the issue is somewhat cosmetic. Interestingly, kiwix-manage show does not issue the error message and does not show the item, even though it is in the xml file.

**Comment by kelson42** [comment]
@tim-moody Thx for the bug report

**Comment by mgautierfr** [comment]
Book can be removed even if the zim file doesn't exists on the file system.
