### ISSUE TITLE
Add a "Powered by Kiwix"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#230]
at the bottom of kiwix-serve welcome page.

**Comment by Bhavnaharitsa** [comment]
I want to work on this issue

**Comment by kelson42** [comment]
@Bhavnaharitsa OK, see my feedback about your PR

**Comment by shrey183** [comment]
Is this issue resolved? If not, can I work on it?

**Comment by kelson42** [comment]
There is a PR ongoing already https://github.com/kiwix/kiwix-tools/pull/232
