### ISSUE TITLE
Add language/size selector to OPDS

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-tools#231]
There might already be a way to filter by language but I couldn't find it on the Wiki page.

**Comment by kelson42** [comment]
I have started a page here http://wiki.kiwix.org/wiki/OPDS. Filtering seems to make sense to me (for example to not list content which simply can not be installed on the device).

**Comment by kelson42** [comment]
@mgautierfr After your last merge, is the size filtering allowed?

**Comment by kelson42** [comment]
@jetownfeve21 Do you think this is something you could work on?
