### ISSUE TITLE
Feature Request: kiwix manage return meta data by zim file name

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#241]
kiwix-manage show returns meta data for items in a library file by bookid. However, bookid is part of the metadata and I would like a way to get it and other meta data when I only have a zim file name.

It would also be nice if this data were to be returned as json or xml so that I do not have to parse it, as is required for the show command.

Please let me know if there is already another way to do this.

**Comment by kelson42** [comment]
@tim-moody `zimdump -F example.zim  | grep uuid | cut -d' ' -f2`. I recommend to open a ticket to have "machine readable output" for `zimdump` if you really need that.

**Comment by tim-moody** [comment]
@kelson42 what repo has zimdump?

**Comment by kelson42** [comment]
https://github.com/openzim/zim-tools

**Comment by tim-moody** [comment]
@kelson42 OK found https://github.com/openzim/zim-tools/blob/master/src/zimDump.cpp

do I have to build it?

**Comment by kelson42** [comment]
@tim-moody You can but we provide binaries here https://download.openzim.org/release/zim-tools/

**Comment by tim-moody** [comment]
@kelson42 don't see arm binary. also not clear on difference between 1.0.0 and 0.0.1

**Comment by kelson42** [comment]
@tim-moody we provide only binary for linux64

**Comment by kelson42** [comment]
I close this ticket as this is the wrong place to require this enhancment.
