### ISSUE TITLE
How to index ZIM files

### ISSUE THREAD

**Issue by int19h** [kiwix/kiwix-tools#242]
I recall the earlier version of these tools (the one that was included with Kiwix 0.9 release on desktop platforms) included `kiwix-index`, but it appears to be missing now. Has this functionality been moved to a different tool?

**Comment by kelson42** [comment]
@int19h We do not provide any solution anymore to index ZIM files. Fulltext index are now part of the ZIM files themselves.

**Comment by int19h** [comment]
To clarify, does it mean that all new ZIM files downloaded from https://www.kiwix.org/ already have embedded indices? If so, what's the cut-off date?

**Comment by kelson42** [comment]
@int19h yes, most of them should and new one will. We have started seriously in June, and all of them since I think octobre are with ft index.

**Comment by int19h** [comment]
It might be helpful to publish this information somewhere (ideally on the [content page](http://wiki.kiwix.org/wiki/Content), marking specific files), given that there are different versions of tooling available for different platforms, and downloading an older wiki (e.g. 2016 version of Wikipedia, since it's the last one to have videos) to use with new tools might mean no index and no way to produce it.

**Comment by kelson42** [comment]
@int29h Agree, the wiki is a bit outdated and will be fixed.
