### ISSUE TITLE
kiwix-serve should reload automatically content (library/files)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#243]
If the files open (library/ZIM files) change, then kiwix-serve should automatically detect it and reload them (or load new files and stop providing removed files). All of this should happen without service interruption. The idea here is to allow to update the library without having here to restart the whole service and create a service interruption. The reload (and not restart) should ideally be smart and do modifications in the internal library only where this is necessary.

**Comment by kelson42** [comment]
Another appriach might be to send a signal to the kiwix-serve which woukd then do the library reload.

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan It seems we need more an more urgently this feature. We will launch a `dev.library.kiwix.org` which purpose seems to me quite obvious and for this purpose we would really benefit of an automatic refresh if a dev. ZIM file has been newly created.

Discussing this ticket with @rgaudin it seems that we should split it in two:
* Implement first a function to reparse the library XML file (if existing) and reparse ZIM files/paths to secure they don't have changed and reload without any service interruption (this ticket)
* Implement an optional feature which would monitor the loaded library XML/ZIM files to reload them if they change (would be easier to deal with for "normal" users. (new ticket created at #476)

So I propose to hook this reload function to the SIGUP (1) signal. This would make this feature POSIX only but does not sound to me to be a big problem.

@mgautierfr @veloman-yunkan Does that sounds right?

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan A quick feedback would be much appteciated as this is on the very top of my feature list.

**Comment by kelson42** [comment]
We should implement #482 first.

**Comment by kelson42** [comment]
@veloman-yunkan Now than #482 is kind of sorted out can you please implement this ticket?

**Comment by mgautierfr** [comment]
@kelson42 Are we agree that if the couple (path/uuid) about a zim file **in the xml** has not changed, we can assume the file don't have to be reloaded (and if in cache, we don't need to drop it from the cache)?
IE, we assume that we will never have a two different zim files with same uuid and the uuid in the xml is always the real uuid (same than in the zim file).

---

Other metadata may have changed and so we must update our internal library with the metadata in the xml (not reading them from zim file itself).
The basic behavior is to always trust the metadata in the library.xml. CMS may change the metadata to something different than in the zim file and we want to use the metadata in the xml.

**Comment by kelson42** [comment]
> @kelson42 Are we agree that if the couple (path/uuid) about a zim file **in the xml** has not changed, we can assume the file don't have to be reloaded (and if in cache, we don't need to drop it from the cache)?

Yes, I don't see any scenario why this could go wrong and this sounds importance for the overall performance of the reload.

**Comment by veloman-yunkan** [comment]
Though kiwix/libkiwix#636 provides bulk of the code for this enhancement, it will only be finalized when #497 is merged
