### ISSUE TITLE
kiwix serve error or faulty zim

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#244]
kiwix-serve[1020]: Invalid /library/zims/content/phet_en_2018-10.zim : Checksum position is not valid

**Comment by kelson42** [comment]
@tim-moody What are the reproduction steps? File seems OK:
```
$ zimdump -C phet_en_2018-10.zim
checksum ok
```

**Comment by tim-moody** [comment]
@kelson42 what I did was

```
kiwix_manage library.xml  add phet_en_2018-10.zim
kiwix-serve --daemon --port 3000 --nolibrarybutton --library /library/zims/library.xml --urlRootLocation=/kiwix/
```

this was with kiwix tools of Nov 12

**Comment by tim-moody** [comment]
to be clear, the error reported is by kiwix-serve

**Comment by kelson42** [comment]
@tim-moody I can not reproduce the pb. Your command is wrong `kiwix_manage` does not exist.

Here is my step-by-step simplified procedure:
```
$ rm -f library.xml ; kiwix-manage library.xml add /tmp/phet_en_2018-10.zim
$ kiwix-serve -p 8080 --library library.xml 
```
I get no error message at the start of kiwix-serve.

Tested with https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64-0.8.0-2.tar.gz

**Comment by tim-moody** [comment]
@kelson42 well I tried again and now I can't reproduce either, so close and I'll reopen if it occurs again. thanks.
