### ISSUE TITLE
does kiwix-serve still use external indices

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#245]
I run 

`/opt/iiab/kiwix/bin/kiwix-serve --daemon --port 3000 --nolibrarybutton --library /library/zims/library.xml --urlRootLocation=/kiwix/`

with library.xml containing

`<book id="ec599830-f577-9c6f-9066-6338540f4357" path="content/wikiversity_en_all_2017-03.zim" indexPath="index/wikiversity_en_all_2017-03.zim.idx" indexType="xapian" title="Wikiversity" name="kiwix.wikiversity_en_all" description="From Wikiversity" language="eng" creator="Wikiversity" publisher="Kiwix" `

and I get 

`kiwix-serve[5452]: Unable to open the search index '/library/zims/index/wikiversity_en_all_2017-03.zim.idx'.`

but the path exists

**Comment by tim-moody** [comment]
I believe this worked in earlier version of kiwix-serve

**Comment by kelson42** [comment]
@mgautierfr I'm not so sure about this backward compatibility stuff? Could you please help @tim-moody

**Comment by tim-moody** [comment]
@mgautierfr Is it true that all newly created zims have an internal internal index? If so, I think we can live with no support for an external index, but I just wanted clarification as to whether kiwix-serve still can use an external index or we need to remove all old zims.

**Comment by mgautierfr** [comment]
kiwix-serve can (should) still use external index. If not, this is a bug.

**Comment by mgautierfr** [comment]
This is due to the remove of the chert backend in the way we are compiling xapian (https://github.com/kiwix/kiwix-build/pull/202). External index uses it.

@kelson42 What do we need to do ? Re-add the chert backend support or assume this is deprecated (and stop support external index ?)

**Comment by kelson42** [comment]
@mgautierfr Stop supporting external indices
