### ISSUE TITLE
Binaries have rpath set

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-tools#250]
rpath is problematic for Debian, see

* https://lintian.debian.org/tags/binary-or-shlib-defines-rpath.html
* https://wiki.debian.org/RpathIssue

Disabling the rpath works fine and continues to function properly as far as I can tell...

This is the same as https://github.com/openzim/zimwriterfs/issues/72 - we should probably discuss this issue there, but I also wanted to flag it as problematic for this repository too.

**Comment by kelson42** [comment]
@mgautierfr Could you please give a feedbacl to @legoktm about that? @legoktm seems to be blocked in packaging of kiwix-tools (zimwriterfs?) because of this.
