### ISSUE TITLE
Can kiwix-tools provide official docker image?

### ISSUE THREAD

**Issue by stardiviner** [kiwix/kiwix-tools#257]
I searched hub.docker.com, found kiwix has some docker images, but don't have `kiwix-tools`. I hope kiwix-tools like `kiwix-serve` can be dockerized, because I want to use it as server for other purpose.

**Comment by kelson42** [comment]
@stardiviner what kind of env variables /volumes would you like to see in such an image? what would you your specific use case?

**Comment by stardiviner** [comment]
Like this docker image
https://hub.docker.com/r/jasiek/kiwix-server
https://hub.docker.com/r/jasiek/kiwix-server/dockerfile
It specify a path as volume for libraries. So that host system can access the docker container kiwix server.
I want to access the server from an Emacs extension https://github.com/stardiviner/kiwix.el.
If the kiwix serve updated to new version, I just need to pull down the image update.

**Comment by kelson42** [comment]
@stardiviner yes, would be a good start poing, have asked the permission to copy it https://github.com/jasiek/dockerized-kiwix-server/issues/2

**Comment by kelson42** [comment]
@stardiviner done

**Comment by stardiviner** [comment]
@kelson42 Thanks for quick working on this Dockerized kiwix-tools. :+1:
