### ISSUE TITLE
Unable to instantiate the HTTP daemon

### ISSUE THREAD

**Issue by evanfir** [kiwix/kiwix-tools#261]
I'm trying to run Kiwix server on Windows 10 with admin access but no matter what port I choose, I get the below error:

> Unable to instantiate the HTTP daemon. The port 8080 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024.

I would appreciate if you can help me fix this issue.

Thanks.

**Comment by kelson42** [comment]
@evanfir What happen if you try with port 9090 for example?

**Comment by evanfir** [comment]
I get the same exact error on two different computers.

**Comment by kelson42** [comment]
@evanfir Really not a Windows user, maybe a problem with a firewall? or maybe this works better with an admin user?

**Comment by kelson42** [comment]
@evanfir If all of this does not work please let me know about your exact command line kiwix-serve.exe call.

**Comment by evanfir** [comment]
I'm on a user admin and I run:

> kiwix-server.exe --port=8080 w.zim

**Comment by kelson42** [comment]
@evanfir @mgautierfr I confirm the bug. This error msg seems to appear since 0.7. Linux version is not impacted. We will do our best to handle that problem withing 2-3 weeks.

**Comment by evanfir** [comment]
Thanks for the info.

**Comment by kelson42** [comment]
@evanfir Work is currently going on to fix that issue. Thank you for your patience.

**Comment by kelson42** [comment]
@evanfir We believe to have fixed the problem. This is OK for us in the last nightlies https://download.kiwix.org/nightly/ and this will be part of the next release of kiwix-tools to be published in the next hours. Thank you very much for your report and patience.
