### ISSUE TITLE
Nighly kiwix-serve can not deal properly anymore with ZIM with absolute URLs

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#262]
This is mostly older and not compliant ZIM files, as newer should have relative path in URLs.

And example of such of file is available here:
http://tmp.kiwix.org/wikipedia.bm.absolute_urls.zim

We should keep that compatbility for a few years still IMO.

I discovered this by working on https://github.com/openzim/mwoffliner/issues/613. Basically

**Comment by mgautierfr** [comment]
My bad, I remove a bit too more code when implement correct redirection.
It's pity has we have to change the content and it is a performance penalty, but we don't really have the choice here.
