### ISSUE TITLE
Weird request on kiwix-serve

### ISSUE THREAD

**Issue by benmar** [kiwix/kiwix-tools#265]
Using kiwix-serve  from kiwix-tools 0.9 with wikipedia_en_simple_all_nopic_2018-06.zim works ok, but  weird requests with a 404 http response are set:

http://localhost/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki%7Cmediawiki.legacy.wikibits&only=scripts&skin=vector&version=18kdz1s

http://localhost:8080/w/load.php?debug=false&lang=en&modules=jquery.accessKeyLabel%2Cclient%7Cmediawiki.RegExp%2Cnotify%2Cutil&skin=vector&version=0c36xmm

They seem to came from  j/js_modules/site.js and j/js_modules/startup.js, but coudn't find that files on source code

**Comment by kelson42** [comment]
I move the ticket to mwoffliner, as this depends from the content.

**Comment by kelson42** [comment]
This issue was moved to openzim/mwoffliner#618
