### ISSUE TITLE
Create permanent redirects for library.kiwix.org content

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#269]
The idea is to have a hard link we can share at all times, no matter when the last zim file was created. For instance, for each ``novid`` entry entry have something along the lines of 
``http://library.kiwix.org/wikipedia_it_medicine_novid_2018-10/A/index.htm``<> ``http://library.kiwix.org/wikipedia_it_medicine/``
or 
``http://library.kiwix.org/wiktionary_fr_all_2018-07/A/Utilisateur:Stephane_(Kiwix)_Landing.html`` <> ``http://library.kiwix.org/wiktionary_fr`` 

Where the first links gets updated every so often but the second one always points to the last zim file generated (with the added bonus in the second example that it hides the strange URL).

This does not prevent from having other hard entries for ``mini`` and ``nopic`` selections, but the shortest/easiest to type should go to the better quality output, as we're more likely to use it to showcase our content.

**Comment by kelson42** [comment]
I came to the conclusion that the best approach to solve that was to have it in kiwix-serve itself:
* No redirect list to maintain
* No additional list (of redirect) to maintain
* Easy to implement
* Proper (as the HTML is OK) no redirect with at the end links with dates
* No additiona/external dependencies, like an additional reverse proxy

That said, this is a quite specific options, if we want to handle random aliases or other behavirous we will have to do that through a reverse proxy.

**Comment by kelson42** [comment]
@Popolechien My patch will more give a link like `http://library.kiwix.org/wikipedia_it_medicine_novid`, just the date will be removed, as this is the variable part.

**Comment by Popolechien** [comment]
Good enough. When do you think we can roll out (at least the medical part)?

**Comment by kelson42** [comment]
@mgautierfr We need to get my change reviewed and make a new release of kiwix-tools (a few weeks I guess)

**Comment by mgautierfr** [comment]
It is a bit more complex that it seems.
Serving a page with a different path than the one stored in the zim file will invalidate the links.
It will not be a problem with the change `wikipedia_it_medicine_novid_2018-10` -> `wikipedia_it_medicine` but it will if  we drop the `A/index.html` part.

**Comment by Popolechien** [comment]
ok, this gets longer and longer but fine: the idea is to have something we can share and forget about. What is the purpose of the ``A/`` segment?

**Comment by mgautierfr** [comment]
> What is the purpose of the A/ segment?

This is the namespace for Article. We want to remove it but it is a lot of work and we need to be sure that we don't break anything. See openzim/libzim#15

**Comment by mgautierfr** [comment]
@Popolechien You can already give the link `http://library.kiwix.org/wikipedia_it_medicine_novid_2018-10`. The browser will be automatically redirected to `http://library.kiwix.org/wikipedia_it_medicine_novid_2018-10/A/index.htm`.
The url of the article (`/A/index.htm`) will not be hidden (and it is hidden it that is tricky), but it will work.

**Comment by Popolechien** [comment]
Ah yes, but no: I really need the date stamp (2018_10 in that case) to go away. Would something along the lines of ``http://library.kiwix.org/wikipedia_it_medicine_novid*/A/index.htm`` work?

**Comment by mgautierfr** [comment]
For the timestamp, we need the PR of kelson to be merged (but we need to fix the issue about it first) See #270
