### ISSUE TITLE
kiwix-serve exits if declared index missing

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#28]
1. version: http://download.kiwix.org/nightly/2017-04-30/kiwix-tools_armhf_2017-04-30.tar.gz (download and untar)
2. use the hopefully attached test.zim file but any zim without internal index should work
3. create library.xml with
/opt/schoolserver/kiwix/bin/kiwix-manage /library/zims/library.xml add /library/zims/content/test.zim -i /library/zims/index/test.zim.idx (N.B. index does not exist)
4. run /opt/schoolserver/kiwix/bin/kiwix-serve --port 3000 --library /library/zims/library.xml
5. navigate browser to host:3000 and load test
6. search for XXXXXXXXXX
root@box:/opt/schoolserver/kiwix# /opt/schoolserver/kiwix/bin/kiwix-serve --port 3000 --library /library/zims/library.xml
terminate called after throwing an instance of 'Xapian::InvalidArgumentError'
Aborted

**Comment by tim-moody** [comment]
tried to upload test.zim, but github does not support that file type

**Comment by tim-moody** [comment]
[test.zip](https://github.com/kiwix/kiwix-tools/files/970700/test.zip)

**Comment by tim-moody** [comment]
the old behavior was to ignore this error. not sure if kiwix-manage ignored the index if missing or if kiwix-serve did, but kiwix-serve still made the zim available for reading.

**Comment by tim-moody** [comment]
kiwix-serve should display as before: 

There is no article with the title "XXXXXXXXXX" and the fulltext search engine is not available for this content.

**Comment by mgautierfr** [comment]
Agreed, whatever the previous behavior was. kiwix-serve should not terminate.

**Comment by kelson42** [comment]
@tim-moody does this problem still occurs with nightlies?

**Comment by tim-moody** [comment]
with 6-5-2017

on startup kiwix-serve reports the missing idx
on search it correctly reports that there is no title and full text search not available
