### ISSUE TITLE
[EPIC] Fix library rendition for small screens

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#285]
It looks like library.kiwix.org does not do a good job of rendering content on smaller phones, e.g. Nokia's bananaphone running KaiOS (see attached video). It would therefore be good to fix the general layout (smaller fonts, removal search and title bars, etc.) to better fit the available real estate.

[KaiOS demo on wikimed library.zip](https://github.com/kiwix/kiwix-tools/files/3110985/KaiOS.demo.on.wikimed.library.zip)

**Comment by kelson42** [comment]
@Popolechien Your ticket talks about many different aspects. We should split-up this Epic task. Could you open a separate ticket for the taskbar and one for the font? It would be also really helpful to be able to work on screenshots, could you make a few ones?

**Comment by ISNIT0** [comment]
@kelson42 @Popolechien  This is my idea to solve this issue:
![Frame 4 (5)](https://user-images.githubusercontent.com/5173131/57008102-a9163b00-6be5-11e9-9cd8-7f7d1a74ffa8.png)


NOTE:
- Changed the "back to library" icon to be books, not a home
- Changed the "home" button to say "home" and not the name of the ZIM file

On small screens (not sure what width exactly yet), hide the top bar and add a button to show the menu. The menu toggles up and down.

@kelson42 The font size editor will work by injecting some CSS:
```
* { font-size: 70%; }
```
This seems to work, though is far from perfect, perhaps this will be part of the JS api?

It would be possible to properly integrate the search on the small view (so when searching it takes up the whole grey box, but I think that would take quite a bit more effort)

**Comment by Popolechien** [comment]
I would remove the Library and Random items altogether to keep only Home (without the "home" word as most deployments / use cases will be for non-English speaking user) and Search.

The <s>problem</s> use case with KaiOS is that people are only meant to navigate one zim (they'll be sent directly to Wikimed) as Library would be the Life environment itself. Also generally speaking for someone unfamiliar with the content tree the difference between Home and Library is not that obvious.
We use library.kiwix.org to showcase what zims look like, so worst case scenario someone coming from the top level and willing to go back to the library can always hit the Back button.

**Comment by ISNIT0** [comment]
@Popolechien True, but this should probably be consistent with the desktop view?

The desktop version has a "home icon button" that goes to the library page, and a button with the name of the ZIM file which takes the user to the ZIM home page.

Should we remove the library button completely?

**Comment by Popolechien** [comment]
Yes. As I said Library normally is a demo site, it is unlikely that people would go through so many articles that users would feel it a drag to hit the back button to go back to the library.

**Comment by ISNIT0** [comment]
Okay, cool :)

**Comment by ISNIT0** [comment]
Something more like this then?
![Frame 4 (6)](https://user-images.githubusercontent.com/5173131/57009221-4e80dd00-6bed-11e9-8e89-1e2ab91d0ab1.png)

**Comment by kelson42** [comment]
@kelson42 @Popolechien The problem you want to fix is a rendering one (on small screens). I don't want to change the logic/labelling/icons of the button within that ticket. Please focus on what is the problem and provide a solution only to that problem.

**Comment by Popolechien** [comment]
@ISNIT0 Forget about my previous comments regarding icon removal - I was focused on library.kiwix.org rendition but forgot this is kiwix-tools and also impacts the hotspot (and not just some random tourist on the web). `` { font-size: 70%; }`` seems to work here so let's take it. I'll open a separate ticket for the taskbar.

**Comment by kelson42** [comment]
@Popolechien Something we really need to know for these kind of problem is:
* Resolution of the screen
* Pixel-depth of the screen
