### ISSUE TITLE
Include human readable IDs in OPDS feed

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-tools#291]
At the moment, the OPDS feed contains for each entry a single, unique, ID in the form of an uuid.
In addition to this ID, are non-unique strings like Title and Description

``` xml
<entry>
    <title>Encyclopédie médicale WikiMed</title>
    <id>urn:uuid:0a4c779c-1c17-51be-b1ea-bd4ffaed9a7c</id>
    <icon>/meta?name=favicon&amp;content=wikipedia_fr_medicine_novid_2018-10</icon>
    <updated>2018-10-10T00:00::00:Z</updated>
    <summary>L'Encyclopédie médicale de Wikipédia</summary>
    <link type="text/html" href="/wikipedia_fr_medicine_novid_2018-10" />
    <author>
      <name>Wikipedia</name>
    </author>
    <link rel="http://opds-spec.org/acquisition/open-access" type="application/x-zim" href="http://download.kiwix.org/zim/wikipedia/wikipedia_fr_medicine_novid_2018-10.zim.meta4" length="288866304" />
    <link rel="http://opds-spec.org/image/thumbnail" type="image/png" href="/meta?name=favicon&amp;content=wikipedia_fr_medicine_novid_2018-10" />
  </entry>
```

As you can see in this sample, the former ID that we used (`wikipedia_fr_medicine_novid`) is not offered although it is visible inside the link or filename.

I suggest we consider adding this human ID for two reasons:

1. It's not an obsolete ID. We use it in the zimfarm for instance and need it internally to refer to ZIMs and we build filenames off it.
2. In console applications (hotspot-installer in my mind), it is move convenient to pass a meaningful `wikipedia_fr_medicine_novid` argument than a `0a4c779c-1c17-51be-b1ea-bd4ffaed9a7c` one.
3. Exchange formats like the hotspot-installer JSON presets were designed to be human-readable. Without this human ID, it's not human-readable anymore.
We could bundle the title inside the exports as well for better comprehension but it's localized, doesn't include variants info and is error prone.

Let me know what you think.

**Comment by kelson42** [comment]
@mgautierfr We really now to think about how to deliver via OPDS the information to allow  Kiwix library implementations to deal with variants (same content, but nopic, novid, ...). I believe this discussion might solve this problem too. We should talk about that in two weeks.

**Comment by mgautierfr** [comment]
"HumanReadableId" is not really a Id, it is based on the filename and we explicitly said that `kiwix-*` should not assume any meaning for the filename. The "humanid" provided is in fact the file name of the zim file on the fs. It works well for local instance of a kiwix-serve, serving zim the user already have.

> Without this human ID, it's not human-readable anymore.

This is a bit excessive as an argument (and not really receivable)

> We could bundle the title inside the exports as well for better comprehension but it's localized, doesn't include variants info and is error prone.

I don't see how the "humanReadableId" would be less error prone that the title.

> @mgautierfr We really now to think about how to deliver via OPDS the information to allow Kiwix library implementations to deal with variants (same content, but nopic, novid, ...). I believe this discussion might solve this problem too. We should talk about that in two weeks.

I don't see how. https://github.com/kiwix/kiwix-lib/issues/131 and https://github.com/kiwix/kiwix-tools/issues/252 are better options.

----

Despite I am not sure about a human readable id (as it is defined now) in opds feed, I agree we miss a **unique** id across all our tools (and our storage backend, fs included). The uuid is a unique id but I agree it lacks of semantics and having zim files named "0a4c779c-1c17-51be-b1ea-bd4ffaed9a7c.zim"  or url like "http://library.kiwix.org/0a4c779c-1c17-51be-b1ea-bd4ffaed9a7c/index.html" is pretty difficult for human. However, if we want some consistency, it is what we should do. (And it is what is done behind the scene in kiwix-desktop).

But for now, we cannot do really much. The file name is generated by mwoffliner to something somehow unique based on the tags and the date. But despite it is unique (because fs need it), it is not a id at all. Because (and not only) the tags are not standardized (see https://github.com/kiwix/kiwix-lib/issues/131)

We should really address this identifier issue once for all, all together, and not go ahead and build our tools on identifiers (on the large sense, as unique identifier or as "things" that allow tools identify a set of zim among others) that are not real ones. It will not solve the problem, it will simply force us to solve a more complex problem later.

**Comment by kelson42** [comment]
I see some kind of relationship to that ticket https://github.com/kiwix/apple/issues/15

**Comment by kelson42** [comment]
@rgaudin I'm not really sure which problem you try to fix, that does not help.

IMO what users should see is the title/description/publisher/tags/date/etc. If you have a use case where this does not deliver the correct information to the users then I'm interested in.

Then you have the technical question of identifying content, and then I think the core is the `name` of the ZIM, associated with tags/uuid/etc.. depending about what you want to do. See https://wiki.openzim.org/wiki/Metadata.

**Comment by rgaudin** [comment]
> @rgaudin I'm not really sure which problem you try to fix, that does not help.
> IMO what users should see is the title/description/publisher/tags/date/etc. If you have a use case where this does not deliver the correct information to the users then I'm interested in.

it's all in the initial comment. Let me re-explain the use cases. I can think of 2.

### hotspot cli

when using the hotspot cli, user have to provide the list of ZIM files he wants to include. ATM, it looks like: `kiwix-hotspot cli --zim-install wikipedia_fr_all_nopic.fr`

Without this human ID, it would look like `kiwix-hotspot cli --zim-install 5957c127-ca1d-76c2-93c5-3b48b6bfc4d9`.

* requires additional steps to find out the UUID
* more error prone (can't easily spot a typo)

So for this cli tool, it's inconvenient but it's not dramatic: users will find the UUID from `--help` maybe and we already have a confirm feedback delay after the command is launched.

### hotspot and cardshop exports

When we introduced the JSON export feature to the hotspot, it was important that the export is human readable/writable. Currently, it looks like:

``` json
{
    "name": "WikiFundi Schools",
    "content": {
        "zims": [
            "vikidia_fr_all.fr"
        ],
    }
}
```

Without a human ID, it would look like 

``` json
{
    "name": "WikiFundi Schools",
    "content": {
        "zims": [
            "0a4c779c-1c17-51be-b1ea-bd4ffaed9a7",
            "5957c127-ca1d-76c2-93c5-3b48b6bfc4d9"
        ],
    }
}
```

It would this be a lot less human maintainable. 

But the **biggest concern** is that current UUIDs are IDs for a particular ZIM file (ie. dated version). 
It means that we won't be able to have export files referencing “*the latest Wikipedia in French NoPic*” anymore. 

---

so there are multiple questions behind this:

* **do we want multiple IDs per ZIM?** I'd say no. Two IDs means one of them is bad.
* **do we want human IDs for ZIM?** I'd say no. For uniqueness sake, UUIDs are good.
* **do we want a sort-of category allowing to nail-down a particular ZIM without browsing a long list or knowing its ID?** Maybe.

It doesn't have to be an extra field. ATM a ZIM is _identified_ (by us) from:

1. `category` (`wikipedia`, `phet`, `other`)
1. `language` (`fr`, `en`, `fa`)
1. `selection` (`movies`, `all`)
1. `format` (`mini`, `nopic`)
1. `date` (`2019-06`, `2019-05`, `latest`).

If we could have a **permalink** to a request on those fields, a human could pin down a ZIM without browsing much nor knowing the ID.

**maybe this is a feature-request for the OPDS search engine?**

I'd be happy with requests like:

* http://library.kiwix.org/catalog/search?category=wikipedia&lang=en&selection=movies&format=mini&date=latest
http://library.kiwix.org/catalog/search?category=wikipedia&lang=bam

**Comment by kelson42** [comment]
@rgaudin @mgautierfr I propose to introduce a "Flavour" metadata. With other metadata, it should allow to do everything needed IMO. Here would be the change on the spec: https://wiki.openzim.org/w/index.php?title=Metadata&type=revision&diff=31118&oldid=31116. Let me know if this is OK for both of you.

**Comment by rgaudin** [comment]
Took me a minute but yes, it solves my issue.

**Comment by mgautierfr** [comment]
> I'd be happy with requests like:
    http://library.kiwix.org/catalog/search?category=wikipedia&lang=en&selection=movies&format=mini&date=latest
    http://library.kiwix.org/catalog/search?category=wikipedia&lang=bam

All the "category", "selection", "format", .. are in tags. And as they are free tags this is pretty difficult to implement correctly in all our project.
For example, for your first request, is it pretty difficult to search for zim file containing the tags wikipedia and nodet but not the tag novid.
Your second request can be already made with library.kiwix.org/catalog/search?tag=wikipedia&lang=bam

> I propose to introduce a "Flavour" metadata in the ZIM file. With other metadata, it should allow to do everything needed IMO. Here would be the change on the spec: https://wiki.openzim.org/w/index.php?title=Metadata&type=revision&diff=31118&oldid=31116.

Well... maybe. We have to think about this. How it is compete with the free tags in the tag list ?
Would it means the we can search on the "flavor" metadata ? If we enforce that the flavor is consistent we the tag, could we generate it and not store it ?

**Comment by kelson42** [comment]
@mgautierfr You can see the "flavour" as a "name" metadata extension. It has to be different from the name to allow to do interesting things like group easily multiple ZIM sharing the same name, but not only. This allows also to share bookmarks between different ZIM file flavours. etc.

**Comment by kelson42** [comment]
The main problem here is that "Name" and "Flavour" metadata have to be properly written in ZIM files.
