### ISSUE TITLE
Wikipedia Article name appears twice only on KaiOS devices

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#293]
When checking out Wikimed on a KaiOS feature phone (2.8") I get the following:
![3](https://user-images.githubusercontent.com/21675885/58342714-6e549b00-7e51-11e9-8f27-9a2ce171cf11.jpg)
And not on a smartphone (android, 6")
![4](https://user-images.githubusercontent.com/21675885/58342850-dc995d80-7e51-11e9-9b6d-061d4b3e063d.jpg)
Any idea why?

**Comment by kelson42** [comment]
@Popolechien There is basically nothing we can really do about that IMO. First one is the browser (we don't really control it) and the second one is in the HTML. We could remove it in the ZIM but then they would not be displayed anywhere else. I don't see any proper solution to that problem so far.

**Comment by kelson42** [comment]
What is the user-agent here? If this is a specific one, we might do a special rule in the ZIM or kiwix-serve stylesheet.

**Comment by kelson42** [comment]
@Popolechien I propose to close that ticket for now. The only way to make it disappearing would be (if possible at all) to make a special rule for KaiOS (I don't like this at all). Let me know what you think.

**Comment by Popolechien** [comment]
Well I understand your problem but as far as UX goes font size clearly is an issue if the title takes up half a screen.

**Comment by kelson42** [comment]
It seems the Browser has a specific `user-agent`
![1562770726812](https://user-images.githubusercontent.com/1029718/60980127-2cfe4900-a334-11e9-8e7b-bafbe5c8e57e.JPEG)

**Comment by kelson42** [comment]
@ISNIT0 What do we do with that? The best solution I see is written Mediawiki ZIM files (with MWoffliner) which do something like [this](https://codepen.io/samiah/pen/NgQKMb) with a css removing (making invisible) the following DOM node but only if usage-argent =~ KaiOS
```
<h1 class="section-heading in-block collapsible-heading open-block" tabindex="0" aria-haspopup="true" aria-controls="content-collapsible-block-0" data-section-id="0">
  <div class="mw-ui-icon mw-ui-icon-arrow mw-ui-icon-element  indicator" title=""></div>
  <span class="mw-headline" id="title_0">Ignorance</span>
</h1>
```

**Comment by ISNIT0** [comment]
Hmmm, seems a bit weird for KaiOS to be part of the MWOffliner code

**Comment by kelson42** [comment]
@ISNIT0 Yes it is... and this is even weirder on kiwix-serve level. But this is one CSS rule and this can be properly explained what is going on here. This is seems to me the less worse solution.
