### ISSUE TITLE
Improve kiwix-serve toolbar layout

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#294]
Currently the toolbar layout on Kiwix-serve is not convenient for users on very small screens (see also #285). There are currently five fields on the top bar: Home (brings the user back to the full zim library)/ File name (which is another form of "Home", but to the zim files' start page) / random / search field / search button
The below improvement has been suggested:
![285](https://user-images.githubusercontent.com/21675885/58341674-0dc45e80-7e4f-11e9-84a4-a017f34edb68.png)
This proposal in #285 is pretty neat, with two caveats:
- Can we do without the text? If it is to be used in non-english languages, it would be more efficient to proceed with icons only (and save space);
- in the case of KaiOS users being online and accessing directly a specific zim file, we might not want to allow them to access the full library. Is it possible to hide the Home/Library button when accessing a specific zim file (e.g. we produce kaiOS-tagged zims, and kiwix-tools would be able to parse this and know that the Library button need not appear?

**Comment by kelson42** [comment]
@Popolechien This is a duplicat of #285. Please put your proposal/comment as a comment. Don't open a new "front" here.

**Comment by kelson42** [comment]
I have reopen that one because:
* It is more focused
* We start on the base.

But I'll close #285

**Comment by kelson42** [comment]
@ISNIT0 @Popolechien I would propose to:
* Keep a bar on the top, but make that bar disappearing automatically if not used (many example of this kind of bar exist)
* Search input box should be always visible immediately in the top bar
* All the rest is available is the drop-down which has been proposed (drop down arrow is alway available in the top bar right side)
* We don't change (for now) any labelling, iconing.

**Comment by kelson42** [comment]
>     * Can we do without the text? If it is to be used in non-english languages, it would be more efficient to proceed with icons only (and save space);

Yes, this one reason why I propose to not change anything in labelling/iconing.

>     * in the case of KaiOS users being online and accessing directly a specific zim file, we might not want to allow them to access the full library. Is it possible to hide the Home/Library button when accessing a specific zim file (e.g. we produce kaiOS-tagged zims, and kiwix-tools would be able to parse this and know that the Library button need not appear?

This kind of requirement is contradictory with the purpose of library.kiwix.org. If this is important, we need to run this somewhere else. Otherwise this will be a mess, we can not run two rabbits going in different direction at the same time with one service.

**Comment by ISNIT0** [comment]
- [ ] add ellipsis to Zim Title button

**Comment by ISNIT0** [comment]
Thoughts on this progress of the button toggling?

![Kapture 2019-06-17 at 13 44 58-min](https://user-images.githubusercontent.com/5173131/59605368-893fc580-9106-11e9-8ede-bb25fa4ca02e.gif)

The arrow is on the left, not the right as @kelson42 requested.
It seemed odd to move the arrow to the right, as the buttons are on the left by default. That said, it's super easy to switch it over if you think it matters :)

**Comment by ISNIT0** [comment]
Disappearing header:
This applies to screens under 520px wide (this number is already used in the css for media queries)

![Kapture 2019-06-17 at 14 12 20-min](https://user-images.githubusercontent.com/5173131/59606892-1fc1b600-910a-11e9-9964-c07d7c162835.gif)

**Comment by kelson42** [comment]
@ISNIT0 Can you please put a demo HTML stuff somewhere online please, so we can test ourself?

**Comment by ISNIT0** [comment]
It's probably easiest to run the PR locally: #300

**Comment by Popolechien** [comment]
Looks pretty good to me.
