### ISSUE TITLE
kiwix-serve URL paths should be specified as relative rather than absolute

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#31]
_From @abudden on January 12, 2017 13:0_

If kiwix is installed behind a proxy (e.g. nginx) with a non-root path, none of the links or stylesheets work as every URL is specified as absolute (e.g. `/skin/jquery-ui/external/jquery/jquery.js`).  Therefore if you have nginx configured to serve kiwix at /kiwix, the links resolve to `/skin/...` instead of `/kiwix/skin/...` and nothing works.

_Copied from original issue: kiwix/kiwix#436_

**Comment by kelson42** [comment]
_From @tim-moody on January 19, 2017 13:48_

I  have also had this problem.  There is a more laborious workaround where you proxy each zim:

location /wiktionary_en_simple_all_2016-05 {
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:3000/wiktionary_en_simple_all_2016-05/;
        }

same principal works in apache

**Comment by swiftugandan** [comment]
Pull request  #80 adds this functionality, please test it

**Comment by swiftugandan** [comment]
this is fixed in #86
