### ISSUE TITLE
kiwix-serve --nolibrarybutton doesn't work (likely a regression in kiwix-tools 2.1.0)

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#313]
I mentioned this to @kelson42 who agrees the non-functioning `kiwix-serve --nolibrarybutton` is likely a regression in kiwix-tools 2.1.0

What happens is that the square "home" button appears in the top-left of the page (it should not!) when viewing any ZIM file in your browser, even despite the `--nolibrarybutton` flag.

Whereas this square "home" button does not appear (correctly!) when trying the exact same thing with kiwix-tools 2.0.0

Context to reproduce this / Internet-in-a-Box runs the following [command](https://github.com/iiab/iiab/blob/master/roles/kiwix/templates/kiwix-serve.service.j2#L7):
```
/opt/iiab/kiwix/bin/kiwix-serve --daemon --port 3000 --nolibrarybutton --library /library/zims/library.xml --urlRootLocation=/kiwix/
```
On OS's like Ubuntu 18.04, Raspbian Buster 2019-07-10 and Debian 10 Buster.

Question: Can this be fixed for Kiwix 2.2.0 or 2.1.1?

**Comment by kelson42** [comment]
@ISNIT0 Might that be that you have built a regression here?
