### ISSUE TITLE
Add name and flavour metadata to OPDS

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-tools#316]
In order to improve ZIM selection displays on readers, the OPDS feed should be query-able using the following [Metadata](https://wiki.openzim.org/wiki/Metadata) fields:

* `Name`
* `Flavour`

Those two Metadata also needs to be included in OPDS entries.

Note: would require update of [OPDS Wiki Page](https://wiki.kiwix.org/wiki/OPDS)

**Comment by kelson42** [comment]
@jetownfeve21 Do you think this is something you could work on?
