### ISSUE TITLE
[3.0.0] ZIM favicons are not loaded correctly with kiwix-serve

### ISSUE THREAD

**Issue by hashworks** [kiwix/kiwix-tools#321]
As you can see, ZIM favicons are loaded incorrectly in the latest 3.0.0.
```html
    <a href="/movies.stackexchange.com_en_all_2019-02">
      <div class='book'>
%20%20%20%20%20%20%20%20%3Cdiv%20class%3D'book__background'%20style%3D%22background-image%3A%20url('%2Fmeta%3Fcontent%3Dmovies.stackexchange.com_en_all_2019-02&name=favicon');">
          <div class='book__title' title='Movies &amp; TV Stack Exchange'>Movies &amp; TV Stack Exchange</div>
          <div class='book__description' title='Q&amp;A for movie and tv enthusiasts'>Q&amp;A for movie and tv enthusiasts</div>
          <div class='book__info'>20,562 articles, 54,485 medias</div>
        </div>
      </div>
    </a>
```

![Example Image](https://fb.hash.works/xrS5Q7/)

I'm using the 3.0.0 tag with kiwix-lib 6.0.0.

**Comment by hashworks** [comment]
I just noticed, the search bar autocomplete script is broken as well. Seems to be related.
```js
  var jk = jQuery.noConflict();
  jk(function() {
  jk( "#kiwixsearchbox" ).autocomplete({

%20%20source%3A%20%22%2Fsuggest%3Fcontent%3D",
  dataType: "json",
  cache: false,

  select: function(event, ui) {
  jk( "#kiwixsearchbox" ).val(ui.item.value);
  jk( "#kiwixsearchform" ).submit();
  },

  });
  });

  /* cybook hack */
  if (navigator.userAgent.indexOf("bookeen/cybook") != -1) {
  	jk("html").addClass("cybook");
  }
```

**Comment by kelson42** [comment]
@hashworks I can not reproduce the problem with https://download.kiwix.org/zim/stack_exchange/movies.stackexchange.com_en_all_2019-02.zim and https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64-3.0.0.tar.gz. http://localhost:8080/meta?content=wikipedia_bm_all_2017-03&name=favicon works fine.

My DOM does not looks like yours:
```
<a href="/wikipedia_bm_all_2017-03">
      <div class="book">
        <div class="book__background" style="background-image: url('/meta?content=wikipedia_bm_all_2017-03&amp;name=favicon');">
          <div class="book__title" title="Wikipedia">Wikipedia</div>
          <div class="book__description" title="Wikipedia, ɔnsikopedi hɔrɔn ka nyɛ">Wikipedia, ɔnsikopedi hɔrɔn ka nyɛ</div>
          <div class="book__info">491 articles, 535 medias</div>
        </div>
      </div>
    </a>
```

Could you please try with only this ZIM file and tell me exactly which URL is broken? Have you refreshed properly your browser cache?

**Comment by kelson42** [comment]
This runs fine on library.kiwix.org, so I think kiwix-serve 3.0.0 is fine. @hashworks You might have compiled an older version of the libkiwix of libzim maybe. But the code is fine in kiwix-tools.

**Comment by hashworks** [comment]
Note: This is caused by mustache 4, works fine with mustache 3.2.1.
