### ISSUE TITLE
Kiwix-tools totally broken for windows

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#329]
* With https://download.kiwix.org/release/kiwix-tools/kiwix-tools_win-i686-3.0.1.zip
* Launching `kiwix-manage.exe` does not print the usage() properly (I see only `Usage:`)
* Launching `kiwix-serve.exe` does not print the usage() properly (I see only `Usage:`)
* Impossible to use both `kiwix-serve.exe` and `kiwix-manage.exe` (each time I see an attempt to to print the usage())

**Comment by mgautierfr** [comment]
Fixed by https://github.com/kiwix/kiwix-build/pull/367
