### ISSUE TITLE
Fulltext search from the list of suggestion partly broken w/ kiwix-serve 3.0.1

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#331]
Several schools in Mexico have reverted from kiwix-serve 3.0.1 to 2.1.0 until we understand why this is happening.

Apologies that we're unable to reproduce the exact conditions causing FT (fulltext) search to fail as part of kiwix-serve 3.0.1, as it does not happen all the time.  When it does happen, FT search reverts to Title search, apparently displaying the 1st page on top (of the autocomplete choices).

@kelson42 suggested this might be a browser caching issue, but it (seems) to be more than that, as the failure occurs even with brand new search queries that have never been attempted before.  So unfortunately we do not understand why the problem is happening, under what conditions.

SUMMARY: The failure is extremely frequent and common, to the point where teachers can no longer run Wikipedia-related lessons, and so for now we've reverted to [kiwix-serve 2.1.0](http://download.kiwix.org/release/kiwix-tools/)

Likely this is UNrelated to: #330 "Fulltext search should not try to complete (like the suggestion does"

**Comment by kelson42** [comment]
Are you able to reproduce the problem with https://library.kiwix.org?

**Comment by holta** [comment]
> @holta Are you able to reproduce the problem with https://library.kiwix.org?

Yes the bug appeared immediately when I visited https://library.kiwix.org/wikipedia_fr_top_nopic_2019-08 and the type "france" into the search box, and the selected "containing 'france'..." from the autocomplete/dropdown.

Specifically, the browser then goes to https://library.kiwix.org/wikipedia_fr_top_nopic_2019-08/A/France instead of listing all pages that mention 'france'

**Comment by kelson42** [comment]
@holta good.. might that be that the bug appears only on the welcome page of the ZIM?

**Comment by holta** [comment]
> @holta good.. might that be that the bug appears only on the welcome page of the ZIM?

No.

This bug happens seemingly everywhere (when it's happening) such that teachers cannot get any Fulltext Searches to work at all.

**Comment by kelson42** [comment]
@holta I confirm the bug. You can workardoung this bug by just typing a ' ' after your search and this will force the fulltext search
@mgautierfr @ISNIT0 Looks like a regression... Not sure exactly who has introduced it so far.

**Comment by kelson42** [comment]
@mgautierfr This is a regression in the reader, not in the ZIM.

**Comment by kelson42** [comment]
Clearly related to #205 IMO, this regression would not have occured if the #205 would have been implemented.

**Comment by kelson42** [comment]
@holta Gives us a few hours to make a new binary release
