### ISSUE TITLE
Wikipedia tiled fron page breaks kiwix-serve suggestions

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#332]
The suggestions are on four columns, but they should be on only one like for other pages

![image](https://user-images.githubusercontent.com/1029718/64268039-b2b70300-cf37-11e9-8b43-f69220a4e1e2.png)

**Comment by kelson42** [comment]
@ISNIT0 Any idea why Masonry impacts the topbar of kiwix-serve?

**Comment by mgautierfr** [comment]
This is probably because a css style of the page is also applied to the suggestion list.
