### ISSUE TITLE
New scenario to make kiwix-serve not available anymore

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#336]
1 - http://library.kiwix.org/wikipedia_fr_medicine_maxi
2 - Search for word "dehors"
3 - You get no result but click on the right arrow
4 - The whole service starts to be unavailable... but reappears after a few minutes.

Instead nothing should happen.

In fact the arrows should not be there in that case. See #335

**Comment by mgautierfr** [comment]
https://github.com/kiwix/kiwix-tools/issues/335
