### ISSUE TITLE
No pictures in the library windows when using kiwix-server in Firefox

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-tools#338]
I run kiwix-server with Kiwix-desktop, I open it with firefox, I get a windows without the pictures oft the wiki in the library:
![kiwix-server](https://user-images.githubusercontent.com/19690477/65822999-f0980600-e21b-11e9-9022-0550f081dd18.png)

**Comment by kelson42** [comment]
Duplicate of https://github.com/kiwix/kiwix-lib/issues/264

**Comment by kelson42** [comment]
See also #321
