### ISSUE TITLE
Zim have some external link in main content

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-tools#350]
With wikipedia_en_all_novid_2018-10.zim accessed from Kiwix-serve, in the page "Internal combustion engine", in the first paragraph, "roter" point to an external link "https://en.wiktionary.org/wiki/rotor". Not sure what is the reason behind this, could be some bug in the system that generate the zim?

**Comment by kelson42** [comment]
@wgt98 How is that different from the original content?

**Comment by kelson42** [comment]
No feebdack. Seems perfectly normal. Works as intended.
