### ISSUE TITLE
Stop daemon?

### ISSUE THREAD

**Issue by orionseye** [kiwix/kiwix-tools#354]
It is documented how to start kiwix_serve daemon, but not sure how stop it.
Would `grep `of the pid and then `--stop`  (or `kill `)..be enough?

**Comment by kelson42** [comment]
@orionseye It really depend how you start it exactly.

I see three possibilities:
* You keep it attached (per default) to the process of the terminal so you keep the handle and you can stop it with `CTRL+c` on the keyboard.
* You start it with `--daemon` and then this is detached from the terminal and run in the background. Yes, in that case you will have to send a signal to the process to stop it via `kill`.
* You can also start it via `--attachToProcess` and "attach" it to another process and when this process will be stopped then kiwix-serve will stop as well.

Hope that help.

**Comment by orionseye** [comment]
Merci:) Beautiful ..
