### ISSUE TITLE
Allow multiple `lang` query paramters on OPDS endpoint

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-tools#358]
Currently in the android app we allow multiple languages to be selected when viewing the Library content.

The OPDS stream currently only uses the last `lang` query parameter when performing a search.

**Comment by kelson42** [comment]
@veloman-yunkan Would you be able to fix that one quickly? Seems pretty straight forward to me.

**Comment by veloman-yunkan** [comment]
@kelson42 Will do.

**Comment by kelson42** [comment]
@veloman-yunkan Thank you

**Comment by veloman-yunkan** [comment]
@kelson42 FYI, such filtering can be achieved via the most general form of query using the `q` parameter.

For example:

- http://library.kiwix.org/catalog/search?q=lang:hye%20OR%20lang:ukr&count=100
- http://library.kiwix.org/catalog/v2/entries?q=lang:hye%20OR%20lang:ukr&count=100
