### ISSUE TITLE
kiwix-serve: Option to disable full-text searches

### ISSUE THREAD

**Issue by teran-mckinney** [kiwix/kiwix-tools#369]
Full text searches are extremely intensive and can easily take out a small device like a Raspberry Pi with something like a Wikipedia ZIM.

Having title search isn't as big of a deal. I think having an option to disable full-text searches would help a lot, or setting an adjustable timeout (like give up after 5 seconds so other page loads and searches can go through).

What do you think?

**Comment by kelson42** [comment]
@teran-mckinney It is true that the fulltext search can slow down a low-end device like a RPI. I'm not opposed to the idea of having an option in kiwix-serve to deactivate it. That said I believe a few things can be down to really speedup the fulltext search and we should maybe just raise the priority on this. I recommend you to read #345 which if explains pretty clearly how the fulltext search can slow-down a RPI.

So, I keep your request to think more about it. For now we are just about to implement the zstd compression to allow quicker article decompression time... and one time we will start to make ZIM with zstd, this should really speed-up the fulltext search by at least a factor 5.

**Comment by teran-mckinney** [comment]
Thank you for your response. It would definitely help improving searches by a factor of 5. I still think that might not be enough on some gear, but hopefully.

I guess the most useful takeaway (from what I've thought about here) could be configurable timeouts in case anything starts to runaway, regardless of this. But 5x faster plain text searches would be pretty amazing.

**Comment by kelson42** [comment]
We won’t implement this I believe. Kiwix Hotpost is made for RPIs. If the fulltext search has a serious problem with RPIs we will fix it.
