### ISSUE TITLE
Several Portable Zims Missing Zim File and Index File

### ISSUE THREAD

**Issue by floydianslips** [kiwix/kiwix-tools#37]
Many of the portable zims are missing the zim file and index files. They are the lastest zims from January 19/20 20017. They all seem to be 189MB in size. 
Here is an example:

http://download.kiwix.org/portable/wiktionary/kiwix-0.9+wiktionary_my_all_2017-01.zip

**Comment by kelson42** [comment]
@floydianslips I think I have removed these files. Thank you for reporting this problem. I have also upgrade the ZIM file managing solution to deal with that problem if this would happen again.
