### ISSUE TITLE
kiwix-serve chroot/setuid?

### ISSUE THREAD

**Issue by teran-mckinney** [kiwix/kiwix-tools#376]
For libraries that exist all in one folder, it would seem possible to improve security by using chroot() and setuid(). Otherwise, sandboxing has to happen out-of-band.

What do you think?

**Comment by kelson42** [comment]
I don’t understand which problem we try to fix here!

**Comment by teran-mckinney** [comment]
Sandboxing, in case kiwix-serve is hacked in some way.

Let's say someone is lazy and runs kiwix-serve as root. If there's a vulnerability in kiwix-serve, someone can hack it and then look across the entire filesystem reading whatever they like, maybe executing arbitrary code, etc.

Since Kiwix is generally a read-only application with public files, chroot() + setuid() could help sandbox it if someone runs it as root. It wouldn't prevent all misuse, but lots.

**Comment by kelson42** [comment]
If the user runs as root kiwix-serve, this is his problem... and for the rest there is no problem or things to fix in Kiwix. We provide a Docker image already which is an efficient sandboxing.

**Comment by teran-mckinney** [comment]
I understand. I'm running this under FreeBSD, so Docker doesn't work for me.

I'll just make a user or a Jail and run kiwix-server under it. Thanks!
