### ISSUE TITLE
bad_alloc / Segmentation fault in kiwix-serve

### ISSUE THREAD

**Issue by Prosthet1cHead** [kiwix/kiwix-tools#377]
Just started playing with kiwix-serve on Ubuntu Mate 20.04, it quickly crashed with the following output:

`===== Unhandled error : std::bad_alloc
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /suggest
method    : GET (0)
version   : HTTP/1.1
request#  : 56
headers   :
 - Accept : 'application/json, text/javascript, */*; q=0.01'
 - Accept-Encoding : 'gzip, deflate'
 - Accept-Language : 'en-GB,en;q=0.5'
 - Connection : 'keep-alive'
 - Cookie : 'gutenberg_en_epub-pdf-html_all_2018-10_keys=%23%23gutenberg%3A%3Adefault-sort%23%23gutenberg%3A%3Aundefined%23%23gutenberg%3A%3Apattern%23%23gutenberg%3A%3Aauthor_filter; gutenberg_en_epub-pdf-html_all_2018-10_vals=%23%23popularity%23%23true%23%23The%20War%20of%20the%20Worlds%23%23wells'
 - DNT : '1'
 - Host : 'localhost'
 - Referer : 'http://localhost/gutenberg_en_all_2018-10/A/The%20War%20of%20the%20Worlds.36.html'
 - User-Agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0'
 - X-Requested-With : 'XMLHttpRequest'
arguments :
 - content : 'gutenberg_en_all_2018-10'
 - term : 'dracula'
Parsed : 
url   : /suggest
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Access-Control-Allow-Origin: '*'
 - Content-Type: 'text/html'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
Segmentation fault
`
Note: I'm not an expert coder, just reporting a bug I encountered. If you'd like more info or for me to try anything then I'll do my best!

**Comment by kelson42** [comment]
@Prosthet1cHead What is the md5sum of your file?

**Comment by Prosthet1cHead** [comment]
> @Prosthet1cHead What is the md5sum of your file?
```

~/bin/kiwix-tools$ md5sum *
a48fe28f5e15403ba5b1108083f4df50  kiwix-manage
0bcaf7dacd1b356aea003eca3461fe2e  kiwix-read
bb5efe0367f2bc58d73d64c2a55c8a86  kiwix-search
470c274638222788e169420d1be0c8cd  kiwix-serve
```

Or did you mean the zim file?

**Comment by kelson42** [comment]
Yes the ZIM file

**Comment by Prosthet1cHead** [comment]
> Yes the ZIM file

Calculating now, it will take a little while as it's on a USB HDD. It is as downloaded with Transmission which I believe checks as it goes, so should be ok. Will post back when it's done.

**Comment by Prosthet1cHead** [comment]
@kelson42 md5 sum of the gutenberg zim is:
`b74077a2e069cf9f5c0a5a41fda1fc4b  gutenberg_en_all_2018-10.zim`

**Comment by kelson42** [comment]
@Prosthet1cHead Your version of the ZIM file is corrupted. That said the app should not crash. If you can upload your file somewhere to make it available for us, we would be happy to understand what goes wrong.

**Comment by Prosthet1cHead** [comment]
> @Prosthet1cHead Your version of the ZIM file is corrupted. That said the app should not crash. If you can upload your file somewhere to make it available for us, we would be happy to understand what goes wrong.

Thanks for the offer, but it would take several months for me to upload the 57GB file anywhere, even if I had somewhere to host it. I don't know why transmission is giving the correct md5 value.. perhaps it became corrupt since transmission verified it. Anyway, I will have to download again.

Agree that ideally kiwix-tools would give a warning that the file may be corrupt or similar rather than crash.

Thanks for your help.

**Comment by kelson42** [comment]
You ca check all the checksums at http://download.kiwix.org/zim/gutenberg/gutenberg_en_all_2018-10.zim.mirrorlist
