### ISSUE TITLE
Can Kiwix Server return JSON results?

### ISSUE THREAD

**Issue by lonnietc** [kiwix/kiwix-tools#378]
Hello,

I have just found this wonderful Kiwix project and have been doing a little testing with a Kiwix Docker container and the Wikipedia zim file.

Is it possible for the Kiwix server to submit as search return JSON results as that would be very helpful?

I am running only the Wikipedia zim data and no other will be run on this container so I am hoping to configure it so that the Wikipedia search page comes up as the initial landing page (index.html) and also so that I can send a search query via browser to it.

Any help on these questions would be greatly appreciated.
Thanks in advance

**Comment by kelson42** [comment]
@lonnietc Not really, I think what you need is #52. But you can probably have a json result based on the title suggestions like the what happens in the searchbar at http://library.kiwix.org/wikipedia_en_molcell_nopic/.

**Comment by lonnietc** [comment]
Thanks for the quick response and I'll look into it more.

As I basically want to types of results:

1. Kiwix Server running wikipedia for a html result to do something like: 

http://example.org/search?pattern=test

2. The harder JSON results one it seems:

http://example.org/search?pattern=test&format=json

I'll ding into things more to see what might be possible or how much development it will take.

On a side note, I am also looking into possibly setting up a mirror for:

https://download.kiwix.org/

and would like to get a rough idea as to the space required to mirror the whole download site?

Any ideas on this one as well?
Cheers

**Comment by kelson42** [comment]
@lonnietc If you have a good server for the mirror that would be indeed helfpul.

Here is the current disk usage:
* 3.6 TiB /zim                                                                                                                                                                                                                          
* 824.5 GiB /archive
* 588.4 GiB /hotspots
* 153.8 GiB /other
* 28.7 GiB /nightly

Could I close this ticket as there seem to be nothing much we can do for it?
   21.0 GiB [          ] /release

**Comment by lonnietc** [comment]
Thanks for the reply on the disk usage.

Looks like a lot of space needed.

I have a couple of servers with about 1.5 TB space each. Although I am going to be using them for a project as well, I also think that I could network up some space for Kiwix as well.

Thanks again

**Comment by lonnietc** [comment]
Just a thought, but maybe I can prune out to hold the latest versions of the /zim files as it seems that in each sub-directory that there are additional versions for each language. Wikipedia for example.

[   ] wikipedia_en_all_maxi_2018-06.zim             2018-07-18 21:21   77G   
[   ] wikipedia_en_all_maxi_2018-10.zim             2018-11-06 12:43   78G   
[   ] wikipedia_en_all_mini_2020-03.zim             2020-03-18 19:09   11G   
[   ] wikipedia_en_all_mini_2020-04.zim             2020-04-19 16:30   11G   
[   ] wikipedia_en_all_nopic_2019-12.zim            2019-12-22 10:41   36G   
[   ] wikipedia_en_all_nopic_2020-04.zim            2020-04-16 20:00   37G   

Maybe that is a thought and get the 

wikipedia_en_all_maxi_2018-10.zim             2018-11-06 12:43   78G 

for this an other languages as well as single latest versions for the sliced sub-zim files.

Will play with the numbers.
Thanks
