### ISSUE TITLE
How to install Kiwix lib on Debian

### ISSUE THREAD

**Issue by lonnietc** [kiwix/kiwix-tools#379]
Hello,

I want to start building the kiwix server on my Debian 10 (x86_64) system so that I can work on trying to implement a JSON response system so that somethings like "format=json" can be added to a URL string:

http://www.example.com/search?content=wikipedia_en_all_maxi&pattern=einstein&format=json

I am looking at some c++ html parsers like (mhtml, gumbo, and libtidy etc..) as well as some C++ libraries for JSON generation in that the idea is to just take the resulting html that Kiwix-server produces and generate a JSON return if the "format=json" statement is present before returning the document to the user.

Seems like a nice and elegant approach for a solution but will have to test it.

Now I am just trying to get the Kiwix server to compile with a native build but need to install these Kiwix-Library.

Any ideas?

Thanks in advance

**Comment by kelson42** [comment]
@lonnietc What is the question exactly? Everything should be written in `README.md` and/or `CONTRIBUTING.md`, you should just follow instructions.

**Comment by lonnietc** [comment]
Working on it now.

Seems like my current problem is getting libzim >= 6.1.1 on to my Debian 10 system as the existing library packages are libzim 4.0.1.

Trying now to compile up the libzim library from the sources to see if I can get them to run things.

Should be able to get it working from there.
Thanks

**Comment by lonnietc** [comment]
Solved the compile problems.

Needed to install as root.

Thanks again.
