### ISSUE TITLE
Enhancement - optionally remove Library Button from kiwix-serve nav bar

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#38]
The top nav bar of pages served by kiwix-serve have buttons for library, home, random.

add a runtime switch to remove the library button

**Comment by kelson42** [comment]
So, it is just to remove the button, not the welcome page?

**Comment by tim-moody** [comment]
every page has a bar at the top with 

![image](https://cloud.githubusercontent.com/assets/5678731/26756223/67c1a670-486b-11e7-8ffa-7a72dcd0e880.png)

I am talking about the Library button

**Comment by kelson42** [comment]
done
