### ISSUE TITLE
Clarification on the built executables?

### ISSUE THREAD

**Issue by lonnietc** [kiwix/kiwix-tools#380]
Hello,

I have now been able to build the Kiwix Tools and can start experimenting with them more to get a better feel.

On the github site it says:

1. kiwix-manage: Manage XML based library of ZIM files

2. kiwix-read: Read ZIM file content

3. kiwix-search: Fulltext search in ZIM files

4. kiwix-serve: HTTP daemon serving ZIM files

I know what the kiwix-serve executable does, but is there any additional documentation on the purpose and use of the others?

Thanks again

**Comment by kelson42** [comment]
@lonnietc There is a few things on the wiki.kiwix.org and if you start them without arguments you have a bit more information. But this is all. If something is still unclear, please ask precisely about it.

**Comment by lonnietc** [comment]
Thanks for the reply.

I am reading more of the source code and am getting a feel for the usage.

If I look at the "kiwix-manage" then it says that its purpose is to Manage XML based library of ZIM files.

Does this imply that the ZIM files have XML data, thus is the wikipedia_en_all_maxi_2018-10.zim file composed of XML or HTML data?

The same question goes for kiwix-search and does it return XML or HTML?

I still do not yet have a feel for the ZIM files themselves, but it is becoming clearer with  each question.

Thanks again,
Lonnie

**Comment by mgautierfr** [comment]
`kiwix-manage` is a tool to manage a xml file representing a library (usually called `library.xml`). A library is a collection of zim files.
There is no xml file in a zim file (at least, no specific ones, a zim file can contains any type of data). `kiwix-manage` doesn't change zim file content.

`kiwix-search` search for content using the index embedded in a zim file. The output is a "simple" listing of articles corresponding to the search.

**Comment by kelson42** [comment]
@lonnietc Should we close that ticket?

**Comment by lonnietc** [comment]
Thanks for the clarification on things.
