### ISSUE TITLE
The procedure entry point _create_locale could not be located in the dynamic link library msvcrt

### ISSUE THREAD

**Issue by lczlczlcz1** [kiwix/kiwix-tools#384]
when run the kiwix-tools  on win7 ,this error has occur

**Comment by kelson42** [comment]
Which tool exaxtly? Which version?

**Comment by lczlczlcz1** [comment]
the latest version（3.1.0）, all tools include serve，search ，read，manage have the same problem，when i look up on Google, maybe this is the same issue ，
https://osdn.net/projects/mingw/lists/archive/users/2019-June/000302.html

**Comment by dmzz** [comment]
the same problem with 2008r2 server, but working at 2012+
which version of msvcrt.dll used? or it depence at c++ runtime lib?

**Comment by kelson42** [comment]
Win7is not supported any more by Microsoft. We won't investigate this issue. Sorry, but we have to focus our effort in supported and recent OSes.
