### ISSUE TITLE
Questions: Install Path and Library Error

### ISSUE THREAD

**Issue by nobicycle** [kiwix/kiwix-tools#386]
Hello, on Arch Linux, all compiles and installs with success:

libzim-6.1.5
kiwix-lib kiwix-lib-9.2.2
kiwix-tools kiwix-tools-3.1.1

But library errors occur: 

$ kiwix-serve --help
kiwix-serve: error while loading shared libraries: libkiwix.so.9: cannot open shared object file: No such file or directory

I ran ldconfig as root - nothing happened.

$ ls /usr/local/include
kiwix  zim

$ ls /usr/local/bin/
kiwix-compile-resources  kiwix-manage  kiwix-read  kiwix-search  kiwix-serve

I though perhaps if I installed into prefix /usr instead of /usr/local  then it might fix it but had no luck with

MESON_INSTALL_PREFIX=/usr meson . build

Or

sudo DESTDIR=/usr ninja -C build install

**Comment by mgautierfr** [comment]
Where the libkiwix.so is installed ? From what you said about the binaries, it should be installed in `/usr/local/lib64` or something like that.
I don't know if this path is part of the standard paths configured in Arch linux.
You can add the path at run time by adding it to `LD_LIBRARY_PATH` env variable.
Or you can install the library in standard path using `meson --prefix=/usr . build`

**Comment by nobicycle** [comment]
@mgautierfr 

meson --prefix=/usr . build

That solution worked. I didn't try changing LD_LIBRARY_PATH
Many thanks
