### ISSUE TITLE
Assertion 'last >= first' failed

### ISSUE THREAD

**Issue by dmzz** [kiwix/kiwix-tools#387]
kiwix-serve 3.1.1 @ debian 10 
different zims
error at random function page (not every time),  or at some pages 
kiwix-serve ../../source/kiwix-lib_release/src/server/byte_range.cpp:68 kiwix::ByteRange::ByteRange(...) Assertion 'last >= first' failed.

**Comment by mgautierfr** [comment]
This should be fixed with https://github.com/kiwix/kiwix-lib/pull/364

**Comment by kelson42** [comment]
Duplicate of #363
