### ISSUE TITLE
Newly created ZIM files fail to upload

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#390]
Not sure if duplicate of #389 as the problem is slightly different:

In this case I launch the creation of wiktionary_es_all_maxi_2020-06.zim, which [went smoothly](https://farm.openzim.org/pipeline/5ef4ae7eee7f74c94573f8be) but clicking on the file link to get the ZIM file returns a `not found` (it obviously also does not appear in library.kiwix.org).

I'm saying it may be a slighltly different issue because last time eventhough the file would not appear in the library at least I could access it from the farm.

**Comment by Popolechien** [comment]
Update: I generated a [much smaller ZIM](https://farm.openzim.org/pipeline/5ef5969eee7f74c94574cac2) (`wikipedia_se_all`) and that one was accessible (still not for the `wikitionary_es`)

**Comment by kelson42** [comment]
Bad repo, this is a Zimfarm problem.
