### ISSUE TITLE
[Regression] kiwix-serve unable to load zim files >4GB on ARM builds

### ISSUE THREAD

**Issue by remipp** [kiwix/kiwix-tools#395]
The current 32bit ARM builds are unable to load zim files larger than 4GB (tested with the 38GB wikipedia_en_all_nopic_2020-05.zim), crashing with the following error a few seconds upon execution:

```
Assertion failed at ../../SOURCE/libzim_release/src/buffer.h:42
 size_.v[39675090776] < SIZE_MAX[4294967295]
[0x80c2f0c]
[0x80c96e1]
[0x80c6df5]
[0x80be488]
[0x80bb47f]
[0x80684cd]
[0x80623a4]
[0x8063b46]
[0x8063fe2]
[0x804de18]
[0x85f38f1]
[0x85f3ed9]
[0x80514b7]
```

There seems to be an assertion failing in libzim that specifically checks whether the filesize exceeds 4294967295, or 2^32-1, byte.
While investigating this I tried older builds and it turns out that on version 0.4.0 the aforementioned file seems to work as expected without any errors. All later versions fail with this error.
I'm unsure whether this is libzim's fault or due to improper use of the library, which is why I decided to submit the issue here.

**Comment by kelson42** [comment]
Which version/build of kiwix-serve exactly? Please try with any big file released in 2020-07 to confirm.

**Comment by remipp** [comment]
Oh, I should've tested again with recent builds before opening this issue. I ran into this bug one month ago with `kiwix-tools_linux-armhf-3.1.1-4`, which was the latest release at that time and assumed it wouldn't have been in this period. It turns out that I was wrong and `kiwix-tools_linux-armhf-3.1.2-1` works!
