### ISSUE TITLE
Top Bar layout issue on narrow screen devices

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-tools#40]
The top bar's layout becomes a bit awkward when it comes to narrow screen devices. The buttons and the search bar are taking up two rows.

I think we could a) collapse buttons or b) hide text field and show only when clicked on search button

![screen shot 2017-06-05 at 10 57 54 am](https://cloud.githubusercontent.com/assets/8294252/26789394/2dcee1ac-49de-11e7-871b-982dcf1e9fd9.png)

**Comment by kelson42** [comment]
@automactic Yes, this is superseeded by  #294 and we plan to fix that within two months. Thank you for reporting the problem.
