### ISSUE TITLE
kiwix-serve docker wikipedia_en_all_maxi_2020-06.zim unusable/laggy

### ISSUE THREAD

**Issue by chjohn22** [kiwix/kiwix-tools#400]
The docker image runs perfectly fine with other .zims, such as wikipedia_de_all_maxi_2019-08.
But it needs approximately 20 minutes to start the container with the english one, the german wikipedia appears instantly and does run flawlessly. I cannot even open the file, because it puts my HDD under a heavy load and hangs up. The difference in filesize (34GB DE, 80GB EN) is not very big. Is there another underlying issue?

Hardware: Intel Celeron J4150, 8GB RAM, files are on a HDD, system is on a SSD

**Comment by kelson42** [comment]
@chjohn22 Clearly not normal but it is difficult to say anything more because we don't have this file anymore. Please try to confirm the problem with latest ZIM file https://download.kiwix.org/zim/wikipedia/wikipedia_de_all_maxi_2020-07.zim

**Comment by chjohn22** [comment]
@kelson42 I downloaded the newest zim files and redeployed the container, now it is working. If you serve dozens of zims at the same time it will load for up to half an hour to generate all preview Icons on the main page, but now it runs quite well. Thanks again for this great and simple piece of software!
