### ISSUE TITLE
windows 7 compatibility seems broken

### ISSUE THREAD

**Issue by blueclouds8666** [kiwix/kiwix-tools#401]
hi, while trying kiwix-serve, i found latest version (kiwix-tools_win-i686-3.1.2-1.zip) is giving an error:

missing entry procedure _create_locale on msvcrt.dll
![image](https://user-images.githubusercontent.com/52018385/90831290-b360c900-e343-11ea-9257-c30ec3caaebe.png)

doing some research i found that the called procedure doesn't work on windows 7, causing it to break windows 7 compatibility. it is mentioned in this other repo: https://github.com/dmlc/dmlc-core/issues/478

i have tried running older versions of the kiwix-tools but some just don't open, and others have a bug in which when you type a keyword on the search bar, the server crashes trying to find articles matching that keyword.
![image](https://user-images.githubusercontent.com/52018385/90831491-210cf500-e344-11ea-8e6f-43e52c330738.png)

the only version i could really make work is 0.9, which is quite old. please fix the build so it works on 7 again

**Comment by kelson42** [comment]
Win7 is out of support by MS. We won’t investigate this because we want to focus on newer and maintenained OSes.

**Comment by blueclouds8666** [comment]
windows 7 is still used by 20% of connected computers. companies like cd projekt red and many others do still care for this operating system but a bunch of developers for a philantropist project can't? we aren't asking for AAA game, we are asking for a relatively small program that allows access to an open encyclopedia on places with censorship or no internet connection.

if you don't want to fix an easily fixable error, you are against free knowledge. small communities can't afford for a windows 10 compatible computer nor have the knowledge to use linux. i wish you can stop thinking about your interests as a developer, and start realizing about the real purpose of this project.
