### ISSUE TITLE
Failed to build Docker image for ARM

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#407]
Original base image fails pull when using example command for ARM from modification made in #405:

$ docker build . -t kiwix/kiwix-serve:latest --build-arg ARCH="arm32v7a/"
Sending build context to Docker daemon 3.584kB
Step 1/14 : ARG ARCH=
Step 2/14 : FROM ${ARCH}alpine:3
pull access denied for arm32v7a/alpine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by rgaudin** [comment]
This is not a bug, it's just a typo in the example command. There's an extra `a` at the end.
It should be:

```sh
docker build . -t kiwix/kiwix-serve:latest --build-arg ARCH="arm32v7/"
```

I suggest we close the linked PR as well as:
- doesn't work (or only work if built on arm?)
- uses `latest` image instead of a version one which may lead to problems.
