### ISSUE TITLE
Search bug in kiwix-serve or some problem in the zim file

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-tools#408]
When searching something with "'s", like "Sam's Club", the "'" is replaced with "&_apos;" (without the _) and there won't be result. How to recreate:

1. Run kiwix-serve in kiwix-tools_win-i686-3.1.2-3 to open wikipedia_en_all_maxi_2020-08.zim
2. Use Chrome 85 and paste "Sam's Club" into the search box in the web UI
3. Now there are many matched result in the drop down list, like two "Sam's Club", one "SAM'S CLUB", one "Sam's club". Clicking some of these result will replace "'" with "&_apos;" in the search box without jumping to the target page. In this example only cliking the second "Sam's Club" will work.

**Comment by kelson42** [comment]
I believe this is a duplicate ticket:
* For suggestions: https://github.com/openzim/libzim/issues/276
* For the encoding problem https://github.com/kiwix/kiwix-lib/issues/398
