### ISSUE TITLE
Kiwix-serve should not be affected by ZIM's CSS

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#412]
In [OpenedX ZIM file](https://download.kiwix.org/zim/.hidden/dev/phzh_core-english-one_en_2020-10.zim), the ZIM's CSS rules overwrites those of the kiwix-serve searchbar breaking its UI completely.

![Capture d’écran 2020-10-19 à 17 23 55](https://user-images.githubusercontent.com/21675885/96548221-c0e7f000-12ad-11eb-840b-9bdc9be37526.png)

Given the *dynamic* nature of OpenedX, it's not possible to predict nor to fix CSS there. CSS are fetched from instances and added to the ZIM.

kiwix-serve injecting this searchbar in the document, it should harden itself to prevent document style to break its UI.

**Comment by mgautierfr** [comment]
This is a known problem.
As we integrate the searchbar inside the content page, the css of the content page may impact the searchbar (and the opposite).

We have carefully make the searchbar css to not impact the content but it is impossible (with the current solution) to be fully sure the content css will not impact the searchbar.

There are two solutions here :
- Check what is the searchbar attribute changed by openEDX css and force this attribute to be what we want (for the searchbar only) in the searchbar css. It is faster, but it is a case by case workaround, we will have to fix equivalent bugs later.
- Avoid content CSS to impact the kiwix-serve UI. This can be done with https://github.com/kiwix/kiwix-lib/issues/394

**Comment by rgaudin** [comment]
👍

**Comment by kelson42** [comment]
Here is the online link http://library.kiwix.org/phzh_core-greek-one_el/A/index.html If our Taskbar CSS rules are the latest ans with `!important`, then they should not be overriden. We need to understand exactly what is going wrong here.

**Comment by rgaudin** [comment]
kiwix-lib is looking for `<head>` to inject the head part of the taskbar but it's not present as the head is declared with `<head dir="ltr">`
