### ISSUE TITLE
kiwix-serve fails with stackoverflow.com_en_all_2019-02.zim

### ISSUE THREAD

**Issue by ttsiodras** [kiwix/kiwix-tools#413]
After downloading `stackoverflow.com_en_all_2019-02.zim` and verifying that [it downloaded properly by checking the MD5 checksum](http://download.kiwix.org/zim/stack_exchange/stackoverflow.com_en_all_2019-02.zim.md5) I tried serving this via `kiwix-serve`. This process works fine with all my other ZIM files (including other stackexchange ZIMs) - but not with this one...

I built kiwix-tools from source, and version 3.1.2 of kiwix-serve reports:

    $ kiwix-serve stackoverflow.com_en_all_2019-02.zim
    Unable to add the ZIM file 'stackoverflow.com_en_all_2019-02.zim' to the internal library

Also, zimcheck v2.0.0 reports:

    $ zimcheck stackoverflow.com_en_all_2019-02.zim 
    [INFO] Checking zim file stackoverflow.com_en_all_2019-02.zim
    Error getting mimelists.

The kiwix-tools inside Arch Linux are also reporting the same issue.

I am guessing this ZIM was built in a different way- is there e.g. any options I can pass to kiwix-serve to make it work with this file? Having offline access to stackoverflow is arguably a very useful thing for a developer.

**Comment by kelson42** [comment]
There is definitly a problem with mime-types with this file. This is tracked here: https://github.com/openzim/zim-tools/issues/126. This ticket is pretty much a duplicate. Thank you for reporting the problem.
