### ISSUE TITLE
Library.kiwix.org lists but does not display zim files

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#417]
A recently generated (and functioning) https://library.kiwix.org/diksha-std10ssc_mr_2020-11 returns
`Internal Server Error`

`An internal server error occured. We are sorry about that :/`

`error 24 opening file "/var/www/library.kiwix.org/zim/other/diksha-std10ssc_mr_2020-11.zim `

**Comment by kelson42** [comment]
@Popolechien Works now
