### ISSUE TITLE
kiwix-serve "undefined symbol" error on run

### ISSUE THREAD

**Issue by robinpaulson** [kiwix/kiwix-tools#422]
When I run kiwix-serve, I get this error:
kiwix-serve: symbol lookup error: kiwix-serve: undefined symbol: _ZN5kiwix5splitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_b

Ubuntu 20.04, kiwix-tools installed from the dev ppa on launchpad

**Comment by robinpaulson** [comment]
versions installed:
kiwix                                    2.0.5+git202012121733.f84606b~focal
kiwix-tools                            3.1.2+git202009211612.9efd18a~focal
libkiwix9                               9.4.1+git202012110546.2659f32~focal

**Comment by kelson42** [comment]
@legoktm I believe this is because the libkiwix ABI has changed and we don't have make any commit on kiwix-tools. What is the best way to deal with this problem?

**Comment by robinpaulson** [comment]
as an aside, it would be good to have a stable release of kiwix-tools as well, i note it doesn't exist at the moment

**Comment by kelson42** [comment]
> as an aside, it would be good to have a stable release of kiwix-tools as well, i note it doesn't exist at the moment

Agree.

**Comment by legoktm** [comment]
> @legoktm I believe this is because the libkiwix ABI has changed and we don't have make any commit on kiwix-tools. What is the best way to deal with this problem?

Make some dummy or minor commit in this repository to trigger a rebuild, which will use the new libkiwix ABI.

> as an aside, it would be good to have a stable release of kiwix-tools as well, i note it doesn't exist at the moment

Ack. I can probably do a manual upload unless a release is scheduled for sometime soon?

**Comment by legoktm** [comment]
@kelson42 if you merge https://github.com/kiwix/kiwix-tools/pull/419 it would coincidentally add a new commit to the repo, triggering new builds against the new libkiwix, fixing this issue as well :))

**Comment by kelson42** [comment]
@legoktm Good point, sorry for having overseen that one.

**Comment by robinpaulson** [comment]
Wonderful, that's working now. Shall I close, or leave this open until there's a "release" package for kiwi-tools?

**Comment by legoktm** [comment]
> Wonderful, that's working now. 

Awesome!

> Shall I close, or leave this open until there's a "release" package for kiwi-tools?

What I did for now is copy the current dev packages to the release PPA and trigger rebuilds so they'll build against the released version of libzim/libkiwix/etc. It's functionally the same as 3.1.2, there haven't been any real changes since. And whenever the next release happens, it'll replace the current snapshot.

**Comment by robinpaulson** [comment]
Great, cheers for fixing so quick
