### ISSUE TITLE
Unable to view article names with forward slashes on a wikipedia .zim file

### ISSUE THREAD

**Issue by mechalincoln** [kiwix/kiwix-tools#425]
Hello. I think this issue affects multiple zim files and/or kiwix-serve, but any article name with a forward slash is either not included or the server can't parse article names with a slash.

In the following example, I navigate through my local version of the November 2020 Wikipedia maxi zim file's Device File article. The links that I click on that have forward slashes go to a Not Found page. In the same animation, I also navigate to www.wikipedia.org for their [Device File](https://en.wikipedia.org/wiki/Device_file) article, where the links with forward slashes properly navigate.

I'm hoping this is something that can be looked at.

![devicefile](https://user-images.githubusercontent.com/49933679/102676772-c013f300-4164-11eb-8c9f-5351b336d5a4.gif)

The URLs may just not be escaped correctly, as this works on my local copy: http://192.168.1.97/wikipedia_en_all_maxi_2020-11/A//dev/zero

Kiwix is one of my favorite programs. Thank you again for maintaining it.

**Comment by kelson42** [comment]
This seems to be a bug in the ZIM file iself
