### ISSUE TITLE
kiwix-serve: reload library.xml?

### ISSUE THREAD

**Issue by fpemud** [kiwix/kiwix-tools#426]
Common servers like apache httpd can be notified for configure file change through SIGUSR1.
Can I do the same thing to kiwix-serve after I change the content of library.xml when "kiwix-serve --library" is running?

**Comment by kelson42** [comment]
@fpemud Thank you for your bug report. This ticket is a kind of duplicate of https://github.com/kiwix/kiwix-tools/issues/243.
