### ISSUE TITLE
Some page problem

### ISSUE THREAD

**Issue by zkosk** [kiwix/kiwix-tools#428]
There are errors in the page "Harald_Welte".

Kiwix-serve version 3.1.2
Chrome 87
wikipedia_en_all_maxi.zim (version is not sure, it is the newest zim downloaded at 2020-10 from https://wiki.kiwix.org/wiki/Content_in_all_languages, suggestion: show the version of the zim in the welcome page)

**Comment by kelson42** [comment]
What is wrong exactly? I don't see anything obvious at http://library.kiwix.org/wikipedia_en_all_maxi/A/Harald_Welte.

**Comment by zkosk** [comment]
@kelson42  The zim file used has a size of 99,427,840,722 bytes. Be sure to use the same version for the zim and the program. Do I need to check the hash of the file?

**Comment by kelson42** [comment]
@zkosk You can chech the md5sum... but the main problem is that you have still not explain what is wrong. Please upload a screenshot and explain.

**Comment by zkosk** [comment]
![image](https://user-images.githubusercontent.com/76477726/103989498-bfea9e80-51ca-11eb-9981-b75143c8639a.png)

![image](https://user-images.githubusercontent.com/76477726/103989545-d55fc880-51ca-11eb-9d6b-eedc47eee6d6.png)

Checking md5sum is a long time and error chance is low - I guess BT contains hash for each block.

**Comment by kelson42** [comment]
This kind of problem is not due to a corrupted ZIM file. Maybe a temporary wrong formating of the wiki code. Seems good now in latest version of the ZIM http://library.kiwix.org/wikipedia_en_all_maxi_2020-12/A/Harald_Welte. Not a problem with the reader.

**Comment by zkosk** [comment]
@kelson42 The purpose of the post is to find out possible bugs of the formatting system, to prevent future possible similar "temporary wrong formating". Can you reproduce this with my zim and serve version?
