### ISSUE TITLE
search in a zim file ignores the --nodatealias

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-tools#431]
The search results of <http://127.0.0.1:8888/search?content=wikipedia_en_all_maxi&pattern=kiwix+tools> ignore the --nodatealias and link to the path with date.

![kiwix](https://user-images.githubusercontent.com/2682123/104572813-6f54c480-5654-11eb-8be6-7e4065d7f3a9.png)

**Comment by kelson42** [comment]
@JensKorte Not sure this is a bug, even if this is not super coherent. `--nodatealias` just create an alias to access the content, nothing more!

**Comment by JensKorte** [comment]
maybe there could be a hint at -h
 -z, --nodatealiases     create URL aliases for each content by removing the date  
 -z, --nodatealiases     create URL aliases for the static content by removing the date

**Comment by mgautierfr** [comment]
> Not sure this is a bug, even if this is not super coherent. --nodatealias just create an alias to access the content, nothing more!

Yes, `--nodatealias` means `--nodate-alias`. But it seems it is understood as `--no-datealias`.

---

But we will not change the behavior of the search.
The results are in a specific zim file, we must link to it.
