### ISSUE TITLE
kiwix-serve Home Page zims order

### ISSUE THREAD

**Issue by OscarL** [kiwix/kiwix-tools#434]
I would like to suggest that the order the zims are presented in the home page should be alphabetical, but sorting on the zim's titles, not on their ids at it seems to currently be the case.

Otherwise there seems to be no logic on the sorting, and it does hinders usage, specially with many zims available.

**Comment by kelson42** [comment]
We are revamping that page anyway, see https://github.com/kiwix/kiwix-lib/issues/450. The current situation where we apply no filter at all will be an exception (if possible at all in the future). The library search engine should decide (based on the filter inputs) what is the best order. Probably alphabetically is not the best order. To me "pertinence" seems a better one. I will close this ticket as WONTFIX. But a lot will be done in the next months to have a better page.
