### ISSUE TITLE
kiwix-serve random dice on Windows

### ISSUE THREAD

**Issue by OscarL** [kiwix/kiwix-tools#435]
I keep getting the same articles so frequently, and in the same order, that I made it to a memory game... (its "0..999" or "Macao Special Administrative Region passport" that comes next?) :-)

Happens with an old version of kiwix-serve.exe from 2019, and with 3.1.2 downloaded today. <s>In fact, the newer version is even worse, as it tends to repeat the same articles much more frequently, and if you hit the dice "too fast", it tends to hang the server.</s> #436

Happens with Edge and with Firefox (slightly less bad on Firefox it seems, but maybe its because I tried it on Edge first).

Does not happens when running kiwix-serve (2019 version) from a Linux install.

So I guess the Windows version of the random function is not up to par, but at least should be seeded properly :-)

**Comment by kelson42** [comment]
@veloman-yunkan Might that be our random article feature is not seeded, or not seeded properly?

**Comment by veloman-yunkan** [comment]
@kelson42 `libzim` doesn't call `seed()` at all. `kiwix-lib` calls `seed()` only in the `kiwix::Reader` constructor:

https://github.com/kiwix/kiwix-lib/blob/47496568286bf8311b0bb7e55246442f8728fb0d/src/reader.cpp#L70-L87

Thus, yes, the random article feature is not seeded.

**Comment by OscarL** [comment]
According to an old Hacker news post: "The windows implementation of ANSI C89 rand() was done with a 16 bit linear congruential generator back in the win16 days, and left unchanged for compatibility reasons.".

Linux seems to use a non brain-dead PRNG.

Using something like https://en.wikipedia.org/wiki/Xorshift on Windows might not be a terrible idea :-)

**Comment by kelson42** [comment]
@veloman-yunkan @mgautierfr Should we update https://github.com/openzim/libzim/pull/476 to have a proper random seeding?

**Comment by kelson42** [comment]
@OscarL I suspect the hanging server case has an other root cause, we should probably split this ticket.

**Comment by OscarL** [comment]
@kelson42:

> I suspect the hanging server case has an other root cause, we should probably split this ticket.

Totally. I just mentioned in passing, and a bit out of frustration :-D (#432 prevents me of using 3.12 other than for testing, at least on Windows, haven't had the opportunity to use on Linux yet).

**Comment by kelson42** [comment]
@OscarL All these bugs are indeed frustrating. AFAIK they are Windows specific and this not that well tested. We will do our best to dix them soon.
