### ISSUE TITLE
Gather and print info about dependence libraries version

### ISSUE THREAD

**Issue by lizfrank** [kiwix/kiwix-tools#438]
Is it possible to get a list of the libraries and their version numbers that were used in the binary currently available on kiwix.org?

**Comment by kelson42** [comment]
Yes, we agree that we need that but we should start at the bottom. Here is the corresponding ticket in the libzim https://github.com/openzim/libzim/issues/452

**Comment by pranavich18** [comment]
@kelson42 I read the ticket you mentioned I would like to work on this can you describe it a little more

**Comment by pranavich18** [comment]
Ok! Then I will go for the ticket first.

**Comment by lizfrank** [comment]
Thank you.  Your work is much appreciated :-).
