### ISSUE TITLE
Some problem in some page with links to "/e/" article

### ISSUE THREAD

**Issue by zkosk** [kiwix/kiwix-tools#439]
In the page "MicroG", in the section "Adoption", the link "/e/" in the following content has problem:

"The /e/ operating system"

The "/e/" points to "http://127.0.0.1:8181/e/_(operating_system)", not like normal link such as "http://127.0.0.1:8181/wikipedia_en_all_maxi/A/Refurbishment_(electronics)"

**Comment by kelson42** [comment]
Yes, there is problem. The problem is tracked at https://github.com/openzim/mwoffliner/issues/1368
