### ISSUE TITLE
Search functionality on library.kiwix.org is Unavailable. Error 503.

### ISSUE THREAD

**Issue by cynequil** [kiwix/kiwix-tools#442]
![Screenshot_20210314_132926](https://user-images.githubusercontent.com/19496170/111062872-aff48100-84d1-11eb-83c5-00c8a110098f.png)
**Search** functionality on **library.kiwix.org** is unavailable.

**Comment by kelson42** [comment]
@cynequil Thank you for your bug report, seem to be a duplicate of #385
