### ISSUE TITLE
Propose a welcome page which is fancier

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#448]

**Comment by kelson42** [comment]
We need first to chose what we want to keep from the latest offspot mockup.

**Comment by MananJethwani** [comment]
@kelson42 only the select page(filter page) without navbar is of our use. we can use the same theme or do you want a different theme?

**Comment by kelson42** [comment]
@MananJethwani For the moment, I would focus on this ticket on the tile design and reuse what @siemsie has done. I trust @siemsie @rgaudin @Popolechien for their work. So it should look like:
![image](https://user-images.githubusercontent.com/1029718/120076410-b6909e80-c0a5-11eb-8d0a-12960f0a0334.png)

The "add to cart" Should be replaced by the download link.
That said this is only a start, not a final design.
