### ISSUE TITLE
`kiwix-manage` command used to be available in kiwix/library docker image... which docker image can I found it now?

### ISSUE THREAD

**Issue by dnk8n** [kiwix/kiwix-tools#454]
https://registry.hub.docker.com/r/kiwix/library does not exist anymore. What is an alternative?

**Comment by dnk8n** [comment]
Ok, I should have looked first... but I solved my own problem with the following commit - https://github.com/Wakoma/Lokal/commit/6e540b93eb26a400bbe6b6c2541443f411303091 (i.e. kiwix-manage is now bundled in with the kiwix-serve image and that image is an Alpine Linux environment with ash shell)

**Comment by kelson42** [comment]
@dnk8n I would recommend to better use the new kiwix-tools docker image. I have updated the README to advert it https://github.com/kiwix/kiwix-tools/pull/455
