### ISSUE TITLE
stackoverflow.com_en_all_2019-02.zim

### ISSUE THREAD

**Issue by eroyee** [kiwix/kiwix-tools#463]
Apologies for bringing this up however it's unclear to me if the issue mentioned in #413 and others has been resolved, either by fixing the file or whatever it is that causes kiwix-serve to refuse it?

I would like to download the file, but am reluctant to do so if it's not going to work (it would take days on this connection).

While I recognise the irony that someone wanting to view stackoverflow should probably know how the fix the previously reported issue I'm sorry but I'm just not capable :-(

Thanks.

**Comment by kelson42** [comment]
We are going to release a new version around end of June. Better wait until then.

**Comment by yekanchi** [comment]
> We are going to release a new version around end of June. Better wait until then.

same problem, any update on this?

**Comment by kelson42** [comment]
we are almost good, currentky polishing fully revamped version of Sotoki.

**Comment by eroyee** [comment]
That's good to hear.

In case anyone wondered the same as me (and to save the internet :) the 
latest zimrecreate will *not* accept 
stackoverflow.com_en_all_2019-02.zim as a valid input file...

**Comment by the-turk** [comment]
I've downloaded this file without knowing this issue. How goes the progress?

**Comment by kelson42** [comment]
Good, you will need a fit more of patience to enjoy the new version of the SO ZIM file.

**Comment by the-turk** [comment]
I'm going offline for 6 months the day after tomorrow, any chance for me to get it early?

**Comment by kelson42** [comment]
No, sorry.
