### ISSUE TITLE
Tables Missing

### ISSUE THREAD

**Issue by metal450** [kiwix/kiwix-tools#466]
I'm not sure if this is the most appropriate place to be reporting this, but I just updated my Wikipedia maxi content or the first time since wikipedia_en_all_novid_2018-10.zim (which also seemed to necessitate updating kiwix-serve - the previous build I'd been using would get stuck while trying to load wikivoyage_en_all_maxi_2021-06).  However, now it seems that the 'related topics' tables that appear at the bottom of many articles are all missing. They are not missing from wikipedia itself, so this is definitely not just a function of changing content.  Here's an example:

2018 data:
![2021-07-05 08 52 55](https://user-images.githubusercontent.com/1877409/124496557-6c6a9f00-dd6e-11eb-839b-da8800d4a5a9.png)

vs now (the whole table at the bottom is missing):
![2021-07-05 08 52 43](https://user-images.githubusercontent.com/1877409/124496571-71c7e980-dd6e-11eb-9a15-75f8fba5aa47.png)

These tables were very useful.  Were they deliberately removed, or is it a bug?

**Addendum:**  It looks like other tables are missing, too.  Here's another example:

2018:
![2021-07-05 09 02 34](https://user-images.githubusercontent.com/1877409/124497621-f6ffce00-dd6f-11eb-86b1-e53600046dd9.png)

vs now - the whole 'Numeral Systems' table is gone.  It is not gone on wikipedia itself:
![2021-07-05 09 02 49](https://user-images.githubusercontent.com/1877409/124497657-03842680-dd70-11eb-9d6b-f413af6b4f87.png)

**Comment by mgautierfr** [comment]
This is more a issue for https://github.com/openzim/mwoffliner
But I let @kelson42 answer you, this may be a wanted behavior or something else.

---

> which also seemed to necessitate updating kiwix-serve - the previous build I'd been using would get stuck while trying to load wikivoyage_en_all_maxi_2021-06)

Except for bugs (probably already fixed) or the new compression algorithm zstd used, this should not be the case. What was your previous version of kiwix-serve ?
