### ISSUE TITLE
Kiwix-serve, top-level search returns no result.

### ISSUE THREAD

**Issue by eroyee** [kiwix/kiwix-tools#470]
Kiwix-serve 3.1.2, build 13 July '21, RPi 3 Raspbian 9.13, FF 82.1 (Ubuntu).

After #469 I trialled a later kiwix-serve.

At the home page, the search function does not appear to search within the loaded libraries. 

Searching for anything I've tried to date returns:

'No result. Would you like to reset filter?'

Specifically selecting a library (say Wikipedia) returns the same result.

Also comment/query - hovering or clicking within library frames no longer returns the full path to that library (albeit 'preview' works), is this intended? 

Given this is a nightly build perhaps I'm commenting on something that's still in progress...?

**Comment by maneeshpm** [comment]
I can say that we had decided to disable the top-level search for the moment as it is a work in progress. But individual archive level search should work fine. Any idea @kelson42? is this a bug with the libkiwix-master as well?

**Comment by kelson42** [comment]
Without a detailed reproduction case, won't be possible to confirm. Works for me.

**Comment by eroyee** [comment]
@maneeshpm Thanks, it's operating as expect then, I can confirm individual searches appear fine :+1:

@kelson42  I assume you respond on the search issue?. Given it's been disabled the result is clearly by design so we can close this, however I did mean that a search for literally anything returned that result :-)
