### ISSUE TITLE
kiwix-serve fails non-gracefully with HTTPS requests

### ISSUE THREAD

**Issue by suterma** [kiwix/kiwix-tools#472]
Note: This is NOT about enabling HTTPS (Which is discussed already in https://github.com/kiwix/kiwix-tools/issues/416)

### Problem

This is how the current implementation handles HTTPS requests. The problem is that kiwix-serve non-gracefully fails when a request is done over https. Now, the experienced behaviour described here might very well be the technically correct behaviour for a web server that does not understand TLS, but I would have expected a more precise hint that the issue is caused by an unexpected HTTPS request.

Here is the resulting log:
```
======================
Requesting : 
full_url  : 09�7���'����|��Cn��ױ+��z)��y�
method    : OTHER (9)
version   : jj�+�/�,�0̨̩��
request#  : 0
headers   :
arguments :
Parsed : 
full_url: 09�7���'����|��Cn��ױ+��z)��y�
url   : 09�7���'����|��Cn��ױ+��z)��y�
acceptEncodingDeflate : 0
has_range : 0
is_valid_url : 1
.............
Reject request because of unhandled request method.
----------------------
Application reported internal error, closing connection.
Received malformed line (no colon). Closing connection.
Error processing request (HTTP response code is 400 (`<html><head><title>Request malformed</title></head><body>Your HTTP request was syntactically incorrect.</body></html>')). Closing connection.
Connection was closed while sending response headers.
```
### Steps to reproduce

kiwix-serve (version 3.1.2) was started with this line, on an Ubuntu 20.04, with this line:

`marcel@bluechip:~/Downloads/kiwix-tools_linux-x86_64-3.1.2-5$ ./kiwix-serve --library ~/.local/share/kiwix/library.xml --port=8080 --verbose`

The browser (Google Chrome in this case) does unfortunately not display the produced HTML (as per the log above):
![Screenshot from 2021-07-22 15-17-59](https://user-images.githubusercontent.com/11473920/126645482-6ca2d0fa-a79e-40ae-9ddc-6a048a97f059.png)

### Expected behaviour

1) the log shows a message about the failed HTTPS connection
2) the browser shows the HTML content produced by kiwix-serve

**Comment by kelson42** [comment]
There nothing we can do here. The client makes here a HTTPS request to a HTTP service. Obviously the kiwix-serve backend does not understand the request and it fails at TLS level. What is display if this happen is 100% under the responsability of the HTTPS client.
