### ISSUE TITLE
kiwix-serve does not display a startup message after invocation

### ISSUE THREAD

**Issue by suterma** [kiwix/kiwix-tools#473]
**Problem**
After invocation from the command line, kiwix-serve is not producing an console message, not even in the --verbose mode.

**Expected behavior**
After successful startup, a message like 
`kiwix is running. Start browsing the library at http://192.168.12.78:8080`
should be displayed, also in non-verbose mode.

**Steps to reproduce the behavior:**
Just start kiwix-serve, e.g. using
`$ ./kiwix-serve --library ~/.local/share/kiwix/library.xml --port=8080 --verbose`

**Screenshots**
n/a

**Environment**
- Version of Kiwix serve: 3.1.2
- OS version : Ubuntu OS 20.04

**Comment by kelson42** [comment]
I’m not sure I want to have this is non verbose mode, but yes for the verbose mode.

**Comment by mgautierfr** [comment]
It agree with this. And I think it is ok to have this in non verbose mode. It is a legitimate  information to have in normal mode.

A time ago we were parsing the zim file at startup and kiwix-serve spend few time before being ready. Having a small message would have been a good thing.

**Comment by kelson42** [comment]
Blocked by #613

**Comment by mgautierfr** [comment]
It is not really blocked by kiwix/libkiwix#613.
For now we are binding to all interfaces.
We can simply use "127.0.0.1" as default address when we print the message.

**Comment by kelson42** [comment]
@juzzO Now that https://github.com/kiwix/libkiwix/pull/622 exposes the necessay material, would you be able to use it to fix this? We don’t need to way your libkiwix PR is merged.

**Comment by juuz0** [comment]
@kelson42 Yes :+1:
