### ISSUE TITLE
kiwix-serve causes the error "Assertion failed"

### ISSUE THREAD

**Issue by Colodore** [kiwix/kiwix-tools#480]
Hi there,

I encounter an issue with the following zim file: wikipedia_en_all_nopic_2021-01.zim

When I run the following command on my raspberry pi 4

_./kiwix-serve wikipedia_en_all_nopic_2021-01.zim_

then this error message follows:

_Assertion failed at ../../SOURCE/libzim_release/src/buffer.h:42_
 _size_.v[45692131814] < SIZE_MAX[4294967295]_
_[0x799d4]_
_[0x7fbf8]_
_[0x7d43c]_
_[0x75168]_
_[0x71d98]_
_[0x277b0]_
_[0x2390c]_
_[0x241d4]_
_[0x246ec]_
_[0xf9dc]_
_[0x4c9acc]_

My system:

Raspberry Pi 4 Model B Rev 1.2
OS: Raspbian GNU/Linux 10 (buster)
CPU: 4x ARM Cortex-A72 r0p3 (AArch32) 32 Bit
RAM: 3878080 KiB

With former zim files, I had no such problems. The wikipedia_en_all_nopic_2020-04.zim for example worked fine on my system.

I did some research on the web about this. [Here on your Github page](https://github.com/kiwix/kiwix-tools/issues/389), another user reported the same problem on 19 June 2020. The user mgautierfr (I guess one of your kiwix team) responded that this has been fixed.

On July 1st 2020, another user had the same problem, posted [here on sourceforge](https://sourceforge.net/p/kiwix/discussion/604122/thread/20046c6ed0/?limit=25). Here, Emmanuel Engelhart (I guess one of the kiwix team) responded that it looks like a corrupted zim file.

Appreciate any feedback, thanks a lot.

**Comment by kelson42** [comment]
@Colodore Which version of kiwix-serve to you use? Who has compiled it? Have you tried with a recent nightly https://download.kiwix.org/nightly/ ?

**Comment by Colodore** [comment]
@kelson42 thanks for your reply. I could not figure out which version that was, I downloaded and installed kiwix-serve in April 2020 from [here](https://www.kiwix.org/de/downloads/kiwix-serve/). I today uninstalled everything and re-installed the latest version from the same page, now it seems to work. At least that "Assertion failed" error does not show up anymore after a few seconds. When I start the main work next week on the dataset, I will see if everything works fine again.

**Comment by kelson42** [comment]
Closing for the moment. Please open a new ticket if any new problem occurs.
