### ISSUE TITLE
kiwix-serve displays same output twice if a port in use is given as argument

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-tools#483]
If I give a port which is already in use, kiwix-serve displays the following output twice
`Unable to instantiate the HTTP daemon. The port 8080 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024.`

Image -  (left command was used first)
![image](https://user-images.githubusercontent.com/26814569/133192350-3625c5eb-3182-4e64-800c-c97512d41b76.png)

**Comment by karandeeppotato** [comment]
Hi there,
I'm willing to work on this, can you please assign me?

**Comment by kelson42** [comment]
@karandeeppotato You are welcome, feel free to propose a PR.
