### ISSUE TITLE
kiwix-serve complains about service workers when serving custom zim files.

### ISSUE THREAD

**Issue by el3ctr0lyte** [kiwix/kiwix-tools#487]
I downloaded stallman.org as a zim using the youzim.it website. When i serve it using kiwix-serve and access it using localhost, it works like normal. When accessing it from an ip address, it then complains and says that i need to access the page via https for service workers to work.

![Screenshot_2021-10-09_14-37-12](https://user-images.githubusercontent.com/69082962/136658208-49f8caef-5ca8-439d-81ed-c16ee10564f4.png)

How can i fix this, or maybe this is a bug. I am using the latest version of kiwix-serve (3.1.2-5). I tried it with another website that i also zimmed using youzim.it and the same thing happens.

**Comment by el3ctr0lyte** [comment]
Can i disable it somehow?

**Comment by el3ctr0lyte** [comment]
Is there a way to create a zim without service workers, likw the ones on the kiwix wiki

**Comment by dustinormond** [comment]
Did you ever find out how to create zim files without server workers?

**Comment by kelson42** [comment]
@dustinormond Almost all zim files don't rely on service wrokers... but so far zimit/warc2zim still rely on serivce workers... still not sure this will change
