### ISSUE TITLE
Internal server error: out of memory

### ISSUE THREAD

**Issue by voillyied8122** [kiwix/kiwix-tools#492]
I setup kiwix server on my raspi 4b (4GB RAM with raspi os lite, version : May 7th,2021) and visit the pages on another pc. After I open some zim files and search something, the error occured:
![error.JPG](https://user-images.githubusercontent.com/56959893/138723617-a434dd11-f543-45b3-ace8-5d5dfcbbd0dd.JPG)

And I closed the page, opened it again to do something else, this one occured:
![error2.JPG](https://user-images.githubusercontent.com/56959893/138723775-44ddb938-ab93-4699-b717-fdc19f007b58.JPG)

Could you please tell me what caused these errors and how to get rid of them? Did the word "memory" referred to my SD card or RAM? And what can I do to solve these problem? I would appreciate if someone here could answer me

Here are the free space of my raspi, not sure if this is useful or not. Just put it here since I'm not good at using linux.
![error3.JPG](https://user-images.githubusercontent.com/56959893/138728159-381d57f6-e707-4a6b-afc4-b9b536a54593.JPG)

**Comment by arslan0tahir** [comment]
should we wait for new zim file or newer version of kiwix will do the job??? OR IS THERE ANY WORKAROUND TO RESOLVE THIS ISSUE TEMPORARILY. 
same issue in kiwix nighly

zim: wikipedia_en_all_maxi_2021-03
kiwix: 3.1.2-5
OS: Win 10 x64


===== Unhandled error : Allocation error : not enough memory
========== INTERNAL ERROR !! ============
Requesting :
full_url : /wiki/A/Africa
method    : GET (0)
version   : HTTP/1.1
request#  : 23
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
 - accept-encoding : 'gzip, deflate, br'
 - accept-language : 'en-US,en;q=0.9'
 - connection : 'keep-alive'
 - cookie : 'filters=lang=&q='
 - host : '127.0.0.1'
 - referer : 'http://127.0.0.1/wiki/A/User:The_other_Kiwix_guy/Landing'
 - sec-ch-ua : '"Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"'
 - sec-ch-ua-mobile : '?0'
 - sec-ch-ua-platform : '"Windows"'
 - sec-fetch-dest : 'document'
 - sec-fetch-mode : 'navigate'
 - sec-fetch-site : 'same-origin'
 - sec-fetch-user : '?1'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'
arguments :
Parsed :
full_url: /wiki/A/Africa
url   : /wiki/A/Africa
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'

**Comment by kelson42** [comment]
We will release 3.2.0 and see id it works better. I suspect the problem might be fixed as well with more recent zim files.

**Comment by mgautierfr** [comment]
> should we wait for new zim file or newer version of kiwix will do the job??? OR IS THERE ANY WORKAROUND TO RESOLVE THIS ISSUE TEMPORARILY.

The last version of libzim have a small workaround to mitigate the bug but the problem is still present. Only new zim files will solve completely the issue.

**Comment by kelson42** [comment]
@voillyied8122 We have released kiwix-serve 3.2.0-1. You can find it at https://download.kiwix.org/release/kiwix-tools/. This version should not suffer of the bug you have reported. If this is still the case please reopen the ticket.
