### ISSUE TITLE
Is there a way to access the search function directly from a script?

### ISSUE THREAD

**Issue by Jcwscience** [kiwix/kiwix-tools#495]
I’m trying to use this in a program I’m working on, but I need a way to send the server a search phrase and receive the text of a few matching articles. Is this possible currently? If so how would I go about doing it?

**Comment by mgautierfr** [comment]
If you have a kiwix-serve working (assuming address 127.0.0.1) :
- You can do a search using url `http://127.0.0.1/search?content=<zimname>&pattern=<search_phrase>`
- You will have to parse the html output (no rest API for now, sorry)
- Then you can access the content using the url `http://127.0.0.1/<zimname>/<article_path>` (the url is in the html output)

Or you can use `kiwix-search`/`zimdump` to do the search and dump the article content.
