### ISSUE TITLE
Edit index.html or styles

### ISSUE THREAD

**Issue by ivannyFosters** [kiwix/kiwix-tools#496]
Hi,

Where can i find the 'index.html' file to edit the current styles of the document?
 I want to change the background, links, top taskbar, etc.
![image](https://user-images.githubusercontent.com/92957378/141507615-5304c6ab-0993-42a6-b159-cb738a2b2d70.png)

Thanks,

**Comment by kelson42** [comment]
In latest release, neither the topbar nor the welcome page can be changed (without recompiling kiwix-serve). But in current master (dev. version), there is a new `--customIndex` allowing to specify your custom welcome page template. The documentation is here https://github.com/kiwix/libkiwix/blob/master/README.md#custom-index-page. The topbar remains non-customisable.

**Comment by ivannyFosters** [comment]
Hi, really thanks for your answer.

I tried to modify service file as: ExecStart=/bin/sh -c '/usr/local/bin/kiwix-serve --port 49849 /opt/data/kiwix/*.zim --customIndexPath /var/www/html/index.html'

Doesnt work or --customInde. Where must i edit that parameter to add my custom template?

I dont understand that part.

Thanks, regards.
