### ISSUE TITLE
Compile for MacOS

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-tools#5]
We have to test and make work kiwix-builder/meson on MacOSX.

This should be no real obstacle for this[*], but we have to test and add the inevitable twinks as platforms are different.

[*]
- Other dependency already compile on MacOSX
- Meson support MacOSX
- kiwix-builder is python script, this should just work.

**Comment by kelson42** [comment]
This be currently buggy because of https://github.com/kiwix/kiwix-build/issues/53

**Comment by kelson42** [comment]
@automactic @mgautierfr Hope we can together sort out the last problems and fix them next month.

**Comment by kelson42** [comment]
@mgautierfr Would be great to know what are the current blocker for this.

**Comment by mgautierfr** [comment]
The last time we've tried was at last hackathon in Potsdam and the blocker was ctpp2.

**Comment by kelson42** [comment]
This compiles on MacOS AFAIK
@mgautierfr @automactic Please reopen it if not.
