### ISSUE TITLE
Kiwix-serve with zimit created zim issues with Apache - howto

### ISSUE THREAD

**Issue by clydzik** [kiwix/kiwix-tools#507]
Hello.
This is more question than issue I believe.

Recently I tried to serve pages scrapped with zimit.
I encountered issues that my scrapped page gets redirected to original page instead of served by kiwix-serve.
I would avoid of reposting stuff here - instead I will paste link to issue I created at zimit.

https://github.com/openzim/zimit/issues/110

From support I got there it seems my zim files are correct.
I am able to serve Wikipedia zim but from there I know these are a bit different then the ones I do with zimit.

Now what exactly I need to serve zim file with kiwix-serve behind Apache. My page is via Https just i proxy it through apache.

Thanks for support in advance
Chris

**Comment by kelson42** [comment]
How you have to configure Apache to work as a reverse proxy is out of topic here, we are not Apache experts. Considering kiwix-serve, AFAIK, you don’t need anything more than kiwix-serve itself… but secure the service-worker requirements are satisfied like written in the other ticket.

**Comment by clydzik** [comment]
What i was able to confirm right now that when using localhost with and without `urlRootLocation` it works correctly.
So i suspect that this is apache configuration issue...
