### ISSUE TITLE
Latest dockerhub image is old

### ISSUE THREAD

**Issue by nessguy** [kiwix/kiwix-tools#508]
It looks like when the most recent 'tag' (3.1.2-4) was released in January 2021 a docker image was pushed. It doesn't look like there have been any newer docker builds pushed to dockerhub since then. https://hub.docker.com/r/kiwix/kiwix-serve/tags

As of now the latest docker-image is using alpine 3.12.3 instead of 3.14.

I ran 'docker scan kiwix/kiwix-serve:latest' and got the following results:
```
Package manager:   apk
Project name:      docker-image|kiwix/kiwix-serve
Docker image:      kiwix/kiwix-serve
Platform:          linux/amd64
Base image:        alpine:3.12.3
Licenses:          enabled

Tested 14 dependencies for known issues, found 20 issues.

Base Image     Vulnerabilities  Severity
alpine:3.12.3  20               2 critical, 5 high, 2 medium, 11 low

Recommendations for base image upgrade:

Minor upgrades
Base Image   Vulnerabilities  Severity
alpine:3.14  0                0 critical, 0 high, 0 medium, 0 low
```

While a new release containing the updates over the past year would be nice, even a replay of the last 3.1.2-4 build using alpine:latest would be welcome.

Thanks for making this great project!

**Comment by kelson42** [comment]
We will release 3.2.0 soon.
