### ISSUE TITLE
Links to Library nested ZIM files lead to incorrect URLs

### ISSUE THREAD

**Issue by ISJ-439** [kiwix/kiwix-tools#529]
I click a link on this page **http://FQDN:5555/2010_-_wikipedia_en_wp1-0.8_orig_2010-12/A/Main%20Page.html** 

Which leads to **http://FQDN:5555/A/Wikipedia:0.8/Index.html** This causes a 404.

Workaround: Add **2010_-_wikipedia_en_wp1-0.8_orig_2010-12** before the **/A/** for a URL of **http://FQDN:5555/2010_-_wikipedia_en_wp1-0.8_orig_2010-12/A/Wikipedia:0.8/Index.html**

It's as though the system is unaware it's in a library?

**Comment by ISJ-439** [comment]
I should note, this ZIM file was generated in 2010-12.

**Comment by kelson42** [comment]
This is a really old ZIM file with absolutes URLs. This is not allowed anymore. I have deprecated this file and its not part of our offering. We have more recent versions here http://library.kiwix.org/?lang=eng&q=0.8
