### ISSUE TITLE
Unable to use kiwix-serve, behind a reverse proxy, in a non-root directory

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#54]
_From @tim-moody on June 26, 2016 8:54_

url rewriting did not work for me if kiwix is not mapped to the web root

so mapping to / works (as I remember), but not /kiwix

_Copied from original issue: kiwix/kiwix-xulrunner#254_

**Comment by kelson42** [comment]
I need to have a look where exactly in kiwix-serve are the problems... This is definilty a problem a links and accessing content. So we need to tweak the HTML to allow this.

**Comment by kelson42** [comment]
_From @tim-moody on July 3, 2016 12:56_

I am now back so can set up a test environment and try to reproduce the problems I had.

**Comment by kelson42** [comment]
@tim-moody thx

**Comment by kelson42** [comment]
_From @tim-moody on July 4, 2016 1:54_

using apache 2.4 the easiest kiwix.conf file is

ProxyPass /kiwix http://localhost:3000
ProxyPassReverse /kiwix http://localhost:3000

with this, a url like http://192.168.0.9/kiwix/wikipedia_en_all_2015-05/ reaches its target

but links on that page are for example

http://192.168.0.9/wikipedia_en_all_2015-05/A/Kentucky_Derby.html instead of 
http://192.168.0.9/kiwix/wikipedia_en_all_2015-05/A/Kentucky_Derby.html

same is true of images on the page

**Comment by kelson42** [comment]
_From @tim-moody on July 15, 2016 19:11_

would it be acceptable to introduce a command line parameter for url prefix which would get prepended to humanReadableBookId in the href etc.?

the default would be "" which would make it behave as it currently does.

I think this would be an easy way to fix the non-root proxy problem without having to parse the incoming url.

so the parameter would be -u <urlPrefix>, in my case /kiwix

**Comment by swiftugandan** [comment]
@kelson42 pull request #80 addresses this issue

**Comment by swiftugandan** [comment]
@mgautierfr this is fixed in PR #86

**Comment by kelson42** [comment]
@tim-moody voila, please test it. @swiftugandan Thank you so much!

**Comment by tim-moody** [comment]
preliminary test looks good. thanks very much.

add 	ProxyPass /kiwix/  http://127.0.0.1:3000/kiwix/ to kiwix.conf or some such

now zim pages are accessible via apache and without the port, so access is now in the apache log.

will continue to test.
