### ISSUE TITLE
HTML tags are shown in the text search field

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-tools#542]
![kiwix-with-html-tags](https://user-images.githubusercontent.com/2682123/154429850-b844d25f-29e6-4f45-8465-1a4402c2f75b.png)

kiwix-tools_linux-armhf-3.2.0-1 binary download from kiwix.org. The System is a Pi400 with Gentoo 64bit. Firefox 91.6.0esr (64-Bit)

**Comment by kelson42** [comment]
@JensKorte Either your ZIM file is old or you need to make a refresh of your cach CTRL+SHIFT+R. This should work perfectly and it does for me for example at http://library.kiwix.org/wikipedia_de_all_maxi/A/Benutzer:The_other_Kiwix_guy/Landing (same version of kiwix-serve.
