### ISSUE TITLE
[Question] Best Practices for creation of Wikipedia ZIMs from dumps?

### ISSUE THREAD

**Issue by ISJ-439** [kiwix/kiwix-tools#543]
Hello,

I would like to create some missing ZIM files from historical Wikipedia dumps. How would I best do this?

My potential approach:
1. Download the dump.
2. Load the dump into a yet unknown program that will display the dump on a web server.
3. Run the kiwix-tools on the web server locally backing it up.

Im fairly tech savvy I just dont know what the best way to do this is, can anyone clarify at a high level?

Thank you,

ISJ

**Comment by JensKorte** [comment]
Did you have a look at https://wiki.openzim.org/wiki/Build_your_ZIM_file ? I must confess, I tried some programs some years ago and I had not found an easy solution.

**Comment by kelson42** [comment]
@ISJ-439 We don't provide any solution do to a ZIM from a Mediawiki XML dump.
