### ISSUE TITLE
kiwix-manage error "cannot add zim url to library"

### ISSUE THREAD

**Issue by UncoveredBulb** [kiwix/kiwix-tools#568]
i'm using 

`$ ./kiwix-manage --version
kiwix-tools 3.3.0

libkiwix 11.0.0
+ libzim 7.2.2
+ libxapian 1.4.18
+ libcurl 7.67.0
+ libmicrohttpd 0.9.72
+ libz 1.2.12
+ libicu 58.2.0
+ libpugixml 0.12.0

libzim 7.2.2
+ libzstd 1.5.2
+ liblzma 5.2.4
+ libxapian 1.4.18
+ libicu 58.2.0
`
on a raspberry pi 4 running nixos 21.11 AArch64

if i run 
`$ ./kiwix-manage library_zim.xml add appropedia_en_all_maxi_2021-03.zim`

kiwix-manage updates the library_zim.xml file correctly, and kiwix-serve successfully hosts the library.

however, i want download links to be available so that anyone using my library can download, for example, appropedia for themselves. ideally, i would like people to be able to download appropedia and other .zim files that are hosted on my machine, or from a .torrent file hosted on my machine. however, first, i'd want to get the basic download functionality working. i read https://wiki.kiwix.org/wiki/Kiwix-manage & it looks like the correct format to tell kiwix-manage to show a download button pointing to appropedia on library.kiwix.org (https://download.kiwix.org/zim/other/appropedia_en_all_maxi_2021-03.zim) is 

`$ ./kiwix-manage library_zim.xml add appropedia_en_all_maxi_2021-03.zim [url|u=https://download.kiwix.org/zim/other/appropedia_en_all_maxi_2021-03.zim]
`
or 

`$ ./kiwix-manage library_zim.xml add appropedia_en_all_maxi_2021-03.zim [url|u=https://download.kiwix.org/zim/other/appropedia_en_all_maxi_2021-03.zim.meta4]
`
or maybe 

`$ ./kiwix-manage library_zim.xml add appropedia_en_all_maxi_2021-03.zim [url|u=https://download.kiwix.org/zim/other/appropedia_en_all_maxi_2021-03.zim.metalink]
`
i tried all of these, and each time ./kiwix-manage returned,

`$ ./kiwix-manage library_zim.xml add appropedia_en_all_maxi_2021-03.zim [url|u=https://download.kiwix.org/zim/other/appropedia_en_all_maxi_2021-03.zim.meta4]`
`Cannot add zim [url to the library.`

i also considered that it might be a formatting error, somehow, and tried variations on removing the [] and `url|` and enclosed the url as a string.

for example:
`$ ./kiwix-manage library_zim.xml add appropedia_en_all_maxi_2021-03.zim url|u=https://download.kiwix.org/zim/other/appropedia_en_all_maxi_2021-03.zim.meta4`
`Cannot add zim url to the library.
`
i would like to add the zim url or the correct zim url to the library. i'd like to know why it can't add that zim url to the library.

i don't know how to read kiwix-manage & i figured maybe there was a difference in formatting between the documentation and the script, but i'm stuck. i don't know if there's something wrong with the script or if i'm failing to understand the instructions. i'd like to know what's gone wrong, and also what the parameters are for kiwix-manage to display a url for any given .zim file. 

i'd also like to know how to have the download link on my zim library that i'm hosting with kiwix-serve point to a .torrent file someone could download over a LAN, if there were no outside internet. for example, if my raspberry pi is hosting appropedia, i want other people on my LAN to be able to copy a .torrent file for appropedia to their machines. if my raspberry pi loses connection to the LAN, but machine_B has the .torrent file, and machine_C has a copy of appropedia in their utorrent client, i'd like whoever owns machine_B to be able to download appropedia from machine_C, so if they want to host kiwix-serve themselves with the .zim files, they can replicate my work.

it's also unclear to me what 
`[--zimPathToSave|-z=the_string_you_want_to_see_in_the_library] [--indexPath|-i=FULLTEXT_IDX_PATH]`
means, in the examples provided on https://wiki.kiwix.org/wiki/Kiwix-manage

**Comment by veloman-yunkan** [comment]
The documentation of Kiwix-manage at https://wiki.kiwix.org/wiki/Kiwix-manage contained several issues. Now they are fixed.

```
$ ./kiwix-manage library_zim.xml add appropedia_en_all_maxi_2021-03.zim --url=https://download.kiwix.org/zim/other/appropedia_en_all_maxi_2021-03.zim
```

**Comment by UncoveredBulb** [comment]
that works, thank you.

`[--zimPathToSave|-z=the_string_you_want_to_see_in_the_library] [--indexPath|-i=FULLTEXT_IDX_PATH]` & torrents?
