### ISSUE TITLE
Kiwix-serve Docker container can't open .zim file.

### ISSUE THREAD

**Issue by grenius** [kiwix/kiwix-tools#570]
My environment: raspberry Pi4 4gb/ Raspberry Pi OS Bullseye 64bit

I have the .zim file on a SSD if that's a variable worth considering.

My initial run command:

docker run -d --name kiwix -v /mnt/ssd/kiwix/:/data -p 8282:80 kiwix/kiwix-serve *.zim 

Log upon container creation:

docker logs --tail 30 -f kiwix [?2004l /usr/local/bin/kiwix-serve --port=80 wikipedia_en_all_maxi_2022-05.zim Unable to add the ZIM file 'wikipedia_en_all_maxi_2022-05.zim' to the internal library. Here is the content of /data: /data/wikipedia_en_all_maxi_2022-05.zim

I tried a fix by @kelson42 (thanks again) 

docker run -d --name kiwix -v /mnt/ssd/kiwix/:/data -p 8282:80 kiwix/kiwix-serve '*.zim' `

But the container just seems to hang with a >

Edit: after letting it run for a while this was the output:

$ docker run -d --name kiwix -v /mnt/ssd/kiwix/:/data -p 8282:80 kiwix/kiwix-serve '*.zim'`                                      
>
-bash: unexpected EOF while looking for matching ``'
-bash: syntax error: unexpected end of file

Any help is appreciated.

**Comment by kelson42** [comment]
@grenius You jave problems woth backticks. You should at least not have one at the end.

**Comment by grenius** [comment]
@kelson42 yeah it was copied directly from your post. I removed the back tick and still no good.

**Comment by kelson42** [comment]
What do you type now and what do you get exactly?

**Comment by grenius** [comment]
@kelson42 it works. Thank you for your help. Though I did move the zim off the SSD and on to internal memory. Not sure if that changed anything. Thanks again, please close this ticket.
