### ISSUE TITLE
Provide a sample library.xml file

### ISSUE THREAD

**Issue by JosephNuthalapati2244** [kiwix/kiwix-tools#574]
The website mentions that there's a sample file at https://www.kiwix.org/library.xml, but the link appears to be broken.

**Comment by kelson42** [comment]
Where is this broken link exactly?

**Comment by JosephNuthalapati2244** [comment]
Sorry, the sample library.xml file is supposed to be on the website, but it's not mentioned on the website. There are links to it from two other places:

* man page of kiwix-manage
* [Wiki page](https://wiki.kiwix.org/wiki/Kiwix-manage) of kiwix-manage

**Comment by kelson42** [comment]
I have fixed the wiki page

**Comment by kelson42** [comment]
@JosephNuthalapati2244 Thx for the bug report, I made a small PR to fix the man page. Let us know if you find other oudated things.

**Comment by kelson42** [comment]
Our main example of `library.xml` is available here https://download.kiwix.org/library/library_zim.xml
