### ISSUE TITLE
Man page for kiwix-manage is outdated

### ISSUE THREAD

**Issue by JosephNuthalapati2244** [kiwix/kiwix-tools#575]
I was confused by the "url" option mentioned in the man page for kiwix-manage. I expected that kiwix-manage would download and add a ZIM file to its library with this option. However, this option doesn't exist in the latest kiwix-tools.

There is a `--url` flag for the "add" option, which adds a hyperlink to the original source of the ZIM file in the library file.

There are 3 flags mentioned in the man page which are not in the source code anymore: `--current`, `--backend` and `--indexPath`

**Comment by kelson42** [comment]
Yes, this tool is not to download anything. I have rewritten the man page in the linked PR.
