### ISSUE TITLE
docker error "Unable to add ZIM file 'stackoverflow.com_en_all_nopic_2022_07.zim' to the internal library." 

### ISSUE THREAD

**Issue by monstermaker** [kiwix/kiwix-tools#578]
Having an issue on Ubuntu 17.04 machine with the stackoverflow.com_en_all_nopic_2022_07.zim file.
The debug message says:
"Here is the content of /data:
/data/stackoverflow.com_en_all_nopic_2022_07.zim"

I have checked the permissions on the file and set it to 777 temporarily to make sure that permissions are not the issue. I am not sure if the leading /data is correct and the content of /data should be stackoverflow.com_en_all_nopic_2022_07.zim and not /data/stackoverflow.com_en_all_nopic_2022_07.zim

Any ideas?

**Comment by kelson42** [comment]
please share the full log of coommand you run

**Comment by monstermaker** [comment]
This is what I ran:
userprompt@myserver:~$ sudo docker run -v /path/to/my/folder/library:/data -p 8888:80 kiwix/kiwix-serve stackoverflow.com_en_all_nopic_2022_07.zim

The output was:

/usr/local/bin/kiwix-serve --port:80 stackoverflow.com_en_all_nopic_2022_07.zim
Unable to add ZIM file 'stackoverflow.com_en_all_nopic_2022_07.zim' to the internal library.
Here is the content of /data:
/data/stackoverflow.com_en_all_nopic_2022_07.zim

**Comment by monstermaker** [comment]
Problem Solved. It appears that this copy of the zim may have been corrupted.
The original zim file I ad was downloaded through windows and transferred to the Linux machine using SCP. I have now downloaded using wget on the Linux machine direct from the source and it appears to be working.
