### ISSUE TITLE
Kiwix deployments that don't redirect arbitrary path to content path are vulnerable to XXS injection

### ISSUE THREAD

**Issue by ClevenL** [kiwix/kiwix-tools#605]
Sorry for being a bit vague. 
I have identified some deployments of Kiwix that do not redirect arbitrary path to `content` path and therefore are vulnerable to XSS injection.

Deployment like this would trigger an XXS with eg. payload:
`https://kiwix.example.domain/%22%3E%3Cimg%20src=X%20onerror=alert(1)%3E`
`https://library.kiwix.org/%22%3E%3Cimg%20src=X%20onerror=alert(1)%3E`

`library.kiwix.org` redirects correctly to `content` path where the input is correctly sanitized. 
`https://library.kiwix.org/content/%22%3E%3Cimg%20src=X%20onerror=alert(1)%3E`

What would be a solution to redirect the path to `content`? Is there a missing configuration? Since I have identified several deployments with this kind of issue then the deployment process might need updating to avoid the misconfiguration.

**Comment by kelson42** [comment]
@mgautierfr Do you mean this bug is fixed or inoperant in latest version of kiwix-serve?
