### ISSUE TITLE
What is compile_resources.py needed for?

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-tools#61]
I'm working on the Debian packaging for kiwix-tools and ran into the following:

```
Running test binary command: /home/km/projects/debian/kiwix-tools/obj-x86_64-linux-gnu/meson-private/sanitycheckcpp.exe
Native cpp compiler: c++ (gcc 6.4.0)
Appending CXXFLAGS from environment: '-g -O2 -fdebug-prefix-map=/home/km/projects/debian/kiwix-tools=. -fstack-protector-strong -Wformat -Werror=format-security'
Appending LDFLAGS from environment: '-Wl,-z,relro'
Appending CPPFLAGS from environment: '-Wdate-time -D_FORTIFY_SOURCE=2'
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29)
Determining dependency 'kiwix' with pkg-config executable '/usr/bin/pkg-config'
Native dependency kiwix found: YES 1.0
Determining dependency 'libmicrohttpd' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libmicrohttpd found: YES 0.9.55
Determining dependency 'zlib' with pkg-config executable '/usr/bin/pkg-config'
Native dependency zlib found: YES 1.2.8
Determining dependency 'xapian-core' with pkg-config executable '/usr/bin/pkg-config'
Native dependency xapian-core found: YES 1.4.4
Program compile_resources.py found: NO

Meson encountered an error in file static/meson.build, line 2, column 0:
Program "compile_resources.py" not found or not executable
```

Is this referring to the compile_resources.py file in kiwix-lib? Why is that python file needed? And where should I be putting it to make this work?

**Comment by mgautierfr** [comment]
> Is this referring to the compile_resources.py file in kiwix-lib?

Yes.
It should be installed by kiwix-lib.

> Why is that python file needed?

This is needed to compile the resources as "C array style" resources embedded in the final binary.

> And where should I be putting it to make this work?
This file should be installed in a directory in the PATH variable.
`kiwix-lib` should install it in `[prefix]/bin`

This script is needed a compilation only. It is not need for kiwix-tools binaries execution.
Says otherwise, on a package point-of-view, it should be in kiwixlib-devel, not kiwixlib

**Comment by legoktm** [comment]
OK, that should be doable then. Could the script be called "kiwix-compile-resources" or something that's not vague and generic? Also if it's being installed to /usr/bin/ it probably doesn't need a .py extension.

**Comment by legoktm** [comment]
Also, is it possible for meson to install it into /usr/bin when building kiwix-lib?

**Comment by legoktm** [comment]
Ping @mgautierfr :)

**Comment by kelson42** [comment]
@legoktm @mgautierfr is off for a week.

**Comment by mgautierfr** [comment]
> Could the script be called "kiwix-compile-resources" or something that's not vague and generic? Also if it's being installed to /usr/bin/ it probably doesn't need a .py extension.

Yes, I can rename it.

> Also, is it possible for meson to install it into /usr/bin when building kiwix-lib?

It is already the case https://github.com/kiwix/kiwix-lib/blob/master/scripts/meson.build#L5
If not, there is a bug somewhere. (It works for me™️ )

**Comment by legoktm** [comment]
> It is already the case https://github.com/kiwix/kiwix-lib/blob/master/scripts/meson.build#L5
If not, there is a bug somewhere. (It works for me™️ )

Yup, you're right, it's installed properly. OK, so once this is renamed to something less generic, it should be fine for Debian :)

**Comment by legoktm** [comment]
I submitted the following PRs to rename compile_resources.py (I'm not sure if there are other places it needs to be renamed?)

* https://github.com/kiwix/kiwix-lib/pull/76
* https://github.com/kiwix/kiwix-tools/pull/63

**Comment by mgautierfr** [comment]
The two PRs have been merged.

I'm closing this issue.
