### ISSUE TITLE
Fix print option

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-tools#619]
Currently, if I try to print the current page using the browser shortcut, it contains the taskbar too and all content is not printed.
Example for Arch Wiki (only 1 page):
![image](https://user-images.githubusercontent.com/26814569/236597906-9d3d64a2-d22e-496e-8653-4236052c1cf3.png)

Expected (4 pages):
![image](https://user-images.githubusercontent.com/26814569/236597930-4877be2f-69e8-4165-9b15-361b451d0082.png)

We can override the print behaviour and/or add a print button in taskbar

**Comment by mgautierfr** [comment]
The classic way to fix that is to use custom css  : https://developer.mozilla.org/en-US/docs/Web/Guide/Printing

**Comment by kelson42** [comment]
I guess here print css should be scraped and announced properly in HTML. Sounds a ticket for MWofflinet,?!

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/mwoffliner](https://github.com/openzim/mwoffliner/issues/1950)
