### ISSUE TITLE
Add OpenSearch <link> to head of pages

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-tools#620]
kiwix-serve has opensearchdescription at https://kiwix-tools.readthedocs.io/en/latest/kiwix-serve.html#catalog-v2-searchdescription-xml but doesn't mention it in the head of the page

See https://developer.mozilla.org/en-US/docs/Web/OpenSearch#autodiscovery_of_search_plugins

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan Anything stopping is to implement this quickly? Seems trivial!?

**Comment by mgautierfr** [comment]
The only reason I could find to not add it is that this opensearch is about searching for books in the catalog and not for articles available in all the library.
It could be disturbing for the user.

And as specified in the [mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#troubleshooting_tips):

> You must include a text/html URL — search plugins including only Atom or [RSS](https://developer.mozilla.org/en-US/docs/Glossary/RSS) URL types (which is valid, but Firefox doesn't support) will also generate the "could not download the search plugin" error.

It would be possible to have an opensearchdescription that point some html content
(Which one ?) Maybe easy, but not trivial. 


---

Note that it is already present in the all "catalog" pages (`root.xml`, `search`, ...)
It is missing only in the main html page (viewer)

**Comment by kelson42** [comment]
@mgautierfr So should we just implement it?
