### ISSUE TITLE
Can kiwix-tools armv6 and armv8 be made downloadable with version-independent redirects, as with all other arch's?

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#623]
@mgautierfr

As seen on page:

https://www.kiwix.org/en/downloads/kiwix-serve/

Currently these redirects work:

https://download.kiwix.org/release/kiwix-tools/kiwix-tools_win-i686.zip
https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64.tar.gz
https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-i586.tar.gz
https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-aarch64.tar.gz

Whereas these redirects do not (yet!) work:

https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv6.tar.gz
https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv8.tar.gz

Just FYI there's one legacy redirect here, that currently leads to a broken v3.5.0 build:

https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armhf.tar.gz

**Comment by kelson42** [comment]
@holta Working redirects are listed on [Product page](https://www.kiwix.org/en/downloads/kiwix-serve/). AFAIK all the binaries are available through them, so we don't need anything additional.

@mgautierfr Why do we have newly files [kiwix-tools_linux-armv8-3.5.0-1.tar.gz](https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv8-3.5.0-1.tar.gz) and [kiwix-tools_linux-armv6-3.5.0-1.tar.gz](https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv6-3.5.0-1.tar.gz). We should stick to the `aarch64` and `armhf` like before, otherwise it should have been discussed. Why we don't have the latest build with https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv6-3.5.0-1.tar.gz?

**Comment by mgautierfr** [comment]
> @mgautierfr Why do we have newly files [kiwix-tools_linux-armv8-3.5.0-1.tar.gz](https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv8-3.5.0-1.tar.gz) and [kiwix-tools_linux-armv6-3.5.0-1.tar.gz](https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv6-3.5.0-1.tar.gz). We should stick to the aarch64 and armhf like before, otherwise it should have been discussed. Why we don't have the latest build of [kiwix-tools_linux-armhf-3.5.0.tar.gz](https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armhf-3.5.0.tar.gz)? It's important we stick to the naming, otherwise it has important consequences.

This came from this PR : https://github.com/kiwix/kiwix-build/pull/615

As said in the description: "This introduce a difference between armv6 and armv8."

**Comment by kelson42** [comment]
@rgaudin Any feedback about the differences and benefits between `armhf`, `armv6`, `armv7` and `armv8`?

**Comment by rgaudin** [comment]
https://github.com/offspot/container-images/wiki/Raspberry-Pi-Models

**Comment by rgaudin** [comment]
Let me know if should add the redirects ; for Linux we currently build

- `kiwix-tools_linux-x86_64`
- `kiwix-tools_linux-aarch64`
- `kiwix-tools_linux-armv6`
- `kiwix-tools_linux-armv8`
- `kiwix-tools_linux-i586`

Here's the Dockerfile for kiwix-tools image (not merged)

https://github.com/kiwix/kiwix-tools/blob/91a9dff87a2e846decdc6c7b39fbd9cf85b31bd6/docker/Dockerfile#L11-L22

**Comment by mgautierfr** [comment]
> Raspbian armhf means ARMv6 + VFPv2 while Debian armhf means ARMv7.

This confirms to me that we should stay with armv6 and armv8 and stop naming our build with armhf

**Comment by rgaudin** [comment]
Should we remove the `3.5.0` armhf file? It's broken, there's no update and from what I understand, there won't be.

I just got fooled updating the hotspot with the latest `armhf`

**Comment by kelson42** [comment]
I hope I understand all the aspects of this problem. Here would be what I would recommend:
* Remove last broken build of `armhf` for Linux
* Remove `armhf` link in https://www.kiwix.org/en/downloads/kiwix-serve/
* Add link to `armv6` as offer for the ARM 32 bits at https://www.kiwix.org/en/downloads/kiwix-serve/
* Fix kiwix-tools (and kiwix-serve) container images (like @rgaudin as proposed)
* Fix zim-tools container images the same way

@mgautierfr @rgaudin Does that makes sense? What else should be updated?

**Comment by rgaudin** [comment]
- [x] Remove last broken build of `armhf` for Linux
- [ ] Remove `armhf` link in https://www.kiwix.org/en/downloads/kiwix-serve/ @Popolechien 
- [ ] Add link to `armv6` as offer for the ARM 32 bits at https://www.kiwix.org/en/downloads/kiwix-serve/ @Popolechien 
- [ ] Fix kiwix-tools (and kiwix-serve) container images (like @rgaudin as proposed) @mgautierfr 
- [ ] Fix zim-tools container images the same way.

@kelson42 `zim-tools` image is `x86_64` only

**Comment by Popolechien** [comment]
I've replaced the `armhf` link with a link to [kiwix-tools_linux-armv6-3.5.0-1.tar.gz](https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv6-3.5.0-1.tar.gz) but for future iterations it would be good to have a more generic redirect (e.g. `kiwix-tools_linux-armv6.tar.gz`) much like the others.

**Comment by kelson42** [comment]
@rgaudin Can you please put the few additional redirects in place?

**Comment by rgaudin** [comment]
> @rgaudin Can you please put the few additional redirects in place?

Done and deployed.
As of today, every single Kiwix and openZIM release file should have a version-less redirect.

**Comment by mgautierfr** [comment]
Sorry about late reply but:
>Remove armhf link in [kiwix.org/en/downloads/kiwix-serve](https://www.kiwix.org/en/downloads/kiwix-serve/) @Popolechien

It would be better to setup a redirection instead of removing ?

> Add link to armv6 as offer for the ARM 32 bits at [kiwix.org/en/downloads/kiwix-serve](https://www.kiwix.org/en/downloads/kiwix-serve/) @Popolechien

What about armv8 ?
If we don't create a redirection for it, I suggest we don't build/publish it neither.

**Comment by Popolechien** [comment]
@kelson42 Done.

**Comment by kelson42** [comment]
@rgaudin so i guess there is only the work on the two container images left.

**Comment by rgaudin** [comment]
> @rgaudin so i guess there is only the work on the two container images left.

What work? This PR has been sitting there for 3 weeks. There's nothing left to do but merge

**Comment by rgaudin** [comment]
> @rgaudin (1) Fix kiwix-tools (and kiwix-serve) container images (2)

I'm sorry I really don't understand what you are talking about. This is #622 

>  Fix zim-tools container images the same way.

That I haven't submitted a PR yet.

**Comment by kelson42** [comment]
@rgaudin Thx, I have merged https://github.com/kiwix/kiwix-tools/pull/622

**Comment by kelson42** [comment]
@rgaudin I have created https://github.com/openzim/zim-tools/issues/351 to request the improvement of container images on ZIM tools. That way we can also close this ticket. @holta Thank you for pointing the many bugs and weaknesses around the distribution of the Kiwix Tools binaries.
