### ISSUE TITLE
Allow tag filtering in kiwix-serve

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#624]
Following the discussion at https://github.com/openzim/zim-requests/issues/669 it appears that we can add tags to zim files, hoewever we do not seem to be able to sort these same tags on library.kiwix.org (only categories). 

Since a zim file could have several tags, the ability to do multiple picks as in the below screenshot should be made available
![Capture d’écran 2023-06-16 à 11 57 10](https://github.com/kiwix/kiwix-tools/assets/21675885/db083b56-37ef-4866-896d-c5608ce19ac5)

**Comment by kelson42** [comment]
@Popolechien There is no tag filter and this is pretty mich on purpose. What use case do you have exactly? If you want to search for something, just use the search field.

Related to https://github.com/kiwix/libkiwix/issues/582

**Comment by Popolechien** [comment]
Well if I am a prepper and I look for prepper material, how will I find it?

**Comment by kelson42** [comment]
@Popolechien I don't understand what are the "several dozens of files" you evocated. I can only repeat what I just have written: if you want to search survivalisme content, you type "preppers" in the search box and you will get all the appropriate books.

**Comment by Popolechien** [comment]
Yup good.
