### ISSUE TITLE
Custom / Default icons needed

### ISSUE THREAD

**Issue by rthawkcom** [kiwix/kiwix-tools#627]
Not all the .zim archive files include a default icon.   Also, it would  be nice to override existing default icons with custom made icons.  I would suggest having the application check for the presence of a picture file, by the same name as the .zim archive, and if present, use that in place of the missing or default icon.

**Comment by kelson42** [comment]
@rthawkcom AFAIK you can do that if you put the favicon in the library.xml. The kiwix-manage does not allow to do that, but this should work like you expect in kiwix-serve.

**Comment by kelson42** [comment]
Having a favicon is clearly now [a requirement](https://wiki.openzim.org/wiki/Metadata).

But related to https://github.com/kiwix/libkiwix/issues/989
