### ISSUE TITLE
Can password access be supported?

### ISSUE THREAD

**Issue by adangran** [kiwix/kiwix-tools#628]
Can password access be supported kiwix web?How to set it up?

**Comment by mgautierfr** [comment]
This is not possible directly with kiwix-serve.
But if you setup a proxy (nginx, httpd, ...) on top of kiwix-serve, you should be able to setup a authentication there.

**Comment by kelson42** [comment]
Kiwix-serve is not aimed to reimplememt all features of a typical web server. The reverse proxy is the solution to this request.
