### ISSUE TITLE
Impossible to change the language of the UI

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-tools#632]
When going to https://library.kiwix.org, the UI is in french (because my browser is configured to french).
If I go to the "language" button (on top rigth) and select english. The page is reloaded but the UI is still in french.

Even when going in the developer view and changing the cookie `userlang` to `en`, when reloading the page, UI is in french.

**Comment by rgaudin** [comment]
This is due to our removal of cookies from kiwix-serve response in varnish configuration.
We need to figure out https://github.com/kiwix/libkiwix/issues/995 first.

**Comment by rgaudin** [comment]
This has been solved but at the expense of removing caching. Closing as the rest will be followed up on libkiwix
