### ISSUE TITLE
Kiwix server windows x86 64 binaries not installing 

### ISSUE THREAD

**Issue by Andressolis77** [kiwix/kiwix-tools#637]
Trying to install a Kiwix server on my new windows 10/11 and won’t work on either is there something I’m doing wrong or need so it can work. I extract and run a window window temporarily pops up and then disappear instantaneously. Ran in compatibility came up with do I want to proceed window and crashed. Can I get some help

**Comment by kelson42** [comment]
To me this is not clear whatbyou exactly do and get. Can you make a screencast or share a detailed step by step procedure with what you do and what you get?

**Comment by kelson42** [comment]
No feedback, closing.
