### ISSUE TITLE
I recommend adding HTTPS to the next version

### ISSUE THREAD

**Issue by asdf5329** [kiwix/kiwix-tools#647]
It is recommended to add HTTPS encrypted communication, including the content inside, and some of them review the content inside the website title

**Comment by kelson42** [comment]
Implementing HTTPS directly in kiwix-serve was a feature request considering then ZIM built with ServiceWorker by Zimit. Considering Zimit 2.0 won’t rely on SW anymore, this seems not necessary anymore. If you want HTTPS you will have to setup a reverse-proxy.
