### ISSUE TITLE
Coordinates and info boxes are partly missing

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-tools#650]
Coordinate missing:
* https://library.kiwix.org/viewer#wikipedia_en_all_maxi/A/Port_of_Hamburg
* https://en.wikipedia.org/wiki/Port_of_Hamburg

The info box is missing in the german zim file, maybe because the german WP uses an extra type of info box for TV serial:

* https://library.kiwix.org/viewer#wikipedia_de_all_maxi/A/Monty_Python%E2%80%99s_Flying_Circus
* https://de.wikipedia.org/wiki/Monty_Python%E2%80%99s_Flying_Circus
* https://library.kiwix.org/viewer#wikipedia_en_all_maxi/A/Monty_Python's_Flying_Circus
* https://en.wikipedia.org/wiki/Monty_Python%27s_Life_of_Brian

**Comment by kelson42** [comment]
This is a topic for MWoffliner

**Comment by JensKorte** [comment]
coordinates: https://github.com/openzim/mwoffliner/issues/1131
