### ISSUE TITLE
3.6.0, CIA Fact book: use "HTTPS URL to support service workers"

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-tools#651]
Using kiwix-tools_linux-x86_64-3.6.0 with theworldfactbook_en_all_2023-06 I get:

> This page must be loaded via an HTTPS URL to support service workers.
> [Try Loading HTTPS URL?](https://pc-jens.fritz.box:8888/content/theworldfactbook_en_all_2023-06/A/index.html)

**Comment by kelson42** [comment]
Yes, you have to use IP 127.0.0.q or HTTPS.
