### ISSUE TITLE
Improve initial landing page - layout of tiles

### ISSUE THREAD

**Issue by eroyee** [kiwix/kiwix-tools#654]
With reference to the screenshots in https://github.com/kiwix/kiwix-tools/issues/653 , the order of tile placement at the initial landing page seems confusing to me. 

I would have thought that an alphabetical arrangement might be most logical, but perhaps there's something I'm missing? Accepting that there could be a reason for how the tiles display I would be interested to know the reasoning for this, and whether there might be an appetite for including an option to change the arrangement?

Cheers.

**Comment by kelson42** [comment]
@eroyee I‘m not very sure how the order is set but I believe there is not. Ultimatively this shoukd be done via popularity once https://github.com/kiwix/libkiwix/issues/489 is implemented. I don‘t think this is a good idea to allow users to sort differrently. Such a feature complexify the UI and if we really need it that woukd mean that the other catalogue search options don ‚t do their job properly.

**Comment by eroyee** [comment]
@kelson42 Thanks, specifying popularity would seem a good method of organising the tiles. 

Just so I understand, if I read https://github.com/kiwix/libkiwix/issues/489 correctly then in fact if one wanted to specify 'popularity' in alphabetical order then that would actually work too (albeit not automatically)? i.e. the popularity ranking of different zim files would be set by the server operator?

**Comment by kelson42** [comment]
> the popularity ranking of different zim files would be set by the server operator?

This is a pretty open question, bit this would be set externaly.,, probably in he library.xml.
