### ISSUE TITLE
GUI webserver interface development 

### ISSUE THREAD

**Issue by Webserv** [kiwix/kiwix-tools#660]
Any intention of adding functionality to the gui Kiwix webserver, for example autostart, daemon mode, and support for zim files using https? I’m finding that any zim file constructed with https links don’t work on the webserver

**Comment by hsushjk** [comment]
Try using supervisord+nginx[reverse proxy], supervisord can achieve autostart and daemon. nginx can achieve http to https

**Comment by kelson42** [comment]
We are not going to support HTTPs directly in kiwix-server. Same for daemon control which should be done from the command line. It’s important to notice that we won’t soon stop to publish ZIM files requiring HTTPS (with service workers).
