### ISSUE TITLE
wrong pictures in askubuntu.com_en_all_2023-11

### ISSUE THREAD

**Issue by ristein** [kiwix/kiwix-tools#662]
hey there,
I just mentioned all pictures in askubuntu.com_en_all_2023-11 are wrong.
As example I looked at these two random links:
https://askubuntu.com/questions/372607/how-to-create-a-bootable-ubuntu-usb-flash-drive-from-terminal
https://askubuntu.com/questions/809237/how-to-fix-the-destination-is-read-only-error-on-hdd-partition
On the website are correct images but in the zim-file are different ones, I don't know where these are from.
Using firefox and docker like this:
docker run -d --name kiwix -p 10234:8080 -v /path/kiwix/:/data --restart unless-stopped ghcr.io/kiwix/kiwix-serve /data/*.zim
using latest kiwix version 3.6.0

**Comment by kelson42** [comment]
ZIM is OK, https://library.kiwix.org/viewer#askubuntu.com_en_all_2023-11/questions/372607/how-to-create-a-bootable-ubuntu-usb-flash-drive-from-terminal

**Comment by ristein** [comment]
> ZIM is OK, https://library.kiwix.org/viewer#askubuntu.com_en_all_2023-11/questions/372607/how-to-create-a-bootable-ubuntu-usb-flash-drive-from-terminal
> 
> Error is probably in your docker command line, you don't follow the README properly: https://github.com/kiwix/kiwix-tools/blob/main/docker/server/README.md

it is not, in your link, the photo is wrong, on live website there is the correct one

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/sotoki](https://github.com/openzim/sotoki/issues/295)
