### ISSUE TITLE
GLIBC Not found, Docker kiwix-serve

### ISSUE THREAD

**Issue by mikepaxton** [kiwix/kiwix-tools#677]
When running docker compose up using the sample compose file i'm getting the following error:

`failed to register layer: exit status 1: /usr/bin/unpigz: /lib/aarch64-linux-gnu/libc.so.6: version GLIBC_2.33 not found (required by /usr/bin/unpigz)`

This is being run on a Raspberry Pi Zero 2 W running a 64bit version of Debian Bullseye.

**Comment by kelson42** [comment]
@mikepaxton Please share the whole command line and execution log.

**Comment by kelson42** [comment]
@rgaudin Do we have some kind of bug with our images and the RPI2?

**Comment by rgaudin** [comment]
This looks completely unrelated:

- output clearly says the offending binary is `unpigz` which is used by docker
- our docker images uses the static binaries that exists mostly to avoid such situations
- our docker images uses Alpine which does not uses glibc

@mikepaxton I'd look at your docker setup. Have you tried to run other images?

**Comment by mikepaxton** [comment]
> This looks completely unrelated:
> 
> * output clearly says the offending binary is `unpigz` which is used by docker
> * our docker images uses the static binaries that exists mostly to avoid such situations
> * our docker images uses Alpine which does not uses glibc
> 
> @mikepaxton I'd look at your docker setup. Have you tried to run other images?

This is only happening on my Raspberry Pi 2 W.  Using the same docker-compose.yml on a Pi 5 works great.
I've listed my docker-compose.yml file above, it's pretty simple and straightforward yet throughs this error message every time.
If Alpine doesn't support glibc, is this not the problem?

**Comment by rgaudin** [comment]
> If Alpine doesn't support glibc, is this not the problem?

No.

> This is only happening on my Raspberry Pi 2 W. Using the same docker-compose.yml on a Pi 5 works great.

Are you using the same SD-card on both the PiZero2W and the Pi5?

@mikepaxton, this i

**Comment by rgaudin** [comment]
@mikepaxton you did not answer my above question asking if you tried to run another image on that docker setup.

From the information you've given, your docker setup looks broken and the issue you're facing is unrelated to kiwix-serve. 
I am this closing this issue on our end. If you find anything suggesting it is indeed kiwix-serve related, please reopen.

If I were you, I'd look at how you installed docker. Maybe you installed the docker apt repository for the wrong version of debian (since you're on Debian 11 on the Zero2W)

**Comment by mikepaxton** [comment]
> @mikepaxton you did not answer my above question asking if you tried to run another image on that docker setup.
> 
> From the information you've given, your docker setup looks broken and the issue you're facing is unrelated to kiwix-serve. I am this closing this issue on our end. If you find anything suggesting it is indeed kiwix-serve related, please reopen.
> 
> If I were you, I'd look at how you installed docker. Maybe you installed the docker apt repository for the wrong version of debian (since you're on Debian 11 on the Zero2W)

@rgaudin Sorry, missed that question.  Yes, had several other docker containers up and running on the Pi Zero 2 W.  No issues with them.

I installed docker using "curl -sSL https://get.docker.com | sh".  I was running Bullseye on the Pi and double checked the shell script, it does check for bullseye and installs accordingly.  

Anyway, I ended up upgrading to Bookworm on the Pi Zero.  After that docker-compose.yml file works great now.   Looks like an issue with Bullseye and glibc.  Just did a count of containers running under bullseye, nine with no compose issues.

**Comment by rgaudin** [comment]
Glad to read!
