### ISSUE TITLE
Simple HTTPS workaround

### ISSUE THREAD

**Issue by CasaPas** [kiwix/kiwix-tools#684]
I just installed Kiwix in a docker container on my Unraid server.

Some of the Zim files won't open due to the known "HTTPS service worker" issue.

The problem being, that generally you access Kiwix via your remote browser pointing to the IP address of the Unraid server, rather than "localhost" if the files were on the host machine.

I managed to get these Zim files working, by installing a Firefox docker on the Unraid server, and setting its networking to "host" rather than "bridge". Basically this browser has access to the "host" or local files. Using this docker container browser, you are now able to access "localhost:8040" version of Kiwix.

I can now connect to my Kiwix server from a remote machine, looking at the Unraid Firefox browser using **localhost:8040/** as an address inside the Firefox docker rather than using the IP address of the Unraid server in the remote or Unraid browser.

It's a bit cumbersome, but it works until the release of the new version which is due to solve this issue.

So;

1: Local browser -> 2: Unraid Browser (IPofUnraidServer:3000) -> 3: localhost:8040

1: Tab in my remote machine pointing to the Unraid docker gui for Firefox (X.X.X.X:3000)
2: Tab inside the Firefox docker pointing to the "local" web gui for Kiwix (localhost:8040)
3: Kiwix running "locally" on the host Unraid system.

Clear as mud, as we say in Ireland.

Hope that helps someone.

**Comment by kelson42** [comment]
> I just installed Kiwix in a docker container on my Unraid server.
> 
> Some of the Zim files won't open due to the known "HTTPS service worker" issue.

Yes, this is because they have been created with ZIMit version 1.x which relies on ServiceWorkers and require HTTPS.

> The problem being, that generally you access Kiwix via your remote browser pointing to the IP address of the Unraid server, rather than "localhost" if the files were on the host machine.
> 
> I managed to get these Zim files working, by installing a Firefox docker on the Unraid server, and setting its networking to "host" rather than "bridge". Basically this browser has access to the "host" or local files. Using this docker container browser, you are now able to access "localhost:8040" version of Kiwix.

Yes, `127.0.0.1` is not impacted by the HTTPS restriction imposed by ServiceWorkers.

> I can now connect to my Kiwix server from a remote machine, looking at the Unraid Firefox browser using **localhost:8040/** as an address inside the Firefox docker rather than using the IP address of the Unraid server in the remote or Unraid browser.
> 
> It's a bit cumbersome, but it works until the release of the new version which is due to solve this issue.
> 
> So;
> 
> 1: Local browser -> 2: Unraid Browser (IPofUnraidServer:3000) -> 3: localhost:8040
> 
> 1: Tab in my remote machine pointing to the Unraid docker gui for Firefox (X.X.X.X:3000) 2: Tab inside the Firefox docker pointing to the "local" web gui for Kiwix (localhost:8040) 3: Kiwix running "locally" on the host Unraid system.
> 
> Clear as mud, as we say in Ireland.
> 
> Hope that helps someone.

Yes, thank you for them!

Two months ago we have released ZIMit version 2.x which does not rely anymore on ServiceWorkers/HTTPS. We have renewed all the ZIM files distributed at https://library.kiwix.org. Therefore you won't have to make this cumbersome things anymore.
