### ISSUE TITLE
Port kiwix-tools to docoptcpp

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-tools#691]
Currently, kiwix-tools are using getopt to parse command line.

However, this library is a unix tool and is not available on Windows [1].
As other projects (zim-tools) are using docoptcpp and it is packaged by kiwix-build, it would be nice to use docoptcpp in kiwix-tools too.

This way, we would use only one dependency to parse command line and it would simplify the compilation on Windows.

---
[1] getopt is not really complex, it would be possible to compile it on Windows, but it means find the right upstream project, probably build a meson buildsystem (as Makefile is difficult on Windows)  and integrate it in kiwix-build.

**Comment by kelson42** [comment]
@mgautierfr I gutess you have implemented this feature with #695  and therefore this issue should be closed?

**Comment by mgautierfr** [comment]
Yes it is. I don't know why it haven't been closed. We have a commit with a "fix ..."
