### ISSUE TITLE
Improve catalog search on library.kiwix.org

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-tools#693]
The search is not easy, the language names are out of order, sometimes it crashes and asks to be reinitialized.

**Comment by kelson42** [comment]
@LAfricain Sorry, but we can not start anything here. We have an issue already open for the order of the languages. If you face a crash scenario, coulf you please share the detailed procedure?

**Comment by kelson42** [comment]
@LAfricain Any feedback about the steps to reproduce the crash? Otherwise I will have to close this issue.

**Comment by LAfricain** [comment]
It's working today, even if the language is still out of order.
