### ISSUE TITLE
Feature Request - Tags

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#71]
Include tags in all (new) zims as follows, in addition to any others currently required such as _ftindex:

selection_criterion_all/medicine/etc. (any string that represents criterion by which articles were selected)
size_criterion_all/50K/etc. (target number of articles)

has_videos
has_pics
has_full_text
has_audio

has_ (any current or future attributes of an article)

These tags should also be in the catalog, but are independent of the file naming convention.

**Comment by tim-moody** [comment]
what is the status of this issue, given that several people are working on mwofflinef?

**Comment by kelson42** [comment]
I need a bit time on this.

**Comment by kelson42** [comment]
This ticket has been superseeded by https://github.com/kiwix/kiwix-lib/issues/131.
