### ISSUE TITLE
Kiwix-serve Port 8080 cannot be re-mapped using portainer

### ISSUE THREAD

**Issue by Spfd0** [kiwix/kiwix-tools#712]
This is more of a personal issue rather than the  kiwix container not working, If I wanted I could stop my other container that currently uses port 8080, when I really need to access kiwix.

Portainer logs:

Unable to instantiate the HTTP daemon. The port 8080 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024. <----- ( ofc seeing this as I have another container using port 8080 )

BUT

Was wondering if it was an easy fix to push.

All you would have to do is give the client access to change the "command" where you import the .zim files. 

version: '3.7.0'
services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - /home/docker/kiwix:/data
    network_mode: host
    command:  
      *.zim   <------------ "command"
    restart: unless-stopped

Portainer logs:

"/usr/local/bin/kiwix-serve --port=8080 *.zim"
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    Command is auto ran with no way of changing.

This does mean you would have to not automatically set the port in the first place and let the client decide which port they would like to use.
Would give the client a little more configurability.

Do let me know! Would love to have kiwix running with my other containers, using portainer.

**Comment by Spfd0** [comment]
In the end I was able to move my other container to solve the issue. 

But would be nice to have the choice to do so!

Thanks for such an amazing project.

**Comment by kelson42** [comment]
The container engine allows to remap the container internal port (here 8080) to any other port, so I don't understand why we shoukd allow to change the internal port.

**Comment by Spfd0** [comment]
Are you referring to the remapping as in adding in this? 

version: '3.7.0'
services:
kiwix-serve:
ports: <------
        - 8081:8080 <------
image: ghcr.io/kiwix/kiwix-serve
volumes:
- /home/docker/kiwix:/data
network_mode: host
command:
*.zim <------------ "command"
restart: unless-stopped


Sorry if I worded anything wrong or I'm asking questions that don't make sense. Still new to using docker and portainer.

**Comment by Spfd0** [comment]
Either way I do have the kiwix container up and running on the default port. So it was just a personal preference kind of thing and a lack of knowledge on my end.

**Comment by kelson42** [comment]
> Are you referring to the remapping as in, adding in this?

Yes
