### ISSUE TITLE
kiwix-serve intermittently crashing

### ISSUE THREAD

**Issue by tripplehelix** [kiwix/kiwix-tools#718]
I'm seeing the kiwix-serve crash randomly. No logs that I can find.

Running the arm64 version from the kiwix website: 
https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-aarch64.tar.gz

This is running on a Raspberry Pi 5, Raspberry Pi OS Lite, Linux 6.6.62+rpt-rpi-2712, Debian 12.8

```
❯ kiwix-serve --version
kiwix-tools 3.7.0

libkiwix 13.1.0
+ libzim 9.2.1
+ libxapian 1.4.23
+ libcurl 7.67.0
+ libmicrohttpd 0.9.76
+ libz 1.2.12
+ libicu 73.2.0
+ libpugixml 0.12.0

libzim 9.2.1
+ libzstd 1.5.2
+ liblzma 5.2.6
+ libxapian 1.4.23
+ libicu 73.2.0
```

I'm starting the package through systemd with the following user service:

```
[Unit]
Description=Run the kiwix server

[Service]
Type=exec
TimeoutStartSec=0
ExecStart=/usr/local/bin/kiwix-serve --skipInvalid --verbose --monitorLibrary -i 0.0.0.0 -p 8005 --library /mnt/mega/Documents/zim/library_zim.xml
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
```

The library and ZIM files are hosted on a connected USB RAID1 device. Has worked perfectly in the past with previous installations. No issues reported on the RAID.

**Comment by kelson42** [comment]
@tripplehelix Thank you for your bug report. For the moment this is obviously a bit difficult to know what cause these crashes. Usually we have 3 categories of crashes:
* A ZIM file is somehow corrupted and this is badly handled by kiwix-serve
* There a bug in some kind of handling (unrelated to the content) in kiwix-serve
* The memory is exausted

The first thing I would recommend is to gove atry with a nightly dev build, as many improvements have already been made but not released yet. Would that be possible for you to give a try to https://download.kiwix.org/nightly/2024-12-25/kiwix-tools_linux-aarch64-2024-12-25.tar.gz and let us know if it works better?

**Comment by tripplehelix** [comment]
It seems to be stable at the moment with the regular release. I was also running Kavita, which I think was the cause that would constantly take it down. As you said, my guess was RAM issues, as it took another service down with it too.

**Comment by kelson42** [comment]
OK, so closing the issue. If you have still a clear problem with `kiwix-serve`, please try the nightly and if this is still there then we would be glad to run an investigation together to see if there is a bug in the software.
