### ISSUE TITLE
Disable animation on accordeon

### ISSUE THREAD

**Issue by okkebal** [kiwix/kiwix-tools#73]
Kiwix-serve shows a Jquery UI Accordeon to show the site selector. Animate is on here. Animate does not work at all on a long list on desktop and especially on mobile devices! It literally takes 10 seconds to animate on my Huawei P8, wich is a pretty fast phone. Problem here is Icecat, or firefox wich animates horribly. Its totally unusable this way.

The solution is very simple. Turn off the animations:
http://api.jqueryui.com/accordion/#option-animate

Like so:
```javascript
  <script>
  $( function() {
    $( "#accordion" ).accordion({
         animate: 0
    });
  } );
  </script>
```

**Comment by okkebal** [comment]
by the way A P8 has: 

Octa-core, 2000 MHz, ARM Cortex-A53, 64-bit and 3 GB RAM

**Comment by kelson42** [comment]
Have you try one of the latest nightly build (kiwix-tool tarball) http://download.kiwix.org/nightly/ ? The kiwix-serve welcome page UI has changed.

**Comment by kelson42** [comment]
I close the ticket as this ticket refer to an outdated bug.

**Comment by okkebal** [comment]
I've tried the latest "kiwix-tools" (just a guess). I found some files in there that are also present in my /kiwix/xulrunner folder of my Windows installation of Kiwix. So I just overwrote the kiwix-serve.exe.

Now it does not work anymore, it sais: "The program cannot be start because msvcr90.dll is missing."

**Comment by kelson42** [comment]
@okkebal can you please just replace kiwix-serve.exe ? And maybe also just try to run it manually?

**Comment by okkebal** [comment]
I am running it from the command-line. I guess I'm missing some Visual C redistribatable, but no idea wich one.

**Comment by okkebal** [comment]
I restored the other executables from a portable kiwix version. Just kiwix-serve.exe is new now. Same problem.

**Comment by kelson42** [comment]
@okkebal Interesting... The missing library is a standard one of Microsoft Visual Studio. It's not uncommon to miss it for VisualStudio projects... but in our case it's not a Visual Studio project... so I kind of wonder.

You should be able to fix the problem by install this microsoft library https://www.microsoft.com/en-us/download/details.aspx?id=26368&tduid=(632bec231c6243eab165a330f51ef138)(229527)(1983911)(68756X1554900X0d0e2eac9068781d0670e8761729289b)()

Let me know if that fix the problem.

**Comment by okkebal** [comment]
I already have those installed. So no solution there. I am using Windows 8, and I you must know that Windows is very unreliable, os it could be my installation that f**-ed
