### ISSUE TITLE
Kiwix-Serve renders random unicode in-place of non-ascii

### ISSUE THREAD

**Issue by darkenvy** [kiwix/kiwix-tools#74]
When using kiwix-serve, random unicode appear near/in-place of where other unicode should go. Example: a em-dash `–` should display, but instead `âˆ’` appears in it's place.
![kiwix-serve showing bug](https://puu.sh/xubbu/e8e42661cc.png)

When extracting the zim using zimdump, the bug appears to be gone and the input file is identical to the output file for the text (the same exact unicode appears). This implies that the information is perfectly preserved and points to kiwix-serve having the bug.
![html file dumped from zimdump](https://puu.sh/xubeq/52915ba506.png)

If I open the zim using the chrome extension zim-reader, the error does not appear and renders as it should. Absolutely perfectly :).
![no bug when using chrome extension](https://puu.sh/xubdP/0877d570f0.png)

You can see this bug on our private server here ![Absolute_Zero article on kiwix-serve](http://iiab.me:3000/20170901_(Americano)_enwiki-pics/A/Absolute_zero.html). We use the Absolute Zero article for our example, but the error shows up all over the place.

To recreate this, simply use zimwriterfs on a downloaded Absolute_Zero article html file.

**Comment by darkenvy** [comment]
Also note the `Â` thats comes out of nowhere between `273.15` and `°`. (It's supposed to be `273.15Â°`.)

It wouldn't be so weird if it replaced another character in this instance, but it just came out of nowhere!

**Comment by mgautierfr** [comment]
I cannot reproduce the bug.

- The zim file I use is generated using mwoffliner with a "article list" containing only one article "Absolute_Zero".
- I use a kiwix-serve compiled statically using the last version (a210cb3a4b9b7d0f).

The text  `−273.15°`  is displayed correctly both on firefox and chrome.

Which version of kiwix-serve are you testing ?

**Comment by mgautierfr** [comment]
And also, you last link ("Absolute_Zero article on kiwix-serve.") doesn't work for me.
Have got a page with "Non-Image content-type returned" as sole content.

**Comment by mgautierfr** [comment]
It could be a rendering problem.

The fonts used on my side are `DejaVu Sans` on Firefox and `Liberation Sans` on chrome (both on linux Fedora 26)
What is the font use on your system ? Depending of your system (os, browser, font installed, ...) you may use a police that cannot render the symbol.

Can you also upload the file returned by kiwix-serve ? (wget on the url)

**Comment by darkenvy** [comment]
I don't get alerts for when people reply to my issues on GH. I didn't know I got responses.
I'll upload an example when I get back. By the way, others see the issue too from the zims I produce.

I see the same effect of mwoffliner working fine and not producing the bug (looking back on older zims produced that contain this article. However, this issue is about kiwix-serve and/or zimwriterfs.

Seeing as zimwriterfs is the magic that creates all zims, it should really come down to input and output. Before and after zimwriterfs ;).

Are you on irc? Handle?

**Comment by darkenvy** [comment]
Zim containing the bad characters. Try unzimming this using zim-tools. What you get out is exactly what goes in! (no corruption).

This is made manually by using zimwriterfs.
https://drive.google.com/file/d/0B3QuWOYlCSL1bzBVMlMyNHFJcVE/view?usp=sharing

**Comment by mgautierfr** [comment]
@darkenvy 
I can confirm the bug with your zim.

However, I don't think it is a problem in kiwix-serve but about your source files.
The "MINUS SIGN"  is encoded with `0xE2 0x88 0x92` which correspond to its utf8 encoding (http://www.fileformat.info/info/unicode/char/2212/index.htm).
This is what `kiwix-serve` return to any request (firefox, chrome, wget. Compression or not)

But you are not declaring an encoding. So browser use a default one (which seems to be occidental or windows-1252). Forcing Firefox to use utf8 encoding make it display the article correctly.
You can see a error displayed by Firefox about this when loading your page with development tools opened.

You should add a encoding to your file. (mwoffliner keep a ` <meta charset="UTF-8">` in `<head>`.)

**Comment by kelson42** [comment]
I think it's pretty clear here we do not deal with a bug in either kiwix-serve or zimwriterfs.

@darkenvy again, please use mwoffliner to snapshot Wikipedia instead of what looks like trying to re-inventing the wheel... we see here that we all lost time because of that...
