### ISSUE TITLE
kiwix-manage regression on rpi

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#76]
on 2017-09-07-raspbian-stretch-lite.img
using nightly kiwix-tools_armhf_2017-09-19.tar.gz (also 2017-9-12)

/opt/iiab/kiwix/bin/kiwix-manage /library/zims/library.xml add /library/zims/content/wikipedia_en_medicine_2017-08.zim

results in 

last cluster offset larger than file size; file corrupt
Unable to build or save library file '/library/zims/library.xml'

/opt/iiab/kiwix/bin/kiwix-manage /library/zims/library.xml add /library/zims/content/wikipedia_es_medicine_2017-04.zim succeeds (so may be the zim)

I have not observed this on linux64 for either zim.

**Comment by tim-moody** [comment]
for more info I tried

root@box:~# /opt/iiab/kiwix/bin/kiwix-serve --port 3000 --nolibrarybutton /library/zims/content/wikipedia_en_medicine_2017-08.zim

and got same issue

last cluster offset larger than file size; file corrupt
Unable to add the ZIM file '/library/zims/content/wikipedia_en_medicine_2017-08.zim' to the internal library.

**Comment by darkenvy** [comment]
I made a zim with just one MP4 video using zimwriterfs and experienced the same problem. (to help isolate the problem). https://puu.sh/xHRRK/063a485ea8.png

**Comment by mgautierfr** [comment]
This is not especially a problem with arm but instead a bug in `libzim` crashing when trying to read a zim file larger than 4GB on a 32 bits platform.

Next nightly build should be ok.

@darkenvy, Does your zim file is larger than 4GB ?
The error message about the MIME type video/mp4 makes me think it is a different problem.
(zim file can be read, but there is a problem somewhere about the return mimetype).
If your issue is not fixed with last nightly build, please open a new issue.

**Comment by holta** [comment]
FYI @mgautierfr I get the same error after waiting 36h and trying the latest nightly build (http://download.kiwix.org/nightly/2017-09-25/kiwix-tools_armhf_2017-09-25.tar.gz).  Which I installed onto RPi3 / Raspbian Stretch then ran:

> /opt/iiab/kiwix/bin/kiwix-serve --port 3000 --nolibrarybutton /library/zims/content/wikipedia_en_medicine_2017-08.zim

Which still yields error:

> last cluster offset larger than file size; file corrupt
Unable to add the ZIM file '/library/zims/content/wikipedia_en_medicine_2017-08.zim' to the internal library.

While "md5sum wikipedia_en_medicine_2017-08.zim" is confirmed identical on 2 other machines, including @tim-moody's:

> 23ab5434f3f6b750feabe6d64f01cc02

Background: This ZIM was generated as follows:

> wget http://download.kiwix.org/portable/wikipedia/kiwix-0.9+wikipedia_en_medicine_2017-08.zip

> unzip kiwix-0.9+wikipedia_en_medicine_2017-08.zip

> cat wikipedia_en_medicine_2017-08.zimaa wikipedia_en_medicine_2017-08.zimab wikipedia_en_medicine_2017-08.zimac > wikipedia_en_medicine_2017-08.zim

After moving the wikipedia_en_medicine_2017-08.zim.idx and wikipedia_en_medicine_2017-08.zim into their normal positions, the following did not help :/

> systemctl restart kiwix-serve

**Comment by kelson42** [comment]
@holta Not sure you have caught a version with the fix... Can you just try the really last one: http://download.kiwix.org/nightly/2017-09-28/kiwix-tools_armhf_2017-09-28.tar.gz

**Comment by holta** [comment]
@kelson42 it works great, including:
- title search
- full-text search
- videos work, e.g. http://box:3000/wikipedia_en_medicine_2017-08/A/Measles.html

Thanks!  Will the linux64 version possibly be available today too?
