### ISSUE TITLE
Move kiwix-serve primitives to kiwix-lib

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#8]
kiwix-serve binary should only rely on kiwix-lib and not on libmicrohttpd, ctpp2, etc.

**Comment by mgautierfr** [comment]
For ctpp2 yes. libkiwix.pc should declare that it needs ctpp2 and it should just work.
But ctpp2 doesn't provide a pkg-config file, so we have to refind ourselves the dependency.
We have to provide a patch to ctpp2 do handle it (or at least have kiwix-builder create the libctpp2.pc file).

For libmicrohttpd, I'm not sure. libmicrohttpd is used only by kiwix-serve. I see no reason to this dependency in kiwix-lib.

**Comment by legoktm** [comment]
Have we asked the ctpp2 upstream (<http://ctpp.havoc.ru/en/faq.html>) to provide a pkg-config file? If not, I think that would be a good idea.

**Comment by kelson42** [comment]
@mgautierfr What is exactly the status on this? I think ctpp2 is now in kiwix-lib and we have decided to keep libmicrohttps in kiwix-serve so far. What is also the point regarding @legoktm's question?

**Comment by kelson42** [comment]
kiwix-desktop 2.0 will include the HTTP server feature, so we will have to do it in the next months.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-lib#138
