### ISSUE TITLE
extraneous strings displayed on medical wiki in kiwix-serve

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#81]
on rpi3 with kiwix-tools_armhf_2017-09-28.tar.gz displaying wikipedia_en_medicine_2017-09.zim in kiwix-serve:

'__CSS_LINKS' is displayed at top

'__ARTICLE_CONFIGVARS_LIST__' is displayed below attribution

**Comment by tim-moody** [comment]
is the output meant to be mobile friendly for non-mobile devices. it used to be centered and now is left justified?

**Comment by tim-moody** [comment]
I don't see this problem with wikipedia_en_medicine_2017-08.zim (same platform and kiwix-serve) 

(the page is also centered as before)

so must be zim

**Comment by kelson42** [comment]
@tim-moody I confirm the bug. This was a bug/regression in mwoffliner. The bug has been fix in mwoffliner master. I'm currently regenerating these problematic files for october. The file you have reported is already fixed and uploaded. Thx for the report and sorry for the regression.
