### ISSUE TITLE
Why are Kiwix searches blocked when asking for more than 67 results?

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#92]
Searching for almost any **67 things** works:
```
http://box:3000/search?pattern=pomme&start=1000&end=1067
(a few min later it shows "Results 1001-1067 of 6,980 for pomme")
```
Searching for almost any **68 things** does not:
```
http://box:3000/search?pattern=pomme&start=1000&end=1068
(about 30 sec later, an empty page is returned)
```
Can this "67" parameter be increased (whether hard-coded or modified by local operators) so that students and teachers can efficiently find what they're looking for?  For example the following popular search fails unfortunately, as it requests more than 67 search results:
```
http://box:3000/search?pattern=pomme&start=0&end=100
```
Context: every time you click for 25 more search results, it costs you 30-60 seconds or sometimes much more.  So serious teachers and serious students would like to see the first 100 results all on one page (or possibly even a much larger number) to avoid bureaucracy, if at all possible!

**Comment by mgautierfr** [comment]
There were two things here:

- An explicit limitation to 70 search results. I have extended it to 140.
- A "bug" when rendering more than 67 search results. ctpp2 templating engine is limited in the number of step and the default limit make it raises an exception if we were try to render more than 67 results. I've double the limit and now ctpp2 is able to render up to 144 results. As we are limiting explicitly the number of result to 140, it should be ok.
