### ISSUE TITLE
Kiwix-Serve 0.3.0 cannot find assets in zim

### ISSUE THREAD

**Issue by darkenvy** [kiwix/kiwix-tools#93]
I have zims that work perfectly. Upon upgrading to 0.3.0, I noticed that I get a lot of 404s on my asset files. Such as angular.min.js. These files are in the zim and work in previous versions of kiwix-serve, and zimdump even verifies that the files are in the correct spot and exist.

[link redacted. PM me on IRC for the link]
"angular.min.js" are 404'd, but other assets such as "jquery.js" and "article_list.js" are found just fine.

Here is a really tiny zim showing this problem as well:
https://drive.google.com/open?id=19JXrnwB8hf7Xs0WAJ20NPtVzXAqdtGZj

**Comment by kelson42** [comment]
@darkenvy This ZIM file does not contain the file "angular.min.js", see:

```
$ zimdump -l 2017-11-04_1440.zim | grep angular.min.js
$ 
```

Please always check that:
* The ZIM file contains the content/article you try to read
* This article is at the right place

**Comment by darkenvy** [comment]
@kelson42 , that zim doesn't have angular.min.js in it. That zim suffers from article_list.js saying its not found but it is. See the other zim with the link I redacted and psoted on IRC.

Okay, I got approval to post the link: http://  iiab.me : 3000 /20171018_Ansuz_frwiki_2gb/

**Comment by kelson42** [comment]
@darkenvy Please post a link to download the ZIM file
