### ISSUE TITLE
Kiwix-Serve 0.3.0 Upgrade now 404s assets in already created zim.

### ISSUE THREAD

**Issue by darkenvy** [kiwix/kiwix-tools#95]
http:// iiab.me : 3000 /20171018_Ansuz_frwiki_2gb/

I have zims that work perfectly before the 0.3.0 upgrade on kiwi-serve. Upon upgrading to 0.3.0, I noticed that I get a lot of 404s on my asset files. Such as angular.min.js. These files are in the zim.

zimdump 20171018_Ansuz_frwiki_2gb.zim -D output/

The file DOES exist in the zim, because if you host with a older version of kiwix-serve, angular.min.js is found and used on the index.html homepage of that zim.

I am uploading the zim via filemail.com. Posted Below.

UPDATE: **https://fil.email/4rTNh7yi**

**Comment by kelson42** [comment]
File is available at http://tmp.kiwix.org/reno.zim

**Comment by kelson42** [comment]
It seems to be still a bug with last nightly of zimwriter and the '-' namespace:
```
zimdump -n '-' -f angular.min.js -d reno.zim
```
Put kiwix-serve returns 404 to /reno/-/angular.min.js
